### ISSUE TITLE
How to support the failover from the view of CoAPServer?

### ISSUE THREAD

**Issue by TerenceYi** [eclipse/californium#1045]
In my testing deployment, my device simulator is communicating with a software load balancer (LB)which configured two CoAPServer(Based on Californium, refer as CS1 and CS2) in the backend.
Here is my fail-over testing sequence:
<img width="545" alt="CoAPFailover" src="https://user-images.githubusercontent.com/26319217/63484029-db1f1600-c4d0-11e9-896e-14d7002544f6.PNG">

My question is:
In my testing, my simulator will retransmit the second notification until reaching the max-retransmit limit(set as 4)
1. Any reference for this scenario,(CoAPServer might restart for some reason, upgrade/maintain restart, etc)
2. Is there any way Californium can let the device to initialize a new handshake

**Comment by boaks** [comment]
Let me start with:
You want to cluster a (coap-)client. Usually (coap-)servers are clustered. For the most other protocols that is related to the tcp/tls roles. With that usual roles, a client sends a request (and therefore the client has state related to that request) to the server. If that breaks, the client repeats and sends it request to the next server. The servers must be "stateless" to support that.
No, if you exchange the roles, one client sends a request  (and therefore the client has state related to that request) and gets multiple responses. And if your client breaks, an other client must take his role (and all the state, a client usually has).

With that ahead, clustering a client is not too easy.
On good source of information is [Leshan Wiki](https://github.com/eclipse/leshan/wiki/F.A.Q.).
To your questions:
1. Californium offers an [ObservationStore](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/observe/ObservationStore.java), which enables to implement a "distribute variant". See Leshan has such a implementation in his cluster modules. AFAIK you lose the "notification ordering" within the protocol. If required, you must add the order information to your payload and sort it out on application layer.  

2. As long as you send CON messages (Notifies) and therefore wait for ACKs you may use the retry counter to trigger a new DTLS handshake. That comes also with a small break, here the deduplication (the server (coap-client) breaks, after processing the notify before sending the ACK). You may also use an approach, where you trigger a new DTLS handshake based on the time since the last message was exchanged. Californium offers that feature on the dtls-client/device as "auto resumption" [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1692), but

**Comment by TerenceYi** [comment]
Really appreciate your reply!
ObservationStore is what I am working on. I checked the implementation you mentioned in Leshan, which put the observation relationship to Redis. Minor question do you think it is better to add recovered ExChange to the ExChangeStore, then needn't lookup Observation from Redis for every notification.

You right seem I am trying to set up a cluster for CoAPClient from the view Observation.

Could share the approach you mentioned about how can I survivor from the one CoAPServer fail?

**Comment by boaks** [comment]
> Minor question do you think it is better to add recovered ExChange to the ExChangeStore, then needn't lookup Observation from Redis for every notification.

My impression was, that the ObservationStore can work as cache and so that should not be a too big penalty. Maybe @sbernard31 can give you more details about that.

> Could share the approach you mentioned about how can I survivor from the one CoAPServer fail?

Do you mean the answer to your 2, question about the new DTLS handshake?
Do you use californium on the device?

**Comment by TerenceYi** [comment]
In my testing deployment, Device simulator using Californium.
In a production deployment, Device talking to my platform with CoAP. That's why I looking for a recommendation about handle the fail-over

**Comment by TerenceYi** [comment]
> > Minor question do you think it is better to add recovered ExChange to the ExChangeStore, then needn't lookup Observation from Redis for every notification.
> 
> My impression was, that the ObservationStore can work as cache and so that should not be a too big penalty. Maybe @sbernard31 can give you more details about that.
> 
> > Could share the approach you mentioned about how can I survivor from the one CoAPServer fail?
> 
> Do you mean the answer to your 2, question about the new DTLS handshake?
> Do you use californium on the device?

**Comment by boaks** [comment]
For the Server (which is a coap-client in your case), you can't use the `CoapClient` class, that only support simple "none clustered" clients.

For the device (which is a coap-server in your case):
I guess, you frequently fire notifies. If the interval between the notifies is smaller than 30s, then the "auto resumption" is no good choice. That is invented for clients, which rarely sends notifies (e.g. every couple of minutes). To trigger a dtls handshake when retransmissions reach a limit (before the max. retries), I implement a `MessageObserverAdapter` overriding at least the `onRetransmission()`. There I use 

```
EndpointContext destinationContext = MapBasedEndpointContext.addEntries(
        observed.getDestinationContext(), DtlsEndpointContext.KEY_RESUMPTION_TIMEOUT, "0");
observed.setDestinationContext(destinationContext);
```

to trigger the dtls handshake with that retransmission.

**Comment by sbernard31** [comment]
Just in case you didn't find it : 
https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster
https://github.com/eclipse/leshan/wiki/Server-Failover

To answer more specifically to your failover question, DTLS connection is not shared but observation state can be (You already see that with Redis).
So if **server1** is down. your notification will be sent to **server2** which will ignore it as it is unable to decrypt it.
If you are using a CON, if CON timeout you can try to rehandshake and resent your CON.
(If you want more reactivity you can consider a shorter timeout than the classic CoAP MAX_TRANSMIT_WAIT)

Keep in mind that failed over is probably not the only one case where this could happened. (expiration of LB association table entry could cause this kind of issue too)

> AFAIK you lose the "notification ordering" within the protocol

This is not clear for me too, but I also think that "notification ordering" is not really well supported in this case.

**Comment by TerenceYi** [comment]
Thanks for your info.

I'm fully understood now. The fail-over needs to be considering both the Client&Server side. There is no easy way to implement it from the server-side only.

BTW, will you consider to make Californium configurable that for unable decrypt message whether ignoring or return an alert?

**Comment by sbernard31** [comment]
> BTW, will you consider to make Californium configurable that for unable decrypt message whether ignoring or return an alert?

The [DTLS RFC](https://tools.ietf.org/html/rfc6347#section-4.1.2.7) does not recommend this.

**Comment by boaks** [comment]
"notification ordering" 

[Reordering, coap-client](https://tools.ietf.org/html/rfc7641#section-3.4)
[Reordering, coap-client](https://tools.ietf.org/html/rfc7641#section-4.4)

The client stuff is implemented in:
[Client Observe Relation](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/CoapObserveRelation.java#L283)
[Client Notification Order](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/observe/ObserveNotificationOrderer.java)

AFAIK, that client stuff is not used in leshan. And my experience is, that too many devices have "broken" coap-server, which are not able to provide a proper obser-number. But that may be just limited to my own experience, others may have a better ones. That notify observe-number will change on every notification and may be required to be sync on every notification between the cluster nodes. That may not pay off. Therefore I think, if it gets required for an application, to support "cluster" and "order", it must be pushed into the application-layer.

**Comment by boaks** [comment]
> BTW, will you consider to make Californium configurable that for unable decrypt message whether ignoring or return an alert?

I personally don't consider it, but contributions are always welcome.

FMPOV, your test naturally over-emphasis the "fail-over-case". In my experience californium runs stable enough to run days (sometimes weeks) without shutdown. If you consider that, the ALERT, which helps to "fail-over", would be a rare case, where the ALERT, which may be misused by an adversary, will be more probable. 

(Using "once upon a day" the Connection ID (see [CID Load Balancer](https://github.com/eclipse/californium/wiki/DTLS-1.2-connection-ID-based-load-balancer) would reduce the "invalid MAC" behind NATs and in a cluster. In some experiments (using a Android App) my result was, that the dtls session on the server side is less invalid, it's more that the server is generally not reachable for the smartphone.)

**Comment by TerenceYi** [comment]
<blockquote>
<p>Therefore I think, if it gets required for an application, to support "cluster" and "order", it must be pushed into the application-layer</p>
</blockquote>
Thanks for your clarification. I think for support "cluster" we have ObservationStore. For "order" will just push to the application layer.

<blockquote>
<p>FMPOV, your test naturally over-emphasis the "fail-over-case". In my experience californium runs stable enough to run days (sometimes weeks) without shutdown. If you consider that, the ALERT, which helps to "fail-over", would be a rare case, where the ALERT, which may be misused by an adversary, will be more probable.</p>
</blockquote>
I have testing and running Californium for weeks, so I do believe Californium is stable in my testing scenario. But restart is common for a software service.
In my client's production deployment, all device are NB Device(Device is made and developed by the client's client) which extremely cares about the battery efficiency(lifetime expected to be few years).

From your comments seems Alert is not a good choice. But do you think a "HelloRequest" will help me on my case?

**Comment by boaks** [comment]
Unfortunately, "HELLO REQUEST" function is removed in in Scandium.
There different views/opinions on the proper usage. In TLS it's used, when you have already a connection and the server want to renew the keys. For the usual cases (session gone) in DTLS this doesn't make too much sense. To use it without encryption would create an "amplification attack surface", though the "HELLO REQUEST" is very small compared to the "CLIENT_HELLO".

>  But restart is common for a software service.

At least in theory. In practise a lot of stuff would have to support "more frequent restarts".
And a restart with "graceful shutdown" is something else as a "recover restart".
It's not implemented for now, but, if one node knows, that it gets shutdown, generally the "association (connection) state - keys, anti-reply window" could be transferred to other nodes. 
May be in a future extension of scandium.
Currently I plan the "finally" release californium 2.0 (with 2 year delay :-) ). So I don't think, that will be added before.

@sbernard31 
What do you think? Also after 2.0?

**Comment by boaks** [comment]
> From your comments seems Alert is not a good choice. But do you think a "HelloRequest" will help me on my case?

Let me add: both would require a handshake, at least a resumption handshake! 
Therefore the benefit compared to handshakes trigger by retransmission may not be that large.

**Comment by TerenceYi** [comment]
Thanks for your time looking into issue.

I understood that a new handshake is required. The max re-transmit is set to 4 in the device, compare to direct response with an alert or HelloRequest it is a hard sell for me to make my client accept it(handshake trigger by retransmission exhaust).
Anyhow really appreciate your time again!

**Comment by boaks** [comment]
> I have testing and running Californium for weeks, so I do believe Californium is stable in my testing scenario. But restart is common for a software service.

If your timelines are very close, one approach you may consider is to run californium in front as "proxy/load-balancer" and do the real "application-aware-processing" behind that on other nodes/machines. That adds some latency, a "californium-load-balancer" will also be not too fast, but it would enable you to exchange your application without running into dtls issues. At least for the next couple of months. If you are more exploring, you may also run only scandium in front, and pass the "RawData" together with some context to the next machine.

But, any of these ideas, may or may not work with the "observe-notify".

**Comment by boaks** [comment]
> all device are NB Device(Device is made and developed by the client's client)

So, hope the client has experience with DTLS. The first common funny thing to see is, all openssl cipher suites proposed in the very large CLIENT_HELLO :-).

**Comment by TerenceYi** [comment]
you are right, CS is 11, in the ClientHello :)

**Comment by boaks** [comment]
> all openssl cipher

usually it's about 70 for none configure openssl clients. And a lot of them are not really supported, because the credentials are not configured on the device.

For californium we had a discussion about the "default cipher suites" (see #909). We use "all" (where the credentials have been provided), and "less, selected" is up to the configuration. In the meantime we "deprecated the CBC ciphers (not recommended)", so the default is now "all recommended" (where the credentials have been provided).

**Comment by sbernard31** [comment]
@TerenceYi, the problem you exposed in classic one.
FMPOV : 
- sending an ALERT seems really not a good idea.
- HELLO_REQUEST is not intended to be used like this as @boaks explained it's about re-negociation. (see [rfc5246](https://tools.ietf.org/html/rfc5246#section-7.4.1.1))

The issue here is how to be able to detect that DTLS connection is lost at server side.
It seems that the general spirit is to not send any data  if we receive messages we are not able to decrypt.

So the only one real solution is to handle the case where server does not answer and to consider that the connection is maybe lost and so rehandshake and retry.  **FMPOV you can not avoid to handle this.**

The drawback is with default CoAP retransmission mechanism this could be long to detect (~93s).
To reduce this time, you could image to : 
 - use a [DTLS Heartbeat](https://tools.ietf.org/html/rfc6520) which is not supported by scandium.
 - just not wait all the CoAP retransmission for your CON.
 - if this is not possible to do that with your coap library during a notify, maybe you could consider to use a coap ping (there is maybe more chance that you library let you use a smaller timeout).

@boaks idea about sending CLOSE_NOTIFY on server shutdown (or connection expiration/eviction) could help.
This way the client could received it and it will know it need to rehandshake next communication time. 
This is just an improvement (probably a good one), but nothing guarantee that you really receive it (UDP packet loss, loadbalancing association expired, device sleeping ...)
So you still MUST handle the case where "server does not answer" == "dtls connection lost".

Just a thought about this, but this could generate a kind of server initiated message, which could cause some trouble with some loadbalancer which is generally designed to handle client initiated communication. ([here some strange behavior](http://archive.linuxvirtualserver.org/html/lvs-users/2018-11/msg00002.html), I faced with LVS/netfilter) To resolve this kind of issue, I'm currently working on an [UDP loadbalancer](https://github.com/AirVantage/sbulb) (not finished for now).

> What do you think? Also after 2.0?

After 2.0 sounds good to me.

**Comment by boaks** [comment]
> @boaks idea about sending CLOSE_NOTIFY on server shutdown (or connection expiration/eviction) could help.

I'm not sure, if this is a misunderstanding. My intention of a graceful shutdown is to stop communication for one node and start it for a other node, which first mainly queues the messages. Then transfer the security context from the stopped to the new node and process the queued messages. but there is a lot to implement for that.

CLOSE_NOTIFY on shutdown requires the devices to be on, when the server shutsdown, otherwise this may be ineffective.
 
So, for now, I think, if scaling is not a matter, using californium as coap/dtls proxy and forward the coap messages then to a second application node, is the shortest way to achieve somehow "high availability". That should limit the scenarios, where the devices required to handshake.

**Comment by sbernard31** [comment]
> I'm not sure, if this is a misunderstanding. My intention of a graceful shutdown is to stop communication for one node and start it for a other node, which first mainly queues the messages. Then transfer the security context from the stopped to the new node and process the queued messages. but there is a lot to implement for that.

You're right this is a misunderstanding.
Maybe I wrong but I guess this will not be so easy. E.g. I asked myself how to know which node should receive the new state.

**Comment by boaks** [comment]
> Maybe I wrong but I guess this will not be so easy. 

I guess, you're right, this will not be too easy ...

> E.g. I asked myself how to know which node should receive the new state.

Therefore I distinguished between a planned switch over (blue/green), where the new node with the new application version takes over the traffic and gets the security contexts from the old node. that creates a "in between window", in which the messages must be queued in the new node. I hoep the window will be only a few seconds (<10 :-) ). But yes, all not too easy and all not implemented.

**Comment by boaks** [comment]
Just for information:

The #1424 gets more and more available.

[built-in CID-load-balancer](https://github.com/eclipse/californium/tree/wip_dtls_cid_cluster/demo-apps/cf-extplugtest-server#built-in-dtls-connection-id-load-balancer-cluster)

Feedback is very welcome.

**Comment by boaks** [comment]
PR #1486 (graceful restart) reduces the number of required handshakes.
More "failover" is not planned for the next time ...
