### ISSUE TITLE
Sending message break the ongoing handshake from client in 2.0.0-M9

### ISSUE THREAD

**Issue by joechen2010** [eclipse/californium#1065]
In 2.0.0-M9,  DTLS server always create a new handshake if there is no session established when sending message, this may break the ongoing handshake from client.
here is the tcp dump.
 [
![handshake](https://user-images.githubusercontent.com/340663/64334883-2aeef880-d00c-11e9-9cd0-8f1d44d6f5ab.jpg)
](url)

we also notice that there is a fix on 2.0.0-M13, https://github.com/eclipse/californium/commit/6a6a827a057c98b3778c9fa89590a1855b664e18 
there is an item "Reuse ongoing handshaker instead of creating a new one." in this commit. 
Is this changed fix this issue? is there any issue ticket relate to this bug?

**Comment by boaks** [comment]
The connection management in scandium was redesigned over several milestones.
The reasons have been:
- clean multi-threading
- DTLS 1.2 connection ID.

No, I don't know any ticket, which is related to that behaviour.
Today we released 2.0.0-M17, with a couple of security fixes. 
May be you have a look on that, if it fits for you.

**Comment by boaks** [comment]
Just to mention:
- your scenario looks similar to a race condition; the CLIENT_HELLO from the client may be on the way, so the server doesn't know about that. In that cases the server would start a handshake.
- to prevent such rare race conditions, the new version provides also a "server only" DtlsConfiguration, so the server never starts a handshake.

**Comment by sbernard31** [comment]
> your scenario looks similar to a race condition; the CLIENT_HELLO from the client may be on the way, so the server doesn't know about that. In that cases the server would start a handshake.

As now, [we store defer application data send when there is an ongoing handshake](https://github.com/eclipse/californium/blob/2.0.0-M17/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1930), I guess this should not happened so often with the 2.0.0-M17 :thinking:

**Comment by boaks** [comment]
@joechen2010 

I really appreciated all your contributions over the time to make californium faster (I would guess 30% speed gain on your proposals). Unfortunately we had to redesign too many things, so keeping "all fixes working with all milestones" is just impossible for me. 

The most of your proposals are in the meantime included in the master:
#559 ciphers and macs are all thread local instances and should not longer cause delays.
#681 fixed
#690 the SplitScheduledThreadPoolExecutor implementation is close to your proposal

I guess, you have some additional extra "extensions" or "private fixes" for 2.0.0-M9, and therefore updating since the 2.0.0-M9 would have caused a lot of work. Some others have also some extensions and usually, if we can agree on an interface, it's not big thing to have such extension easier merged with newer versions. If you plan to update to 2.0.0-M17, consider to contribute/request APIs, which allows you to add your own stuff easier.

**Comment by boaks** [comment]
@joechen2010 

could you migrate to the 2.0.0-M17? Any issues we should consider?
Do you have any further question on this? 
If not, please close this issue
