### ISSUE TITLE
DTLS Handshake Key expiration Time Check

### ISSUE THREAD

**Issue by jsinghuy** [eclipse/californium#1071]
I have implemented DTLS PSK based security using Scandium library. I have used PSK keys from third party. These PSK keys may be expired or not at the of handshaking. So, I want to check in my implementation that PSK key(sent by client)  is expired or not at the time of handshaking. Any way to check PSK is expired or not in Scandium library at the time of handshaking.How will terminate handshaking for expired PSK keys.

**Comment by boaks** [comment]
Though your server implementation is intended to provided a implemenation of
[PskStore](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/pskstore/PskStore.java#L74), which fit's your requirements. The ` getKey`will be called ruding handshake, and, if your PSK entry is expired, your server-side implementation should not return that expire key.

> PSK key(sent by client) is expired 

I'm not sure, if you're asking, how you can determine this only based on that "PSK key(sent by client)". simply you can't, because the key isn't sent neither by the client nor the server.

[RFC4279](https://tools.ietf.org/html/rfc4279) 

The peers exchanges the "identity" but the "secret" is kept secret. These secrets must be exchanged ahead, therefore the name "preshared secret key".

**Comment by boaks** [comment]
Was the answer helpful? May I close the issue?
