### ISSUE TITLE
2.0.0-M18 (RC1 hopefully)

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1091]
I would like to release 2.0.0-M18 this week on Thursday 10.10.2019

No (interoperability-) issues are reported for the security update of 2.0.0-M17, so I hope this is the RC1!

Currently two trouble hot spots are reported:
- using container technique may cause strange side effects (second handshake blocked). 
- using long term tests seems to show large message drops.

Both are retested but could not be reproduced. We will see, if the cause could be found.

If you feel, that using 2.0.0-M17 or the new M18 behaves strange, let us know. Even if we can't reproduce it (maybe because it's caused by some special effects in your environment), other user may help.

**Comment by sbernard31** [comment]
> No (interoperability-) issues are reported for the security update of 2.0.0-M17, so I hope this is the RC1!

We didn't test it and even if I consider changes done as really good one. I should admit that I have some concern about how our devices will react with this(they don't like change so mush, even when change is for the better ...). I would let you know but for know I can not give any feedback about that :/

On our side we also face some strange behavior in production where server seems to not answer anymore. This happens extremely rarely and not just with the last version. I never reported this because I haven't any input to give you about that :/ and I'm not even this is a Californium issue (Maybe just a Leshan or proprietary code ...)

**Comment by boaks** [comment]
I guess, the most other also haven't the time to test it.
Anyway, I would prefer to have the M18 released for 1-2 weeks and start the release process. I don't see, that this feedback will change in the next weeks. And even a release could be bugfixed :-).

**Comment by boaks** [comment]
The build is available at [repo - eclipse](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/).

Maven central seems to have issues when deploying artefacts since a couple of days.
I will report it, when maven central deployment works again.

**Comment by boaks** [comment]
Now it's also deployed to maven central.

**Comment by boaks** [comment]
Currently reported issues of 2.0.0-M18:

#1099  (fixed PR #1100)
#1101  (fixed PR #1102)
#1103  (will be fixed PR #1105)

**Comment by boaks** [comment]
2.0.0-RC1 is released.
