### ISSUE TITLE
Whether all the code needs to meet this two licenses？

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#1098]
Whether all the code needs to meet this two licenses？ Eclipse Public License and Eclipse Distribution License.

**Comment by sbernard31** [comment]
I'm not sure I get the question, but all californium code should be dual licensed.
We are reusing (or embedded) some third party libraries and as far as I know those libraries have their own open source licenses and should be approved by the eclipse foundation.

**Comment by boaks** [comment]
Just to mention:
In the meantime, the eclipse foundation requires the licenses EDL/EPL 2.0 for new releases. So we will change that in the next days/weeks. The "new" license versions clarify more/some details and is therefore required for our upcoming 2.0.0 release.

**Comment by sophokles73** [comment]
The Eclipse Foundation maintains [an FAQ page](https://www.eclipse.org/legal/epl-2.0/faq.php) regarding the EPL and upgrading to EPL 2.0.

**Comment by boaks** [comment]
So, does this answer your question?

> Whether all the code needs to meet this two licenses？

If code is intended to be part of this project, yes, it must meet these licenses in order to grant all users these rights to distribute or use it. If this library is used within an other project, and/or distributed with that, these licenses defines, how to do that.

**Comment by xuzhiweiand** [comment]
OK，Thanks
