### ISSUE TITLE
HP Fortify issues

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/californium#112]
Hi Kai,

Apart from issues fixed in the PR https://github.com/eclipse/californium/pull/111.
I have attached the list of all the other issues reported by HP fortify on latest master code(californium-core & element-connector).

[Californium_SCA_Fortify_Security_Report.pdf](https://github.com/eclipse/californium/files/543416/Californium_SCA_Fortify_Security_Report.pdf)

Please provide your input on the issues reported. 

Thanks,
Rajesh Kumar.

**Comment by Rajsmit** [comment]
Hi @sophokles73 , Could you please let us know if you have analyzed the issues and some issue needs to be fixed.

Thanks,
Rajesh Kumar.

**Comment by sophokles73** [comment]
Sorry, @Rajsmit, I have been at EclipseCon this week and didn't find the time yet to go throught the list. Will do during next week ...

**Comment by sophokles73** [comment]
It seems that your report only contains the issues considered *low* priority by HP Fortify. Having scanned over them I did not find anything that overly concerns me. Most of what is reported should probably be addressed at some time but I do not consider anything of it pressing or urgent. 

I would therefore be more interested in the *high* priority issues that Fortify found. Can you provide those as well?

**Comment by Rajsmit** [comment]
Hi @sophokles73 ,

We have Following High issue that are also part of the attached report.

Often Misused: Authentication 12
Log Forging 3
Insecure Randomness 2
Unreleased Resource: Streams 2
Code Correctness: Double-Checked Locking 1

Thanks,
Rajesh Kumar.

**Comment by sophokles73** [comment]
Ok, I have taken a look:

* Often Misused: Authentication - I do not see an issue here because the untrustworthiness of DNS has already been considered in the design of CoAP and DTLS
* Log Forging - this is an interesting problem that I hadn't given much thought in the past. I have created issue #122 for this
* Insecure Randomness - already addressed in bd0253a4488c2c6380ad7ab79ad8d9b1eab2d92b
* Unreleased Resource - have created issue #123 for this
* Code Correctness - I am not sure whether the code actually has this problem or whether this is a *false alarm*.

Thanks again for creating and sharing the report :-) May I ask what your intentions with Californium are? Are you simply evaluating it or are you considering using it in a project/product?

**Comment by Rajsmit** [comment]
Hi @sophokles73 ,

Yes we are planning to use californium in our Project. May i ask if you have any issues with it?

Thanks,
Rajesh Kumar.

**Comment by sophokles73** [comment]
Well, in our IoT scenarios we often have devices on mobile networks or behind NAT firewalls. In such scenarios, it is hard to e.g. maintain observations on devices when the device's IP address or port changes due to a NAT timeout (which often happens after about 20  - 30 secs without traffic in the UDP case).
