### ISSUE TITLE
Exchange dosen't include the request payload of a GET method

### ISSUE THREAD

**Issue by navoda** [eclipse/californium#115]
A CoAP client sends a **GET request** with a payload in it, but the server always receives the payload as a **null** value. The same thing happens for a **DELETE** method but works for **POST** and **PUT.**

Even the **GET** and **DELETE** request methods are not defined to have a payload, for _HEADER_ information  (as CoAP messages don't have headers) and security purposes, it is required to have a request payload for those methods. 

Can you fix this, if there are any restrictions for request payloads for the following methods.

**Comment by sophokles73** [comment]
The GET method is used to *retrieve* a resource's current representation whereas the DELETE method is used to remove a resource. No method payload is defined for both of these methods, simply because there is no need for them to support it. If you need to convey additional information to the server then you need to either use a POST/PUT or include the information in CoAP *Options* (similar to HTTP *headers*).

However, I would be interested to know what kind of information you are trying to convey.

**Comment by navoda** [comment]
as an example: 
I'm trying to connect to a http server using a coap interface. To access the http server and recieve the information, particular oAuth parameters must be set in the http Header info which is initially should come from the CoAP client. 

`CoAP Client` --_**[coap GET request with oAuth param]**_----> `CoAP Server` -----_[http GET request +Header set with oAuth]_----->` HTTP Server`

The problem creates with the **coap GET request with oAuth param**. Since coap cannot use a _Header_, how can I transfer this information with restricted payload? 

I can use a POST instead of a GET. I think it is not a good solution for the matter. 
But I haven't tried the _CoAP options_ at the moment.

**Comment by sophokles73** [comment]
I see. AFAIK there is no *official* binding of OAuth to CoAP (yet). You may want to take a look at [Authentication and Authorization for Constrained Environments (ACE)](https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-04), though ...
