### ISSUE TITLE
2.1.0 - Released!

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1228]
The Californium 2.1.0 Release is out!
It's available at the [Eclipse Repo](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/).
It's already deployed to maven central and will be soon available also there!

**Comment by sbernard31** [comment]
@boaks Do you have an approximate date for the 2.2.0 release ?

**Comment by boaks** [comment]
No. Do you have a preference?

**Comment by sbernard31** [comment]
We plan a release of Leshan [1.0.0 for mid april](https://projects.eclipse.org/projects/iot.leshan/releases/1.0.0).

I plan to release a `RC1` around 2 or 3 week before. I just asking to have an idea if I will release with Cf 2.1 or 2.2.

**Comment by boaks** [comment]
I hope, I can finish my work for PR #1232 and #1238 until Monday and include them in 2.2.0. So, from my side, I think, next Thursday maybe a good date.

For #1240 it's up to you, if you want to have it included, and so when we should release the 2.2.0.

**Comment by sbernard31** [comment]
That's sounds good to me.

About #1240, for now it's not so clear to me what should the good direction :confused: (if we don't have it for the 2.2 it's ok)

**Comment by sbernard31** [comment]
I think we can exclude #1240 to the 2.2 :)

**Comment by boaks** [comment]
I created  a 2.2.0 Release in the Californium project. I get the message, that it should be announced at least for one week. Would schedule the 2.2.0 for 25.03. be OK for Leshan 1.0.0 ?

**Comment by sbernard31** [comment]
>  I get the message

You mean in the eclipse ui => https://projects.eclipse.org/projects/iot.californium/ ?

I plan to release the leshan RC1 this week, I would prefer to get the 2.2.0 in it. 
It would be too bad if this is impossible just because of that. :sob: 
Personally, I would release Californium now and eventually only announce it for the 25.03.

If you disagree, I will release a RC1 without it anyway and I release a RC2 later.

Just let me know :-)

**Comment by boaks** [comment]
So just go for 2.2.0 this week, 19.03. 
We will see, if someone complains :-).
