### ISSUE TITLE
OSCORE  questions

### ISSUE THREAD

**Issue by eliot4321** [eclipse/californium#1250]
Hi,

We  have some questions about OSCORE implementation:

1.  what does mean the "isprotected" attribute in the OSCOREResource. java?
2.  what does  mean the "protected"  and "unprotected" attributes in the Attribute.java in the cose package?  and how  you map it to the class U, class I, class E options in this RFC described in section 4.
 https://tools.ietf.org/html/rfc8613. 

Thanks in advance.

**Comment by boaks** [comment]
@rikard-sics 

Maybe you can answer this question?

**Comment by rikard-sics** [comment]
Hello.

I have been working as the main implementer adding functionality for OSCORE in Californium. To answer your questions.

> 1. what does mean the "isprotected" attribute in the OSCOREResource. java?

The intention is to have a way to enforce that such as resource must be accessed using OSCORE. So a normal CoAP request to such a resource (that has isProtected set to true) should be rejected.

> 2\. what does  mean the "protected"  and "unprotected" attributes in the Attribute.java in the cose package?  and how  you map it to the class U, class I, class E options in this RFC described in section 4.
>     https://tools.ietf.org/html/rfc8613.

The "protected" and "unprotected" attributes in Attribute.java from COSE has to do with the structure of a COSE object. See the following sections and further in the document:
https://tools.ietf.org/html/rfc8152#section-2
https://tools.ietf.org/html/rfc8152#section-3
It does not have a direct relation with the "isProtected" in terms of a CoAP resource.

To understand how the COSE object relates to the CoAP message and its options see:
https://tools.ietf.org/html/rfc8613#section-5
https://tools.ietf.org/html/rfc8613#section-5.3
Note that when building the COSE object (a COSE_Encrypt0 object) in OSCORE the "protected" field is left empty. So the terms "unprotected" and "protected" in COSE does not have a direct relation to class U, class I and class E CoAP options.

Feel free to ask if you want me to elaborate on some point.

**Comment by eliot4321** [comment]
Hi,

Thanks a lot @boaks  for the referral, and thanks  @rikard-sics for your explanations.
Actually I still have some questions,  where I can find the  classes I/U/E options to define?  and if they are not implemented yet are they within your roadmap?

Thanks in advance.

**Comment by rikard-sics** [comment]
> Thanks a lot @boaks for the referral, and thanks @rikard-sics for your explanations.

No problem, glad you are interested in OSCORE.

> Actually I still have some questions, where I can find the classes I/U/E options to define? and if they are not implemented yet are they within your roadmap?
> 
> Thanks in advance.

This is implemented, most of the logic regarding the processing of the CoAP options can be found in OptionJuggle.java:
https://github.com/eclipse/californium/blob/master/cf-oscore/src/main/java/org/eclipse/californium/oscore/OptionJuggle.java

You can see the exact class for each option here:
https://tools.ietf.org/html/rfc8613#section-4.1.1

**Comment by eliot4321** [comment]
@rikard-sics  Thanks again for the clarification.

May I ask which option is used by default in normal OSCORE running?  for example the code of HelloWorlClient.java used as an example to test the OSCORE behavior?

**Comment by rikard-sics** [comment]
> May I ask which option is used by default in normal OSCORE running?

It really depends on what options are set in the CoAP message that OSCORE-protection is applied on. (Of course OSCORE always has the OSCORE option.)

For instance in the HelloWorldClient you have the following options in the request:
Uri-Host: "localhost"
Uri-Path: "hello"
Uri-Path: "1"
OSCORE: 0x0900

Note that OSCORE will fill the OSCORE-option automatically, it just needs to be added as an empty option to the outgoing request. And in the OSCORE-protected request some of the options will be encrypted (depending on their class).

When sending a request in Californium it will also fill some options automatically, without having to explicitly set them (like Uri-Host and Uri-Path since the destination URI is set on the CoapClient).

> for example the code of HelloWorlClient.java used as an example to test the OSCORE behavior?

Yes, it shows first performing a request using only CoAP to an OSCORE-protected resource resulting in a Unauthorized 4.01 response.

Then it shows performing a request protected with OSCORE (using the correct security material) that succeeds with Content 2.05 with the response payload "Hello World!".
