### ISSUE TITLE
Slow DTLS handshake in case of packet loss

### ISSUE THREAD

**Issue by nojz** [eclipse/californium#1267]
@boaks pointed me here from https://stackoverflow.com/questions/60925692/slow-dtls-handshake-in-case-of-packet-loss

I have attached the Wireshark capture file.
[slow-dtls-handshake.pcapng.zip](https://github.com/eclipse/californium/files/4402427/slow-dtls-handshake.pcapng.zip)

**Comment by boaks** [comment]
Thanks, I answered in stackoverflow!

**Comment by boaks** [comment]
I saw someone else has already provided the right answer in stackoverflow. So follow that.

**Comment by nojz** [comment]
The problem is that I don't know which is a right value to set. And did you read the comment I gave on that answer? According to the RFC I think it should answer every retransmitted Client Hello. I don't want to trigger the server side timer if not needed.

**Comment by boaks** [comment]
I read your comment.  Generally implementations consider some more/other aspects than RFC 6347. Californium's DTLS implementation will filter out the retransmission and retransmit the server flight first after 2s (default). So californium will be even slower. We assume in many times very slow networks (especially for the first message).

Fast replies may have in general also downsides, especially, if your handshake is without "hello verify request", as in your case. The server maybe get misused as "amplifier" to DDoS an other peer. Someone may spoof a "client hello" with the victims address as source (that's called spoofing. It's not that easy ...) and though the server answers with its first flight, that will be more data then sending it directly. If your server is under misuse, that will also affect your times negative. 
To throttle that and get a unattractive target of being misused, large timer interval helps. Depending on your network conditions, these drop may occur not too often (e.g. 3-5%). So overall, this should be not a too big issue. 

Otherwise, if you sure, that your server can not be misused, you may use faster times. Therefore I would go to determine the RTT for about 95% of your traffic (time between one peer sends something and then receives an answer, the percent value is the value  of the drop rate of your network conditions). If that timing results in too many retransmission, then try adding 10% until you found your speed vs. retransmission trade off.
