### ISSUE TITLE
2.x.y - PskStore - ambiguous javadoc and example implementation

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1303]
[PskStore.getKey](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/pskstore/PskStore.java#L81) and
[PskStore.getIdentity](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/pskstore/PskStore.java#L118) mention both, that if the `serverName` is `null`, a `NullPointerException is thrown.
But the example implementation just call the none servername-specific variant. So:

- should the javadoc be adapted?
- or should the code throw that exception?

**Comment by sbernard31** [comment]
For `PskStore.getIdentity`, the javadoc doesn't  seem consistent on its own.
```java
/**
 * ...... ....  
 * @param virtualHost The virtual host at the peer to connect to. If
 *            {@code null}, the identity will be looked up in the
 *            <em>global</em> scope, yielding the same result as
 *            {@link #getIdentity(InetSocketAddress)}.
```
and 
```java
/**
 * ... ... .. 
 * @throws NullPointerException if address or host are {@code null}.
```

I look at the Leshan implementations and they do not raise `NullPointerException` too. (doing something like calling the none servername-specific variant too or raising `UnsupportedOperationException` as we don't really support SNI)

:thinking:  I suppose the most backward compatible choice should be to : 
1. relax the javadoc by saying that null is allowed. (maybe saying what is the expected behavior in this case
2. be sure that the californium code don't call those method with null parameter ?

This way :
 - if someone's implementation raises an exception this should not be triggered by californium (still compatible)
 - if someone call californium implementation with `null` this will still work.

**Comment by boaks** [comment]
`PskStore` is removed for 3.0.
