### ISSUE TITLE
Can we use JDK trust store for DTLSConnector?

### ISSUE THREAD

**Issue by sverhagen** [eclipse/californium#1409]
Using version 2.3 of Californium. Thank you for this library.

I have a question. I may very well have my wires crossed here, but my understanding is that when creating a `DTLSConnector` based on a `DtlsConnectorConfig` that I am starting with an empty trust store. Let's say I'm setting up my client, then the certificate management in my organization may provision this client with the appropriate parent certificates so that I can talk to my server. But what if the server is using a publicly-signed certificate from, for instance, Let's Encrypt? The JVM ([for modern versions](https://blogs.oracle.com/jtc/openjdk-10-now-includes-root-ca-certificates)) comes with a trust store with root certificates that are compatible with Let's Encrypt; is there a reasonable way to tell Californium to trust servers based on that?

If so, how about hostname verification?

Thank you!

**Comment by boaks** [comment]
PR #602 introduced a feature to customize that check.

(I personally would have preferred to use the java TrustManager API, but the author of the extension chose a different approach.)

See [AdvancedCertificateVerifier](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/AdvancedCertificateVerifier.java) to add your checks.

> But what if the server is using a publicly-signed certificate from, for instance, Let's Encrypt? 

I'm not sure, what you point to. Using the trust store shipped with java?

> If so, how about hostname verification?

FMPOV, that makes mainly sense on the client side and may be added in the implementation of the `AdvancedCertificateVerifier`.

**Comment by sverhagen** [comment]
*Thank you* for the quick response. I had noticed [that PR](#602), and I'm actually using a `StaticCertificateVerifier` on the server already. It holds two or three certificates, easy. When I accidentally loaded a lot of certificates into my server's certificate verifier, communications broke down due to message fragmentation (during the handshake). I imagine that a custom `AdvancedCertificateVerifier` would allow more customization than `StaticCertificateVerifier`, but if I wanted to accept all publicly-trusted certificates, would I not end up with an implementation of `CertificateVerifier.getAcceptedIssuers` that returns all the certificates known to the JVM, i.e. too many (some 129 of them)? Or does it not matter for the client-side (I don't understand the handshake well enough to understand why all certificates or references to certificates had to be sent down from my server to the client, during the handhake, which then broke as mentioned above.)

**Comment by boaks** [comment]
[TLS 1.2 - RFC5246](https://tools.ietf.org/html/rfc5246#section-7.4.4)

If you send trusted issuers, the client chose them to select a proper client certificate.
If you send a large list of trusted issuer, you send a lot of data.
If you send a empty list, it's up to your client to chose a proper client certificate on its own.
(Just overwrite the `X509Certificate[] getAcceptedIssuers()` returning an empty array).

Let me add:
In my opinion, x509 is simple NO CHOICE for common IoT deployments! You pay a lot and gain nothing.
Usually the clients platforms (e.g. OS or application as browser) are maintained by others and you get your updates of the current x509 states. But, if you're the responsible for the client's OS or application, it's up to you to maintain these certificates proper. That cause either frequent updates, or you weaken that x509 system.
In too many cases the devices will required to be registered at a server anyway, so there is no reason to use the x509 indirect trust for IoT usage.

**Comment by boaks** [comment]
I prefer therefor RPK (hopefully with EdDSA in the java 15 future and also hopefully with new secure hw supporting also Ed25519, until that ECDSA RPK with HW on the device). For a scaling server, a cheap server-side HW solution may for now not scale enough, but also for now the most deployments have not the millions of devices.

**Comment by boaks** [comment]
[RFC5246 -  Message flow for a full handshake](https://tools.ietf.org/html/rfc5246#page-36)

```
 Client                                               Server

      ClientHello                  -------->
                                                      ServerHello
                                                     Certificate*
                                               ServerKeyExchange*
                                              CertificateRequest*
                                   <--------      ServerHelloDone
      Certificate*
      ClientKeyExchange
      CertificateVerify*
      [ChangeCipherSpec]
      Finished                     -------->
                                               [ChangeCipherSpec]
                                   <--------             Finished
      Application Data             <------->     Application Data

             Figure 1.  Message flow for a full handshake
```

There are two main cases:
1. server is authenticated using a certificate - client is anonymous and authenticated by something else. That's the most common case, e.g. using https: and then enter your login and password in a login page.
1. server and client are authenticated using a certificates. That's the case for server-server communication.

For anonymous clients the server only sends the certificate, but no certificate-request (that would contain the issuers list). To achieve that with Californium, set both `setClientAuthenticationWanted` and `setClientAuthenticationRequired` in `DtlsConnectorConfig` to false. Please read also the javadoc there [DtlsConnectorConfig.setClientAuthenticationWanted](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1798).

For mixed case, where some clients use a certificate, some not, `setClientAuthenticationWanted` must be set to true. With that, the server sends the certificate and the certificate-request. In order to use a small certificate-request, you may select the most important trusted issuers. [SslContextUtil.loadTrustedCertificates](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/SslContextUtil.java#L369) offers therefore a `aliasPattern`. It will also be not to hard, to filter it in your own code, if a alias pattern doesn't work good enough.

The client may use a large set of trusted issuers to verify the server's certificate. The client doesn't sent these trusted issuers back, the server has already sent his certificate and so there is no need at that time to select a certificate. 

Currently scandium only support one certificate and doesn't support to select one out of a set.

**Comment by boaks** [comment]
Does my latest comment answer your question?

**Comment by sverhagen** [comment]
I will definitely circle back. We've had a few days off (including Labor Day) but I plan on discussing this with my peers on Tuesday. Thanks for the extensive information already!

**Comment by boaks** [comment]
You're welcome.

**Comment by sverhagen** [comment]
We successfully tried this for our client (Kotlin):

```kotlin
val trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
trustManagerFactory.init(null as KeyStore?)
val systemCerts = arrayListOf<Certificate>()
for (cert in trustManagerFactory.trustManagers) {
    for (issuer in (cert as X509TrustManager).acceptedIssuers) {
        systemCerts.add(issuer)
    }
}
dtlsConfig.setTrustStore(systemCerts.toTypedArray())
```

This uses `StaticCertificateVerifier` under the covers (as you know) which returns all the given certificates through `getAcceptedIssuers`.

>(Just overwrite the X509Certificate[] getAcceptedIssuers() returning an empty array).

This may thus not be needed. I realize you were saying this in the context of the server, whereas I am looking at the client now. Subsequently:

>The client may use a large set of trusted issuers to verify the server's certificate. The client doesn't sent these trusted issuers back, the server has already sent his certificate and so there is no need at that time to select a certificate.

Thank you for confirming this. I believe it is the exact reason why loading all the certificates from the runtime does not lead to message fragmentation (in the same way as when I mistakenly loaded 129 certificates on the server).

>In my opinion, x509 is simple NO CHOICE for common IoT deployments!

We debated this at length over here. And, well, here we are now (which is: committed to certificates).

Thank you for your help!

**Comment by boaks** [comment]
Just in the case you're allowed to publish such information:

- which is the intended domain (e.g. IoT, Smartphone, Smart Home Controller)
- which criteria did you use to make that decision?
- what was your evaluation matrix (e.g. criteria with scores and weight for different analyzed alternatives, e.g. PSK, RPK, JWT, x509) 

Especially for smartphones I agree, that it makes sense. For smart home controller it may make sense, for IoT I have my doubts.

**Comment by sverhagen** [comment]
I can't say much about my project, unfortunately. But my employer is Verizon (this is public knowledge). What we're trying to get "flying" here doesn't fit the typical IoT profile very well, certainly a step up from there in terms of wanting to secure the payload.

**Comment by boaks** [comment]
> certainly a step up from there in terms of wanting to secure the payload.

The "secure payload" is one of the "over-stressed" terms at all :-).

Just as forecast:
- a naive approach to select the "payload" requires to define, what the protected payload and the unprotected message-frame should be. 
- it requires a definition of the security-context and session, even if the idea is to decline that (that results in a everlasting session with off-band exchanged secrets. Or to use asymmetric encryption for much more then just exchange the session keys).
- security comes with more than just naive encryption. It comes with stuff, like "salt" to prevent to detect, that the encrypted data is the same as in other messages. It comes with "replay protection", in order to protect the receiver from reading the same twice. That also points to a general topic: it's not only about exchange payload, it's frequently also about the request-context or/and the time point.    

For the payload definition:
- as the protocols seem to build a stack, the protocol frame of the one may be considered as the payload of the other. There is nothing wrong to say: DTLS is payload encryption for UDP, it encrypts the payload for UDP. That example also demonstrates, that extending the "naive payload encryption definition" too often use additional "artifacts" for that encryption (in that case the UDP source address and port to identify the security context).
- There is a RFC considered as "payload encryption for CoAP", [RFC8613 - Object Security for Constrained RESTful Environments (OSCORE)](https://datatracker.ietf.org/doc/rfc8613/). That also couples CoAP "artifacts" to the "payload" encryption. Therefore, it's not encrypted payload, what is forwarded as response, it's the plain. The [RI.SE](https://www.ri.se/en) spent an implementation of that RFC to Californium, see issue #516 . It's contained in the module `cf-oscore`.
