### ISSUE TITLE
Cannot send message to /180.167.227.226:7773, all MIDs are in use

### ISSUE THREAD

**Issue by superJack2222** [eclipse/californium#1520]
helllo,when i  send a message,the lwm2m server appear this warn ,and my device can not receice any message ,my device number about 30000 ,but i am sure my MAX_ACTIVE_PEERS=150000 ,Why report this error but this value is not reached.

**Comment by boaks** [comment]
Which Leshan version are you using? Or, which Californium version?

Do you have logs? Can you provide them? Or, does this warning appear, when sending request or responses (on the lwm2m server side)?

How many messages are sent from the lwm2m server to each device? Does this comply to [NSTART-1](https://tools.ietf.org/html/rfc7252#section-4.7)?

**Comment by boaks** [comment]
I'm wondering, you write:

> my device number about 30000 

Do theses lwm2m devices share the same coap-endpoint? Because you also title "/180.167.227.226:7773", which seems to be an single endpoint?

Do you use the leshan-client? Or did you implement a own?

Just to mention: using 30000 CoapClient all using the shared default coap-endpoint is not intended!

**Comment by superJack2222** [comment]
I use the real device,not leshan-client .

**Comment by superJack2222** [comment]
my californium version is  <californium-core>2.0.0-M5</californium-core>, this logs are 
![1611713031(1)](https://user-images.githubusercontent.com/19429672/105931906-03785000-6087-11eb-8748-a35b9ec80c99.jpg)

**Comment by superJack2222** [comment]
[](url)![mark](http://cloud.anttechnologys.cn/imgs/20210127/hCrXBO9D4XmN.jpg?imageslim)

**Comment by boaks** [comment]
Thanks for the screenshots.

AFAIK, the leshan-server is using the `NullMessageIdTracker` by default and so this error should only be caused by exhausting the `tracker` table. The `MAX_ACTIVE_PEERS=150000` limits the inet-socket-address endpoints and uses a timeout for such entries of 10 min. How often do the devices register/update_register to the server? Do they change their address? Maybe you try out a larger value than `150000`.

What makes me wondering is, that your `mid` in the screenshots are out of the range of CoAP MIDs (see [RFC 7252, 3. Message Format](https://tools.ietf.org/html/rfc7252#section-3), "Message ID:  16-bit unsigned integer in network byte order."). I'm not sure, if that `mid`s in the screenshots are related to the CoAP MIDs.

**Comment by superJack2222** [comment]
my device not change their mid 。

**Comment by superJack2222** [comment]
And how to resolve this problem.

**Comment by boaks** [comment]
I think, that mid is not the CoAP message ID. Otherwise, your devices will just not be CoAP / RFC 7252 compliant.
The screenshots show also, that the CoAP MID is different. I would check the configure value of `MAX_PEER_INACTIVITY_PERIOD`. And try to find out, how often the devices register/update and, if they change their ip-address/port.

**Comment by superJack2222** [comment]
![image](https://user-images.githubusercontent.com/19429672/105961199-26235c80-60b9-11eb-8c94-2d392cdbe383.png)

**Comment by superJack2222** [comment]
![mark](http://cloud.anttechnologys.cn/imgs/20210127/J9Xtnvc8W52N.jpg?imageslim)

**Comment by superJack2222** [comment]
the device is real device, and I understand that devices are not registered very often，aboute 24 hours once

**Comment by boaks** [comment]
I don't understand, what's going on in your leshan-server ;-).

The error "all MIDs are in use" has two causes:
- the tracker-table in `InMemoryMessageIdProvider` is full
- the MIDs of the `MessageIdTracker` are exhausted (there is a range [0...65000) and a lifetime `EXCHANGE_LIFETIME`). But `NULL` is used, so only the other cause is valid.

I would give a larger `MAX_ACTIVE_PEERS` a chance.

Do you have the chance to add logging messages into the Californium you use? (Means, can you use a Californium SNAPSHOT?)

**Comment by superJack2222** [comment]
No, I restarted the server after this problem occurred. In order for the customer to use, but every once in a while the same problem occurs.

**Comment by boaks** [comment]
Sorry, I was mislead. you don't use leshan, or?

Is there a reason to use Californium version 2.0.0-M5? 
That's from Sep 2017. Since that, a lot of errors have been fixed. Our current release is 2.6.0.
Migrating from the 2.0.0-M5 is not too easy, but it's really worth.

If you looking for "hotfix", maybe you try to grab the current `LeastRecentlyUsedCache` implementation and try out that. I'm not sure, if that has an chance to work, but maybe.

**Comment by superJack2222** [comment]
My clients are using real devices, real customers are using real hardware

**Comment by boaks** [comment]
Sure, Californium and Leshan are frequently used on the server-side. 
Therefore,  I was mislead, assuming you're using leshan for the server side.
 
Anyway, I guess you need to try out to either migrate to the current 2.6.0 release, or to try a "hotfix" as described above on your own.

**Comment by superJack2222** [comment]
All right. I'm going to evaluate this.

**Comment by boaks** [comment]
I also try to "hotfix" the 2.0.0-M5.
I will only be able to apply the available unit-test of that 2.0.0-M5. I don't know, if that solves your problem, it's just a guess.
I will push the changes, when I'm finished.

**Comment by boaks** [comment]
I pushed the hotfix to branch "2.0.0-M5-hotfix".

> NOT INTENDED TO BE USED GENERALLY!
> 
> Assumption: the tracked peers in InMemoryMessageIdProvider.trackers are
> not removed on timeout.
> 
> Therefore use the 3.0 LeastRecentlyUsedCache.
> Requires to add the ClockUtil and adapt InMemoryConnectionStore.
> Update also SslContextUtil to use explicit TLSv1.2 in order to support
> build with newer jdks.
> Recreates the certificates for build.

**Comment by boaks** [comment]
Just to mention:

I hope the hotfix solves the issue, but I'm not sure about that.
I still recommend to migrate at least for mid-term to 2.6.0.

**Comment by superJack2222** [comment]
Ok thank you very much

**Comment by superJack2222** [comment]
I will try it.

**Comment by superJack2222** [comment]
I have another question. What causes this.

**Comment by superJack2222** [comment]
![mark](http://cloud.anttechnologys.cn/imgs/20210129/deeIAdvjwF8o.jpg?imageslim)

**Comment by superJack2222** [comment]
![mark](http://cloud.anttechnologys.cn/imgs/20210129/8lqz7Eh0hI63.jpg?imageslim)

**Comment by boaks** [comment]
Just to mention: pictures are harder to read and "textual copies of the logs".

The 1. screenshot seems to show a next 2.0.0-M5 bug. As I already wrote, since 2017 many many bugs have been fixed. I'm pretty sure, you will find more in 2.0.0-M5. Therefore the recommendation to migrate to 2.6.0.

The 2. screenshot shows a bug in the block-option encoding. That encoding is defined in [RFC7959, 2.2.  Structure of a Block Option](https://tools.ietf.org/html/rfc7959#section-2.2), it has at most 3 bytes. Though the stacktrace contains "parsing", the malformed option is received. So, the device sends malformed requests. At least not RFC7959 conform requests. 

With the 1. (there are sure more bugs in 2.0.0-M5) I strongly recommend to migrate to 2.6.0, with the 2. (non-conformant devices/buggy devices), that migration must be made with caution. If you have access to such devices, you may test the effect of that migration ahead. (just to mention, it may be faster to use leshan for that check, than to migrate your server to Californium 2.6.0). If that compatibility check succeeds, then the migration helps a lot. If you find issues, it depends on the ability to "fix" the devices.

**Comment by boaks** [comment]
Any update?

**Comment by boaks** [comment]
I hope, the first hotfix helped a little. If you want to migrate to 2.6.1 and get faced any issue, don't hesitate to contact me.
