### ISSUE TITLE
overlapping notifications requiring blockwise transfer are not detected

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#155]
On the 2.0.x branch the `ObservationLayer` is not able to detect an already ongoing blockwise transfer for a notification when a new notification for the same token is received while the blockwise transfer is still in progress. This leads to the following problems:
* we no longer follow NSTART 1 because we run multiple blockwise transfers in parallel
* already running blockwise transfer(s) might mix up *old* with *new* blocks of the (changed) resource.
* since all blockwise transfers are conducted independently from each other, the blockwise layer delivers a separate *assembled* and potentially corrupted `Response` for each of them to the application layer when it should have delivered only one `Response` reflecting the most recent (completely transferred) state of the resource.

On master, this does not happen because an already running blockwise transfer is stopped and replaced with a new (blockwise) transfer for the newly received notification when such an *overlapping* notification is received.

**Comment by boaks** [comment]
> we no longer follow NSTART 1 because we run multiple blockwise transfers in parallel

This question depends on the definition of NSTART. A blockwise transfer could be considered as a sequence of request/reponse pairs and NSTART 1 is only applied for each pair. Then also other "request/response" pairs would be possible, even if the complete blockwise is not completed.
Or the "complete blockwise transfer" is considered to be in NSTART 1, so no other request/response pairs are allowed.
I would prefer the pairwise definition. Otherwise the communication will be blocked for to long.

The NSTART 1 is mostly related to the resource restriction in the communication layer. Therefore blockwise is constructed in a way, where it is possible to handle the blockwise specific stuff outside of the communication layer. So I think NSTART 1 should be interpreted based on a single request/response pair and not the complete "blockwise transfer".

**Comment by sophokles73** [comment]
I agree, but the issue is not whether the whole transfer is considered an exchange or not. The problem is that in the existing implementation there is no check making sure that there are no two exchanges (for a single block or the whole body) with the same endpoint are going on.

**Comment by sbernard31** [comment]
Do we have a test for this bug ? 

The issue could not be fixed just by searching the exchange by URI instead of token in the [matcher](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/UdpMatcher.java#L246) for block2 notification ? 
(I know we will add some specific blockwise behavior in the matcher :/)

**Comment by sophokles73** [comment]
I have been working on this for the last 10 days now. I have created a test case for it and have also re-factored the BlockwiseLayer quite a lot so that it now handles all of this correctly AFAIK. In the course of doing so I completely removed all *special behavior regarding blockwise transfers* from the Matchers as well. 
I will push the branch with the changes later during the day so that you guys can take a look. But beware, I made a lot of changes :-)

**Comment by sbernard31** [comment]
Should we be afraid ? :)

**Comment by sophokles73** [comment]
I am not a big fan of overly large PRs in general. However, in this case I had to make *a lot* of changes to decouple the blockwise transfer handling from the other layers. So, you will probably not really *enjoy* reviewing the code unless you have masochistic tendencies ;-)

**Comment by boaks** [comment]
I’m afraid, that in the intent of having blockwise „transparent“ to the upper layer, forces a MUST/require on ETag.
May be we can add a “callback” for the upper layer to control that, if ETag is missing. But it’s just a rough idea. We may add this on top of Kai’s cleanup.

**Comment by sophokles73** [comment]
@boaks,

I am afraid I do not understand what your point is. Can you give a more concrete example of a situation where your concern comes into play?

**Comment by boaks** [comment]
@sophokles73

An example for a changing blockwise resource without ETag?
Camera with "snap" execute and "picture" resource. 
Though the change is controlled by the client, a ETag may be not required, if a "cancel" of an pending transfer would be possible. For such an case, a callback for an ongoing blockwise read (as follow up of an notifiy), may allow this cancel.

But I'm not sure, why RFC 7959, 2.4, says "SHOULD", and not "MUST".

**Comment by sophokles73** [comment]
Fixed on 2.0.x in 5ef638e341d7b5f6edd48a5ccbfc97a804034a79
