### ISSUE TITLE
Some problems encountered in development using the Californium framework

### ISSUE THREAD

**Issue by wangshengji** [eclipse/californium#1617]
Hello, I am a Chinese programmer and my English is not very good. Please forgive me.
I want to modify the format of tcp data parsing during the development process of using the Californium framework. I have been troubled for a long time. I want to ask you for advice. Now I am using version 2.6.2, but the currently parsed tcp uses https:// tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-03, I want to modify it to https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls -01 TCP protocol header, how should it be done?

**Comment by boaks** [comment]
1. you need to implement your `DataParser` and `DataSerializer`. Hope the current API of these classes works for your requirements.
2. Create your `CoapEndpoint` using `CoapEndpoint.Builder.setDataSerializerAndParser(yourSerializer, yourParser)`.

If you need some modifications in the `DataParser` and `DataSerializer` API in order to implement the adaption, then, please migrate to 3.0.0-M1 (or the current SNAPTSHOT). Either prepare a PR with the required adaptions in `DataParser` and `DataSerializer` or at least a description of the required changes.

(See [CONTRIBUTING](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md) for details).

Good luck.

**Comment by boaks** [comment]
Version -03 (implemented):

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |Len=13 |  TKL  |Extended Length|      Code     | TKL bytes ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |  Options (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |1 1 1 1 1 1 1 1|    Payload (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

          Figure 4: CoAP frame with 8-bit Extended Length field.
```

Version -01:

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |        Message Length         |Ver|0 1|  TKL  |      Code     |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |        Token (TKL bytes) ...  |  Options (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |1 1 1 1 1 1 1 1|    Payload (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

          Figure 5: CoAP Header with prepended Shim Header.
```

That requires also to "patch"/"replace" the [DatagramFramer](https://github.com/eclipse/californium/blob/master/element-connector-tcp-netty/src/main/java/org/eclipse/californium/elements/tcp/netty/DatagramFramer.java). This unfortunately currently not customizable.

Let me know, if you was successful to get it working.
Then I will consider to adapt the tcp-netty module to pass in such a custom `DatagramFramer`.

**Comment by boaks** [comment]
I think, there are two topics about the token:

if you want to send requests, you just may use your own tokens. 

```java
Request get = Request.newGet();
byte[] token = new byte[] { 1, 2, 3 };
get.setToken(token);
...
```

That prepares a request with a 3-bytes token.
If you do that, you provide your own token and so you're responsible for obeying, that each token in use/fly must be unique for the peer's pair (see details [RFC7252, 5.3. Request/Response Matching](https://datatracker.ietf.org/doc/html/rfc7252#section-5.3)). Otherwise the processing of the responses may be mixed up. If Observe/Notifies are used, that requires even more care, because these token are used for longer.

If you want to setup a more sophisticated, but custom, token management, you may implement your own `TokenGenerator`. If you just want to try shorter tokens, you may configure the `TOKEN_SIZE_LIMIT` in your Californium.properties. Change

```
TOKEN_SIZE_LIMIT=8
```

to

```
TOKEN_SIZE_LIMIT=4
```

The other topic is then the encoding/decoding of such tokens. [RFC7252, 3.  Message Format](https://datatracker.ietf.org/doc/html/rfc7252#page-16) specifies that.

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |Ver| T |  TKL  |      Code     |          Message ID           |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |   Token (if any, TKL bytes) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |   Options (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |1 1 1 1 1 1 1 1|    Payload (if any) ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

                         Figure 7: Message Format
```

There are two fields used for the token:

> Token Length (TKL):  4-bit unsigned integer.  Indicates the length of
>       the variable-length Token field (0-8 bytes).  Lengths 9-15 are
>       reserved, MUST NOT be sent, and MUST be processed as a message
>       format error. 
> 
> Token (if any, TKL bytes) 

A token can have a variable length of 0 to 8 bytes. That length is then encoded in the TKL nibble (4 bits).
TKL will be `0b1000` for 8 or `0b0011` for 3 bytes. And the token field itself must have exactly that number bytes.

What is changing with the TCP format is just the position of the TKL field. It's not longer the 1. byte, it's the 3.
I think, that requires only small changes in the `DataParser` and `DataSerializer`.

**Comment by boaks** [comment]
@wangshengji 

Did it work for you? If so, can the issue be closed?

**Comment by wangshengji** [comment]
I'm very sorry, I forgot to close it, thank you for reminding, I can't access this website now, I will close it later. Your answer is very useful to me. Now I am trying to modify the tcp-netty package so that I can customize the Coap protocol.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Achim ***@***.***&gt;; 
发送时间: 2021年5月20日(星期四) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eclipse/californium] Some problems encountered in development using the Californium framework (#1617)





 
@wangshengji
 
Did it work for you? If so, can the issue be closed?
