### ISSUE TITLE
Clarify wanted behavior on restart a connector with port == 0 

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#165]
Analysing UDPConnector, I'm wondering, what the "exact" definition of "restart" with port 0 should be. Should it start on the previous port or could it alos chose a new one? UDPConnector preserves the 0 and would therefore potentially reopen a new port. Is that intended?

**Comment by sbernard31** [comment]
I believe we use this mechanism to be able to simulate a port change in some tests.
I don't know if it's a good reason to keep this behavior.

I suppose if you want a fixed IP, you can set it instead of using 0.
Does it exist a use case where you want to let the system choosing a free port on `start ` then you want to keep it on `restart` ? I don't know :)

**Comment by sophokles73** [comment]
*Restarting* the UdpConnector means to start it again on the same port (if possible) as it has been running before. This implies that you can only meaningfully restart the connector if it had been running before at least once. Otherwise, with a configured port of 0, it will use an ephemeral port.

Does this answer the question?

**Comment by boaks** [comment]
OK, then the UDPConnector may require a "fix". 
`localAddr` stays, and so port == 0 would also be reused on (re-)start.
No big issue, I just want to know, which was the inteded functionality.

**Comment by sophokles73** [comment]
Do you want to create a new issue for the problem and close this issue then?

Otherwise, please explicitly state the behavior here that you consider erroneous so that I can label this issue as a `bug`.

**Comment by boaks** [comment]
After checking DTLSConnector, I'm in doubt.
In DTLSConnector a explizit "restart" method was added with the above described behavior (see @sophokles73).
But execute a stop()/start() cycle would not reuse the assigned port, it would just use the 0 again. So I'm not sure, if we just had a missunderstanding about the term "restart". So, was your desciption above for the explizit restart? Or alos for stop/start?

**Comment by sophokles73** [comment]
For the `restart()` method. Doing a `stop()` followed by a `start()` results in the configured bind to address being used again (which might include an ephemeral port).

**Comment by boaks** [comment]
OK! So UDPConnector is implemented as expected.
