### ISSUE TITLE
Make request/response correlation configurable

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#174]
As I explain [here][1], I think that correlate request/response by session/epoch is really too strong I recommend to just made the correlation by Identity. Having a way to do that in Californium by offering a way to implement your own correlator or by adding a new correlation mode could be a good point.

[1]:https://mailarchive.ietf.org/arch/search/?email_list=core&gbt=1&index=0vwuEnq6IRHJc70l3BTggX6p9vs

**Comment by boaks** [comment]
@sbernard31 

Could you check, if the introduced `CorrelationContextMatcher` solves this issue for you?

**Comment by sbernard31** [comment]
This solves partially the issue. We should now add principal to correlation context.

**Comment by boaks** [comment]
A did some investigation also on my idea in #344 to move the principal and correlation context into 
`org.eclipse.californium.core.coap.Message` to make it possible to pass that information also in.  
Doing so I recognized, that the matcher could not use Message on element-connector, so I withdrawn that and extended the CorrelationContext with the Principal and InetSocketAddress and renamed it to EndpointContext. Together with an cleanup (remove the InetAddress/Port from Message and RawData), this is also a flood of changes, as some other pending stuff or PRs.

So, I think, we should first agree on the order of the work:
- separate TCP
- change logging (I'm not sure, if we should do this at all)
- introduce the "EndpointContext"

**Comment by sbernard31** [comment]
It sounds a good plan.

**Just to complete it :**
- integrate #397
- release 2.0.0M5
- separate TCP
- change logging (I'm not sure, if we should do this at all)
- introduce the "EndpointContext"

**What about this other PR ?**
_#394 multicast request: remove exchange only by timeout_ : should we integrate it before ?
_#367 Bert TCP Support_ : should we integrate it before ?
_#326 Add isEmptyWithDump() for more details in logs while testing_ : we should agree on that before to merge.
_#322 Add endpoint identifier_ : probably throwed out
_#294 Add correlation context and principal to TLS connectors_ : is it part of EndpointContext ?
_#95 Exchange shouldn't be removed if it with a multicast request_ : should we integrate it before ?
_#87 Observationstore improvement_  : the problem is still here but will not be merged soon so we will see later.

**Comment by boaks** [comment]
Uups, I used the "bullets" instead of numbers to leave it open, in which order the work should be done :-).

I agree with the first two.

But then I would prefer to postpone PR #399. Even if it's "mostly moving", this makes it hard to rebase. 
Therefore I asked for additional reasons, why this should be done now. I don't see that issue #119 has a priority, I asked for wishes according of the timeline in the #119 discussion, but there was no current wish. For me it seems to be easier to do the moves later, so I would also take the responsibility to do that moves based on your work in PR #399, if you don't want to spent your time twice (what I fully understand). 

I currently working on that EndpointContext (former CorrelationContext), but there is some work left ...

#394: its for 1.0 so not related to 2.0.x. Multicast in 2.0.x will cause some additional changes ... (even clarification in the RFC about the MIDs). So not required to be merged in order with other stuff for 2.0.x.

#367 no interest from my side. I don't know, why someone create a PR for master after declining that PR exactly for that master and redirect that PR to 2.0.x based "tcp_experimental_features" branch. Though it's for master, it's not required to be merged in order with other stuff for 2.0.x.

#326  logging important information is for me much more important than the logging framework. But though you rather request redesigns instead of "easy include" logging, I just use that PR for temporary debugging. But there is no need to merge that or to postpone any work because that is not merged. I can also close it.

#294 important for include TLS into the californium security. But is related to changes in correlation context, therefore postponed.

#95 we will see, if we could make #394 working. I don't know, if there is still interest in this PR.
anyway, it's for master, and so it's not required to be merged in order with other stuff for 2.0.x.

#87 I didn't spent the time into that, so I simply don't understand the issue nor the PR.  I hope, it's not a "killer" :-)

**Comment by sbernard31** [comment]
Ok so does it means that the plan is more : 

1. integrate #397
2. release 2.0.0M5
3. introduce the "EndpointContext"  +  #294
4. separate TCP
5. change logging

For #326 I will propose some else if you're ok ?

According to your comments other PR are not in this plan :)

**Comment by boaks** [comment]
1 - 4, yes, I think this would be a good plan. 
For 5. I would prefer the feedback from the other committers or "using projects". 
But I see also the positive effects for leshan (and maybe other projects).

For #326, sure, if you want to provide the logging information in a better design, feel free to do so.

**Comment by sbernard31** [comment]
We can close this one too, right ?

**Comment by boaks** [comment]
Yes, it's yours, so close it :-)
