### ISSUE TITLE
OSCORE- Sending two downlink request from same host

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#1748]
Hi,

I tried sending two coap  request from same host(same ip) to coap server.

Second request overridden the first request context in HashMapCtxDB. Only second downlink request worked there after. 

```
public static Request encrypt(OSCoreCtxDB db, Request request) throws OSException {

		String uri = request.getURI();
		OSCoreCtx ctx = db.getContext(uri);

		if (ctx == null) {
			LOGGER.error(ErrorDescriptions.CTX_NULL);
			throw new OSException(ErrorDescriptions.CTX_NULL);
		}

		// Perform context re-derivation procedure if ongoing
		try {
			ctx = ContextRederivation.outgoingRequest(db, ctx);
		} catch (OSException e) {
			LOGGER.error(ErrorDescriptions.CONTEXT_REGENERATION_FAILED);
			throw new OSException(ErrorDescriptions.CONTEXT_REGENERATION_FAILED);
		}

```
```
@Override
	public synchronized OSCoreCtx getContext(String uri) throws OSException {
		if (uri != null) {
			return uriMap.get(normalizeServerUri(uri));
		} else {
			LOGGER.error(ErrorDescriptions.STRING_NULL);
			throw new NullPointerException(ErrorDescriptions.STRING_NULL);
		}
	}
```
Guess port also should be considered in key while storing the context?

**Comment by boaks** [comment]
@rikard-sics 

Any ideas?

**Comment by rikard-sics** [comment]
Hello. Thank you for the feedback.

Just to understand your setup better. Do you have 2 OSCORE contexts shared between the client and server? Are you sending the requests to different ports on the server?

**Comment by madhushreegc** [comment]
Yes, I have two oscore context shared between client and server . 

>  Are you sending the requests to different ports on the server?


No, I am sending request to same port of server , only clients(same ip but different port) are different .

**Comment by rikard-sics** [comment]
> Yes, I have two oscore context shared between client and server .
> No, I am sending request to same port of server , only clients(same ip but different port) are different .

Alright, thanks for the info. Do you have 2 standalone clients, or are they both implemented as a single application? Are you sending the requests to the same resource on the server or to different resources?

**Comment by madhushreegc** [comment]
Yes I have two standalone clients.  Yes accessing same resource on server .

**Comment by rikard-sics** [comment]
> Yes I have two standalone clients. Yes accessing same resource on server .

Thanks for the details on the setup. May I ask how you are adding the OSCORE contexts on the server? Is it using
`HashMapCtxDB addContext(String uri, OSCoreCtx ctx)`
or
`HashMapCtxDB addContext(OSCoreCtx ctx)`

**Comment by madhushreegc** [comment]
I am using  `addContext(String uri, OSCoreCtx ctx) ` .

**Comment by rikard-sics** [comment]
> I am using `addContext(String uri, OSCoreCtx ctx) ` .

I see. And what are you practically using as the uri string? The URI of the client "coap://IP:PORT", or "coap://localhost"?

**Comment by madhushreegc** [comment]
I am setting "coap://127.0.0.1"

**Comment by rikard-sics** [comment]
> I am setting "coap://127.0.0.1"

Could you try instead adding the contexts using?
`HashMapCtxDB addContext(OSCoreCtx ctx)`
If the server will not send out any requests, associating the context with a URI should not be necessary.

Also could you post configuration for the 2 contexts you are using? Specifically the Sender ID, Recipient ID and ID Context.

**Comment by madhushreegc** [comment]
I tired adding only HashMapCtxDB addContext(OSCoreCtx ctx) . I am getting nullpointer exception when trying to send downlink request. 

The coapserver here acts as both client and server for me . 

I am not using idContext .
Context details as below 
Context 1:
byte[] master_secret = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D,
    			0x0E, 0x0F, 0x10 };
byte[] master_salt = { (byte) 0x9e, (byte) 0x7c, (byte) 0xa9, (byte) 0x22, (byte) 0x23,
    			(byte) 0x78, (byte) 0x63, (byte) 0x40 };
 byte[] context_id = { 0x37, (byte) 0xCB, (byte) 0xF3, 0x21, 0x00, 0x17, (byte) 0xA2, (byte) 0xD3 };
 byte[] rid = new byte[] { 0x01};
 byte[] sid = new byte[] { 0x09 };

Context 2:
byte[] master_secret1 = { 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 };
byte[] rid1 = new byte[] { 0x0A};
byte[] sid1 = new byte[] { 0x02 };


Usecase is as below :
Coap server receives a request .(uplink
Coap server now acts as a client and send one downlink request .

**Comment by madhushreegc** [comment]
This is just like LWM2M usecase.

**Comment by rikard-sics** [comment]
> Usecase is as below :
> Coap server receives a request .(uplink
> Coap server now acts as a client and send one downlink request .
> This is just like LWM2M usecase.

Okay, I see. So the server is also sending requests. Then I understand the use case in more detail.

Just for curiosity, how do you make the server find the OSCORE context to the client(s) when you add it using the following?
`addContext("coap://127.0.0.1", ctx)`
It seems to me the string would need to be the IP of the client for the server to find the context. But perhaps you are running the client and server on the same machine so they are all on 127.0.0.1? (As a note, the way this is currently done in the LWM2M Leshan code is that after the client sends the first request to the server (and the server then gets to know the IP of the client), at that point the context is (re-)added on the server associated to the URI (hostname/IP) of the client.)

However, I see your point now that you mentioned initially about ports. For your case you could do something like this on the server:
`addContext("coap://$ClientsCommonIP:$Client1Port", ctx)`
`addContext("coap://$ClientsCommonIP:$Client2Port", ctx)`
So the server can distinguish between the different contexts to the 2 clients. (If the ports of the clients are know ahead of time, otherwise you need a more advanced solution like the one in the Leshan code.)

**Comment by madhushreegc** [comment]
ok . I got the point , I tested adding port also along with ip addContext("coap://$ClientsCommonIP:$Client1Port", ctx) . 

normalizeServerUri is giving only host so getting nullpointerException .

**Comment by rikard-sics** [comment]
> ok . I got the point , I tested adding port also along with ip addContext("coap://$ClientsCommonIP:$Client1Port", ctx) .
> 
> normalizeServerUri is giving only host so getting nullpointerException .

Yes, I understand your use case now, and yeah since both clients are on the same IP but different ports and the server is sending requests to the clients, the port need to be added in the code handling the context retrieval/addition.

I can start looking into this and post the code here when I have something working. Then as a later step I can open a PR about this. Basically it should be about updating the _normalizeServerUri_ method (as you bring up):
https://github.com/eclipse/californium/blob/95f7197750c72d21df1f31b65194671058f1de53/cf-oscore/src/main/java/org/eclipse/californium/oscore/HashMapCtxDB.java#L293

If you want a work-around in the meanwhile it would be to run the clients from different IPs.

**Comment by madhushreegc** [comment]
Thank you so much ..

**Comment by madhushreegc** [comment]
I was thinking one more , for Non-IP devices , ip address will not be there . 

Is it possible to change below method to take coap Request as parameter in addContext(String uri, OSCoreCtx ctx) method in OSCoreCtxDB class .
Uri can be derived from Request . Why is this because non-ip devices will not have unique ip and unique identifier required can be derived from request endpoint context . 

```
public void addContext(String uri, OSCoreCtx ctx) throws OSException {
```

to 

`public void addContext(Request request, OSCoreCtx ctx) throws OSException;
`

Thank you.

**Comment by rikard-sics** [comment]
For the issue with using multiple ports on the clients in your setup, could you try replacing _normalizeServerUri_ here:
https://github.com/eclipse/californium/blob/95f7197750c72d21df1f31b65194671058f1de53/cf-oscore/src/main/java/org/eclipse/californium/oscore/HashMapCtxDB.java#L293

With the following code? That should hopefully solve things for your setup. With this code the port will also be taken into account for context retrieval.

```
	private static String normalizeServerUri(String uri) throws OSException {
		String normalized = null;
		int port = -1;

		try {
			port = (new URI(uri)).getPort();
			normalized = (new URI(uri)).getHost();
		} catch (URISyntaxException e) {
			// workaround for openjdk bug JDK-8199396.
			// some characters are not supported for the ipv6 scope.
			try {
				String patternString = "(%.*)]";
				Pattern pattern = Pattern.compile(patternString);

				//Save the original scope
				Matcher matcher = pattern.matcher(uri);
				String originalScope = null;
				if (matcher.find()) {
					originalScope = matcher.group(1);
				}

				//Remove unsupported characters in scope before getting the host component
				normalized = (new URI(uri.replaceAll("[-._~]", ""))).getHost();

				//Find the modified new scope
				matcher = pattern.matcher(normalized);
				String newScope = null;
				if (matcher.find()) {
					newScope = matcher.group(1);
				}

				//Restore original scope for the IPv6 normalization
				//Otherwise getByName below will fail with "no such interface"
				//Since the scope is no longer matching the interface
				if (newScope != null && originalScope != null) {
					normalized = normalized.replace(newScope, originalScope);
				}

			} catch (URISyntaxException e2) {
				LOGGER.error("Error in the request URI: " + uri + " message: " + e.getMessage());
				throw new OSException(e.getMessage());
			}
		}

		//Further normalization for IPv6 addresses
		//Normalization above can give different results depending on structure of IPv6 address
		InetAddress ipv6Addr = null;
		try {
			ipv6Addr = InetAddress.getByName(normalized);
		} catch (UnknownHostException e) {
			LOGGER.error("Error finding host of request URI: " + uri + " message: " + e.getMessage());
		}
		if (ipv6Addr instanceof Inet6Address) {
			normalized = ipv6Addr.getHostAddress();
		}

		if (port != -1 && port != CoAP.DEFAULT_COAP_PORT) {
			normalized = normalized + ":" + port;
		}

		return normalized;
	}
```

**Comment by rikard-sics** [comment]
> I was thinking one more , for Non-IP devices , ip address will not be there .
> 
> Is it possible to change below method to take coap Request/Response EndpointContext as parameter in addContext(String uri, OSCoreCtx ctx) method in OSCoreCtxDB class .
> Uri can be derived from Request/Response EndpointContext. Why is this because non-ip devices will not have unique ip and unique identifier required can be derived from request/response endpoint context .

Interesting idea. I will start looking into this a bit and see what could be done to help in non-IP cases.

**Comment by boaks** [comment]
Before working on support "non-IP cases", please consider to read [Leshan - Add support of NIDD transport](https://github.com/eclipse/leshan/issues/1046#issuecomment-915984876).

In my opinion, IP-addresses can not be replaced, but other "address schemes" may be mapped into IP-addresses.

The `EndpointContext` is no `EndpointIdentity`, but is used as argument for `EndpointIdentityResolver.getEndpointIdentity(EndpointContext context)`.

With PR #1714, the `Exchange` should return the identity according the configuration in [Exchange.getPeersIdentity()](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/Exchange.java#L732) (that may require to be checked, because OSCORE is something used inside the stack and I didn't check it on my own, if it is already set at that time). That identity is in the most cases the IP-address. If the principal is used, then it must be ensured, that credentials are only used once. For plain CoAP, it mainly the IP-Address.

For future transport implementations that may also be adapted to other "identities" in order to replace the IP-address more and more. But it will take a lot of time, until the IP-address could be really replaced.

**Comment by madhushreegc** [comment]
> With the following code? That should hopefully solve things for your setup. With this code the port will also be taken into account for context retrieval.

Sure , I will apply this and will come back to you . Thank you.

**Comment by madhushreegc** [comment]
> For the issue with using multiple ports on the clients in your setup, could you try replacing _normalizeServerUri_ here:

Thanks , code worked.

**Comment by rikard-sics** [comment]
> Thanks , code worked.

That is excellent news.

Then I can prepare a pull request to add this functionality to the codebase. Let me come back also regarding the NIDD transport.

**Comment by boaks** [comment]
Any progress? Or plans to fix that in the next days?

If not, and with the current feedback/experience from 3.0.0-RC2, I would like to release the 3.0.0 tomorrow, 3. November, as already announced in the [Eclipse/Californium - Release Plan](https://projects.eclipse.org/projects/iot.californium/releases/3.0.0).

**Comment by rikard-sics** [comment]
Apologies for the long silence on this. I am back to working on it now and aim to submit a PR within 1 week.

**Comment by rikard-sics** [comment]
> Apologies for the long silence on this. I am back to working on it now and aim to submit a PR within 1 week.

Sorry for the delay on this, I will create the PR before this week is over.

**Comment by rikard-sics** [comment]
> Sorry for the delay on this, I will create the PR before this week is over.

Alright, I have now created a PR that should resolve this here https://github.com/eclipse/californium/pull/1853

**Comment by boaks** [comment]
@madhushreegc 

Did PR #1853 solve your problem? If so, could you please close this issue?

**Comment by madhushreegc** [comment]
Yes. Closing the issue . Thank you .

**Comment by rikard-sics** [comment]
> Yes. Closing the issue . Thank you .

Very nice, excellent to know it solved the issue.
