### ISSUE TITLE
unknown curve name: 1.2.840.10045.3.1.7

### ISSUE THREAD

**Issue by tanghengliang** [eclipse/californium#1750]
When loading the PEM certificate file, an error is thrown: unknown curve Name: 1.2.840.10045.3.1.7. Set the running JDK environment to version 11 and platform 30 on Android studio, but an error occurs when obtaining the certificate private key: Asn1derdecoder.readprivatekey (decode); How to solve this problem, thank you!

**Comment by boaks** [comment]
@tanghengliang 

Sorry, i miss close to all information requested for issues!
- no Californium version nor branch
- no stacktrace
- do you use some of the demo-certificates, which comes with Californium? If not, can you please tryout, if using one solves your issue?

At least the master's [server.pem](https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/server.pem#L6-L7) contains a private key with:

```
SEQUENCE (3 elem)
  INTEGER 0
  SEQUENCE (2 elem)
    OBJECT IDENTIFIER 1.2.840.10045.2.1 ecPublicKey (ANSI X9.62 public key type)
    OBJECT IDENTIFIER 1.2.840.10045.3.1.7 prime256v1 (ANSI X9.62 named elliptic curve)
  OCTET STRING (39 byte) 30250201010420DF69BAB1C8DFF77E0D898305D2EDF39912CBC8ECD542302F2843FEF6…
    SEQUENCE (2 elem)
      INTEGER 1
      OCTET STRING (32 byte) DF69BAB1C8DFF77E0D898305D2EDF39912CBC8ECD542302F2843FEF668C1ECDA
```

and could be loaded "on my machine". (Maybe you can use [ASN.1 decoder](https://lapo.it/asn1js) in order to check your private key, but be very careful, not to leak a "productive key". Just use it with a temporary generated key only for the purpose to check the structure.)

A web-search results in

[Unsupported curve: 1.2.840.10045.3.1.7 on Java app](https://stackoverflow.com/questions/41934099/unsupported-curve-1-2-840-10045-3-1-7-on-java-app)

With the above that may be the hint, that your platform misses EC support. According RFC7252, CoAP, at least supporting that curve is "mandatory", if RPK or x509 is to be used.

**Comment by tanghengliang** [comment]
Thank you for your reply. I have solved the problem. When using the PEM certificate file in the Android platform to read the EC private key / public key, get the EC parameter specification. The keypairgeneratorinitialize (algorithmparameterspec params) implementation class is implemented by default using the openssleakeypairgenerator class in the Google constrypt project. Finally, you will get the unknown curve Name: secp256k1 error message, Therefore, you need to change the security provider and add the providers to be added in Android, such as prov-1.58.0.0 and eddsa-0.3.0

**Comment by boaks** [comment]
If it's resolved, please close the issue, thanks!
