### ISSUE TITLE
[discussion] Should we set client mtu to1442 (openstack default)

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [eclipse/californium#1813]
Just a intersting bug reported by our tester. With rsa certificates(larger in size) wakaama client took about 6s to finish dtls connect while californium client only took 0.1s. 

After days of investigation. we find that the problem is openstack mtu (mtu in openstack docker container is 1442) while a normal linux machine is 1500. Because wakaama send all certificates in chain(don't know why, still investigated by my co-workers) so it's certificate message was much larger than leshan client and reached the max mtu (1500 per IP level package with 16 link layer bytes) and dropped by server.

It's therotically possible that a single certificate has size larger than 1401 bytes(1442-28(ipv4 header length without optional options) - 13(dtls header length)) and then a californium client with 1500 mtu would failed to send message on first try (not tested yet).  Maybe we should change client `org.eclipse.californium.scandium.dtls.RecordLayer#DEFAULT_ETH_MTU` to 1442? (as nowadays most server is deployed in cloud).

**Comment by boaks** [comment]
> wakaama

Which DTLS library is used? Mbedtls? 

The MTU is reflected/considered by the handshake-record-size. Though the PMTU (smallest MTU on the messages path) is the relevant number, the local MTU is just a maximum value. Unfortunately, discovering the PMTU is a topic on it's own. The DTLS library will then split handshake messages (here the server's Certificate message including the complete x509 chain) in fragments in order to fit into that record size.

There are two extensions, a client may chose, to negotiate a smaller record size:
- [RFC6066 - 4.  Maximum Fragment Length Negotiation](https://datatracker.ietf.org/doc/html/rfc6066#section-4), with that you may chose 512 or 1024 to overcame your issue.
- [RFC8449 - Record Size Limit Extension for TLS
](https://datatracker.ietf.org/doc/html/rfc8449), works as well for DTLS.

For both, the client need an assumption about the PMTU.

If that's not supported by the client, then Californium offers you some `Configuration` values as well.

- [DTLS_MAX_TRANSMISSION_UNIT_LIMIT](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L425-438)  
- [DTLS_MAX_TRANSMISSION_UNIT](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L419-423)

For clients, there are also:
- [DTLS_RECORD_SIZE_LIMIT](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L357-364)
- [DTLS_MAX_FRAGMENT_LENGTH](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L367-373)

Finally, to limit attack with fragments, Californium limits also the maximum size of an reassembled message to
- [DTLS_MAX_FRAGMENTED_HANDSHAKE_MESSAGE_LENGTH](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L375-382) ensure, your RSA "beast" chain fits in :-)

The new Configuration supports now 3 levels of defining a configuration value:
- default, compiled in value, if everything else is missing)
- initial value, the value set, when a new configuration (file) is created.
- configured value (Properties file, or "always" set via the API by your application.)

I would consider, that you setup the "initial value" of [DTLS_MAX_TRANSMISSION_UNIT_LIMIT](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L425-438) to that value you assume as limit in your application. For the [leshan demo server](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/LeshanServerDemo.java#L140) that could be done just after calling
`LeshanServerBuilder.createDefaultCoapConfiguration()`.

So, please check, if that works for you.

**Comment by boaks** [comment]
> Because wakaama send all certificates in chain(don't know why, still investigated by my co-workers) so it's certificate message was much larger than leshan client and reached the max mtu (1500 per IP level package with 16 link layer bytes) and dropped by server.

> all certificates in chain 

I'm not sure, what you expect. That's the way, RFC5246 defines the Certificate message. There DTLS uses "fragments" to split larger messages.

> max mtu (1500 per IP level package with 16 link layer bytes) and dropped by server.

Just to say: for IPv6, a message above the MTU will likely be dropped. For IPv4 it may just get fragmented on the IP layer itself. That IPv4 fragmentation is just considered to be somehow not reliable.

**Comment by boaks** [comment]
Let me add:

Therefore, just don't use RSA ;-).

**Comment by Nick-The-Uncharted** [comment]
Wow, that's a lot of things to learn, thank you for your enthusiasm. 

Actully my problem is already solved by setting mtu of wakaama (I am not familiar of wakaama, it's done by my co-workers, they seems to use openssl with `wakaama`).

The RSA certificate is really not something I can control as my client insisted on using same rsa certificates chain as our http service. 

Just thought that is hard to debug without experience, so maybe a smaller default would prevent a lots of trouble for newbies.

**Comment by Nick-The-Uncharted** [comment]
Just for curiosity, why sending raw message don't require spliting, are they fragmented by ipv4 layer? If this is the case, it's very strange the dtls record with size 1500 don't get automatically fragmented....

**Comment by boaks** [comment]
> Just for curiosity, why sending raw message don't require spliting, are they fragmented by ipv4 layer? 

I'm not sure, what raw message exactly means. raw udp message? Yes, sometimes the ipv4 layer does it for you. And sometimes it works. But sometimes it's considered to be to unreliable. Therefore both DTLS and CoAP come with their own "fragmentation/blockwise" handling of larger messages.

Assume, the probability of an 2k udp message goes down to say 95%. Using that just once during the handshake, maybe retransmitting that flight (you gain 99%), is not optimal, but also not that bad. But, if you resend 2k several times, then the less resulting probability makes a difference. Therefore at least at the coap-layer, blockwise helps.

For dtls, my experience is, that this is more the "raw receive buffer size" of a peer, than the MTU. But also here, using smaller messages, comes with some benefit, but not that large, as for coap.

**Comment by boaks** [comment]
> The reason that I think sending entire chain is unusual is leshan client only sent the node cert

That's the difference of the server side and the client side. And of some assumption, valid limitations for LwM2M, but not for a general dtls-x509 use-case.

Maybe it's time, that you try to provide some wireshark logs to see, what happens on the wire. Before the considerations are mislead.

**Comment by Nick-The-Uncharted** [comment]
@boaks Sorry for not able to provide the wireshark logs due to the security constraint of my company, I sincerely apology for that. Actually my problem is already solved and whether sending entire chain is just some implementation detail that may not be important. 

Thanks for your expertise. I learned a lots of knowledge today.

**Comment by boaks** [comment]
> Just thought that is hard to debug without experience, so maybe a smaller default would prevent a lots of trouble for newbies like me.

"Newbies" are not recommended to use "RSA". And to be frank, this is mostly an issue of the embedded peer's buffer size. And this varies much more than just 1500-1442. Some use even 512. So, no, I don't think fixing it on Californium make too much sense. And those "newbies", who don't have the time to read, must then have the time to wait for successful handshakes, though the dtls layer will, after some retransmissions, fallback to a mode, where it tries smaller message. I guess, therefore, after 6s it worked.

**Comment by Nick-The-Uncharted** [comment]
@boaks I find the [leshan issue](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502) for only include node cert. Only reference it here for otherones who may read this issue. Thank you for teaching me so much things.

**Comment by boaks** [comment]
@Nick-The-Uncharted 

Just to say:
It would be very welcome, if your embedded developer can analyze, if the root-issue is the peer's buffer size, rather than the MTU. That help others much more, then reducing the default MTU.

He may easily do that by capturing the IP traffic and check, if adjusting the MTU on the client side results in smaller message send by the server.

**Comment by Nick-The-Uncharted** [comment]
@boaks I didn't get the logic of `adjusting the MTU on the client side results in smaller message send by the server.`, can you explain more? Why mtu in the client side would affect server response?

**Comment by boaks** [comment]
As I wrote, lwm2m makes assumption, which limits the usage scope of x509. With that lwm2m assumption, you may send less in the Certificate message.

Bug generally, without the lwm2m assumptions, the server sends the chain except the root-certificate.
And the client usually consider the received issuers in order to truncate the chain. But, if you have "many" issuers, then it's common to use a empty list, and so the client does the same, as the server, it sends the full chain expect the root-certificate.
(There is also an extension for the client, to indicate the server, where to cut the chain. But that's not implemented in Californium.)

**Comment by Nick-The-Uncharted** [comment]
Sorry for still not able to understand the relation between smaller certificate message and network buffer. Should I use netcat to send message of size 1443(1 larger than 1442) and tcpdump on the target server to assure it's a network buffer issue?

**Comment by boaks** [comment]
> I didn't get the logic of adjusting the MTU on the client side results in smaller message send by the server., 

> Actully my problem is already solved by setting mtu of wakaama (I am not familiar of wakaama, it's done by my co-workers, they seems to use openssl with wakaama).

Again, you may have the ip-capture, not I. Therefore you may know, but I can only guess, based on the experience of the last couple of years.
My assumption is still, it's the servers Certificate message (contains the certificate chain), which is fragmented by the server. If the size of that fragments is too large for the embedded peer's receive buffer size, then this too large message is dropped at the peer's stack, not the IP-layer.

So, if the client "set now the mtu", this may either result in smaller messages, sent by the server, or in a larger receive buffer, used by the client. Therefore the question: does applying a different mtu on the client side lower the size of messages, sent be the server?

**Comment by boaks** [comment]
> Sorry for still not able to understand the relation between smaller certificate message and network buffer. 

If the server sends a handshake message fragment, e.g. 1480 bytes, but you client's udp-raw-receive-buffer is about 1442, then the message is not dopped by the network layer, it's dropped by the client.

As I have repeated:
In my experience, that's mostly the root-cause. A too small receive buffer on the embedded peer.
And therefore it's more important, to point out, that this must be proper.

**Comment by boaks** [comment]
> Should I use netcat

I would prefer, if you just run the handshake with the old client and repeat that with the new client (set mtu). And then compare the size of messages, the server uses. I guess, the size is the same. And with that, it#s not the network layer, which drops the message, it's your client's receive buffer. And that underlines, that it's no good idea to adjust the Californium's default MTU, it's much more important, to make the client developer aware of the setup of their client.

**Comment by boaks** [comment]
Or your embedded developer diggs in hte code, to see, where the mtu value is used in his stack.

**Comment by Nick-The-Uncharted** [comment]
> which is fragmented by the server. If the size of that fragments is too large for the embedded peer's receive buffer size

Okay, I may know the misunderstanding between us. From the capture it's the client(embeded device) package contains client certificate get retransmitted 3 times with total length 1516\1516\592 respectively. So it's not the receive buffer of client that's too small.

**Comment by boaks** [comment]
But then it makes even less sense, to adapt the server's mtu, or?

**Comment by Nick-The-Uncharted** [comment]
It's a misunderstanding, I just suggest changing client mtu:
>  Maybe we should change client org.eclipse.californium.scandium.dtls.RecordLayer#DEFAULT_ETH_MTU to 1442?

**Comment by boaks** [comment]
There is only a general MTU, no client specific. 

if you want to adapt it for a client, that should be done at the client's application.

> With rsa certificates(larger in size) wakaama client took about 6s to finish dtls connect while californium client only took 0.1s.

And with that, it seems for me to be the embedded client, not Californium.

So, I really wondering, why Californium should be adapted.

**Comment by Nick-The-Uncharted** [comment]
It's me that consider this through. I just think that can be adjusted because leshan client also use Californium, but even someone should adpat that, it would be leshan. And after your explaination of mtu varies much more than just 1500-1442, now I know adapting server is meaningless......

**Comment by boaks** [comment]
> From the capture it's the client(embeded device) package contains client certificate get retransmitted 3 times with total length 1516\1516\592 respectively. 

Just for information:
These are the numbers for the embedded client? Without or with mtu set?

**Comment by Nick-The-Uncharted** [comment]
> These are the numbers for the embedded client? Without or with mtu set?

Yes, without mtu set so it's use default 1500 + 16(link layer header).
And later the client backoff and sent smaller package.

**Comment by boaks** [comment]
And with mtu?

**Comment by Nick-The-Uncharted** [comment]
Client mtu 1500, and server mtu 1442 (the default of openstack).
