### ISSUE TITLE
Integration of californium 2.6.5 in leshan 1.3.1

### ISSUE THREAD

**Issue by darkopoppin** [eclipse/californium#1849]
Hello,

I noticed that [californium 2.6.5](https://github.com/eclipse/californium/releases/tag/2.6.5) includes a fix for a [bug](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-34433). I see that leshan 1.3.1 uses californium 2.6.1 and I am wondering if you plan to integrate 2.6.5 in leshan 1.3.1.

Thanks

**Comment by boaks** [comment]
>  if you plan

AFAIK, there are no changes needed in Leshan in order to update to Californium 2.6.6.
As usual, that requires to test the resulting Leshan.

So, though no PR with changes is required from my side, this is more a question to the leshan project, isn't it?

Or what do you assume me or the project Californium to do?

**Comment by boaks** [comment]
@sbernard31 

Any plans to make such a "bugfix" release? 
At least, I don't see, that this is a job, I can do, right?

**Comment by darkopoppin** [comment]
I am sorry. I had two tabs open with leshan issues and californium and I posted the issue in the wrong one.

**Comment by boaks** [comment]
So, please close it.

**Comment by sbernard31** [comment]
@darkopoppin  Leshan 1.3.2 is available :  https://github.com/eclipse/leshan/issues/831#issuecomment-996853462
