### ISSUE TITLE
DTLS handshake fails if ClientKeyExchange and ChangeCipherSpec recieved out of order

### ISSUE THREAD

**Issue by ramporicha** [eclipse/californium#186]
I am using Californium release 1.0.4 as DTLS server. The DTLS connection establishment request used to fail once in every 5 attempts. Upon debugging I have found that the connection establishment fails when ClientKeyExchange and ChangeCipherSpec messages are received out of order.

As per RFC# 6347 (DTLS v1.2), ClientKeyExchange and ChangeCipherSpec are part of same flight (Flight 5). Hence, these messages can be received out of order and should be handled by the server accordingly. The ChangeCipherSpec message should be buffered if received out of order and shouldn't be processed before processing ClientKeyExchange message.

Please find attached the debug logs.
[dtls-err-logs.txt](https://github.com/eclipse/californium/files/672909/dtls-err-logs.txt)

**Comment by sophokles73** [comment]
Thanks for reporting. Most clients send the ChangeCipherSpec message along with the other messages of flight 5 in the same Record so that this is not a problem. May I ask what client you are using?
The problem with the current implementation is that we do the buffering and re-ordering based on the (handshake) messages' sequence numbers. The ChangeCipherSpec message, however, is not a handshake message and thus is not buffered correctly ... I'll take a look into this.

**Comment by sophokles73** [comment]
Fixed on master in ac525cb2f231b0e8b5015904fdc4adf209f81083
Fixed on 1.0.x in 45e57d548af96ba0460299a1197eb4a828e8bca1
Fixed on 2.0.x in f4ad8c09d85cde8917c0c2ba5d1253b50ccda3d4

**Comment by sophokles73** [comment]
@ramporicha,

can you give it a try and see if it fixes the problem?

**Comment by ramporicha** [comment]
@sophokles73 I tried the fix provided and it is working fine now. 
Thank you for such a quick response and fix. Much appreciated !!!

**Comment by sophokles73** [comment]
Glad it works :-) We are planning to do a 1.0.5 release by the end of the week so you won't need to use the snapshot in your project ...
