### ISSUE TITLE
Truststore contains certificates duplicates with subject issue 

### ISSUE THREAD

**Issue by ddtran** [eclipse/californium#1899]
Hello, 

We load 4 unique certificates into the Truststore using 2.0.0-M12 and this worked.  However migrating to 3.0.0-M4 using the StaticNewAdvancedCertificateVerifier and setting the trusted certificates, I am getting an error "Truststore contains certificates duplicates with subject."  I am looking for some suggestions on root causing this issue.

DOCO:
[setTrustStore]
Deprecated. 
use [setAdvancedCertificateVerifier(NewAdvancedCertificateVerifier)]
CertificateVerifier.html) may be used for simple setups. More complex ones may require a custom implementation. During migration you may also use the [BridgeCertificateVerifier] in order to use old implementations for that period.

Method that's causing the exception

	/**
	 * Ensure, that all certificates are unique.
	 * 
	 * @param certificates array of certificates.
	 * @throws IllegalArgumentException if certificates contains duplicates
	 * @since 2.5
	 */
	public static void ensureUniqueCertificates(X509Certificate[] certificates) {

		// Search for duplicates
		Set<X509Certificate> set = new HashSet<>();
		for (X509Certificate certificate : certificates) {
			if (!set.add(certificate)) {
				throw new IllegalArgumentException("Truststore contains certificates duplicates with subject: "
						+ certificate.getSubjectX500Principal());
			}
		}
	}

**Comment by boaks** [comment]
Not sure, what you are trying.

You have "4 unique certificates", but you `X509Certificate.equals` seems to interpret them as not unique.

`2.0.0-M12` is somehow "years" old. The [MIGRATION_HINTS](https://github.com/eclipse/californium/blob/master/MIGRATION_HINTS.md#general) says:

> This document doesn't contain hints for migrating versions before 2.0. That excludes also hints to migrate any of the 2.0 MILESTONE releases.
> 
> If a 2.0.0 or newer is used, it's recommended to update first to 2.6.5 and cleanup all deprecation using the documentation on the deprecation. 

(In the meantime , the last 2x is the 2.7.0, i will update that.)

And to be frank: why 3.0.0-M4? The current release is 3.2

So, in all that years since 2.0.0-M12 a lot of functions have be cleaned up. I guess, if that conflicts with your usage, then your usage considers to be known by us in order to see, if that could be supported. If it's possible for you, to give us more information about your "4 unique certificates", then we will see, what needs to be changed.

**Comment by boaks** [comment]
From checking the `Certificate.equals` I guess:

> We load 4 unique certificates

is 

> We load 4 unique certificates chains

And these chains contains duplicates. e.g. in our demo-certs, we have a root-certificate and a ca-certificate (signed by the root). if now the root-certificate is loaded, and the ca-certificate is added, that works, but if the ca-certificate-chain is loaded, that fails, because that chain also contains the root-certificate. The ambiguity may be caused by the file/trust-store and the functions used to load the trusts. So, please provide more information about the functions and file/trust-store you use.

**Comment by dtreviver** [comment]
Thank you for your feedback.  It was a mistake on my end where I'm setting same certificates multiple times.

**Comment by ddtran** [comment]
Thank you for your feedback.  It was a mistake on my end where I was setting the certificates twice.
