### ISSUE TITLE
InMemoryConnectionStore: build-in support for unique principals?

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1913]
I currently consider to extend the `InMemoryConnectionStore` to keep only one connection per principal.
The intention is to make this configurable.
Upstream projects or deployments, which uses such unique principals will benefit, though resources may be released earlier. That would apply for hono and leshan, or any use-case with such unique principals.

Any opinion?

**Comment by boaks** [comment]
First user feedback:

Sometimes a client may have two session for a short time, e.g. handover/changing the client's network interface.
A compromise may be to also use [DTLS_STALE_CONNECTION_THRESHOLD](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L477-L492) to protect such "intended parallel sessions", but clean them up, if they get stale. In difference to session, where no newer messages from the same principal has arrived.

**Comment by sbernard31** [comment]
### A user feedback : 

**In our use case**, we don't care so much about memory consumed by connectionStore.
Mainly because LRU + limited size seems to do the job. I mean we don't care if connection is release sooner.

BUT we can imagine that only 1 device which does full handshake in loop (intentionally or not) could easily block a lot of slot in `ConnectionStore`  and so limit the number of devices allow to connect at the same time. 
We never faced this but I think this is maybe the main benefits of this ? :thinking:

**Not directly linked** but we faced the same question for our persistent `SessionCache` (1 session by principal)
This was even more an issue than connectionStore because generally a persitent `SessionCache`  has not size limit.

(from another issue)
> Last point, when we try to implement this we face a situation where most of our clients create a lot of new Session. As only the last one is generally reused we try to remove the oldest one. (see [RedisSessionStore.put()](https://github.com/eclipse/leshan/commit/627136a806b20d89ff347788aa626409732835df#diff-cef04d405816a74debc6e269e4bc60bcb4c345d13b07a932513111909fe07284R74-R84), We implement it only for PSK. but maybe this is not an issue for you (or you don't face it ?)

**Comment by boaks** [comment]
> I mean we don't care if connection is release sooner.

Yes, that's true, if your deployment is on the "safe side", means not too much memory "over commitment" e.g. in k8s pods. But, if used in a shared system with memory over commitment, releasing the memory earlier may help.

(For me, the point with the `SessionStore` is more the intended "distributed" nature. 
For Californium itself, it seems to be more a "API" question, but I don't see, that adapting `SessionStore` helps.)

**Comment by boaks** [comment]
With #1982 it's now possible to limit reused principals by applying the DTLS_STALE_CONNECTION_THRESHOLD earlier. That can be enabled with DTLS_REMOVE_STALE_DOUBLE_PRINCIPALS in combination with DTLS_READ_WRITE_LOCK_CONNECTION_STORE. It also replaces the reused `Principal` in order to reduce the heap consumption.
