### ISSUE TITLE
Graceful server restart when using DTLS with CID

### ISSUE THREAD

**Issue by sonny82** [eclipse/californium#1928]
Hi,

We would like to ensure graceful server restart (mainly for maintenance purposes).
I was going through existing threads (a lot of communication and changes over time) but I'm not sure if I completely understand the current state :)
We would really appreciate your help.

Let me first try to explain our scenario..

We are using Californium 3.0 for 3 components in our NB-IoT solution
  - Leshan (Device mgmt Server and Bootstrap server)
  - MQTT-SN Server

We would like to ensure graceful server restart. We use DTLS 1.2 with Connection ID. Currently we are NOT using cluster deployment.
We use InMemoryConnectionStore.
Devices are sleeping devices (battery-powered). They wake up once per day to send meter data to the MQTT-SN server and registration update to Leshan Device Mgmt Server.

We have problem in case of server restart because clients are not aware that session/connection info on the server side has been lost and they keep on sending encrypted data messages (they don't trigger a new handshake for each communication).

The biggest problem is on the MQTT-SN Server side. By default (factory settings) devices trigger a new handshake after 4 unsuccessful attempts (if no ACK has been received). It takes 3 days for the devices to re-connect. 

One way to solve this would probably be to change device settings so that they would trigger a new handshake after 1 or 2 unsuccessful communications.

However, we are also looking for the best way to solve this on the server side. 

Q1:
Is it possible to somehow let the device know that it should trigger a new DTLS handshake if the server doesn't have the session/connection objects instead of ignoring the message? For example, by returning an Alert Close_nofity? Can this be configured in Californium? However, this is probably not the best solution from the security POV...

Q2:
I know that Californium supports SessionCache (I see that it has been renamed to SessionStore recently).
If I understand SessionStore correctly only sessions are stored and not connections? This means that after server restart devices would still have to trigger a new (abbreviated) handshake to resume the session?
In this case this probably doesn't solve our problem.

Do you maybe have any feedback regarding the use of SessionStore? Is anyone already using it (in combination with InMemoryConnectionStore?). I see in comment that it is not well tested.

Q3:
I was also thinking about implementing a custom logic to serialize and store session/connection state on graceful server shutdown to a file or some other store.
On server startup I would simply read the state and fill the InMemoryConnectionStore.

Do you think this would be simply doable or are things more complicated?

Bets regards,
Marcel

**Comment by boaks** [comment]
Q1: if you assume spoofing as not relevant, maybe. Otherwise, please read [IP spoofing - MAC Errors](https://github.com/eclipse/californium/tree/master/scandium-core#ip-spoofing---dos---mac-errors).

Q2: yes the session store is about sessions and usually useful in setups, where the device are using an "auto-resumption", means, if the device doesn't exchange messages for a timeout (e.g. 30s) a new message exchange requires an resumption handshake. if that fails, the server fails back to an full handshake. That's more or less to support devices without DTLS CID. Using that on a single node works quiet well. Using it in a cluster I personally have not too much experience with, you may ask the leshan project about that.

Q3: I'm not sure, why you want to implement a custom logic?
For version 3.3.0 (once it gets available on maven central :-) ):
- the [DTLSConnector](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java) is a [PersistentConnector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/PersistentConnector.java). It supports already serialization and deserialization (since 3.0).
- Though I'm not aware of your MQTT-SN usage (see [1]), Californium adds the support for multiple `DTLSConnector` on the `californium-core` layer. There you find the [ServersSerializationUtil](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/server/ServersSerializationUtil.java) and for encryption the [EncryptedServersSerializationUtil](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/server/EncryptedServersSerializationUtil.java) (since 3.3).  
- For k8s there is also some support to take over the dtls context in flight, see [JdkK8sMonitorService](https://github.com/eclipse/californium/blob/master/cf-utils/cf-cluster/src/main/java/org/eclipse/californium/cluster/JdkK8sMonitorService.java) and [RestoreHttpClient](https://github.com/eclipse/californium/blob/master/cf-utils/cf-cluster/src/main/java/org/eclipse/californium/cluster/RestoreHttpClient.java) (since 3.0, currently under limited redesign to be used without cluster).
- The [cf-plugtest-server](https://github.com/eclipse/californium/tree/master/demo-apps/cf-plugtest-server) shows, how to use a file for a graceful restart (yeah, the code got somehow wired, I already consider to provide simple basic setups, which are easier to take over for own servers (since 3.0).
- The [cf-extplugtest-server](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server) supports the k8s support additionally (since 3.0, currently under limited redesign to be used without cluster)..

Currently I do some redesign for the k8s stuff, in order to use it without the cluster. But for this time, I need to stick to the "StatefulSet", because I can't spend too much more time in it to change that. I may come back to that later, but not for this time. I hope, my work/redesign is ready end of next week.
 
[1] Maybe a good time to consider to add you to the [Adopters](https://iot.eclipse.org/adopters/) see [project-adopters](https://github.com/EclipseFdn/iot.eclipse.org#project-adopters)

**Comment by boaks** [comment]
Further information:

[Benchmark - DTLS graceful restart](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server#benchmarks---dtls-graceful-restart)

[k8s Blue/Green Update With DTLS Graceful Restart](https://github.com/eclipse/californium/blob/master/cf-utils/cf-cluster/README.md#k8s-bluegreen-update-with-dtls-graceful-restart)

**Comment by sonny82** [comment]
Thank you for your kind support. I'll check solutions proposed under Q3.

**Comment by boaks** [comment]
Just to mention:

Unfortunately I found a bug in the dtls graceful restart, introduced in commit  bf4c6b43dc867f4225d8c3b014bb6927d6674980

See PR #1929 for the fix.

**Comment by sonny82** [comment]
Thx for info.

**Comment by sonny82** [comment]
For MQTT-SN we are using just plain DTLS - DTLSConnector (no CoAP).
This probably means I cannot use the abovementioned utility classes, but I can probably reuse some code.

I haven't tried yet persistence of DTLSConnector - will probably do it next week and I'll report.

I talked to our customers and they want me to test the first option (server returning Alert in case of connection is missing), just to know if it works (despite security risks). If I understand correctly, Californium/Scandium doesn't support this, right?

**Comment by boaks** [comment]
> This probably means I cannot use the abovementioned utility classes, but I can probably reuse some code.

Yes, maybe for 3.4 I add a more generic support, that isn't longer depending on `CoapEndpoint` and `CoapSerer`. Not sure, if this is possible for the 3.4, that depends more on other tasks I have.

**Comment by boaks** [comment]
> I talked to our customers and they want me to test the first option (server returning Alert in case of connection is missing), just to know if it works (despite security risks). If I understand correctly, Californium/Scandium doesn't support this, right?

Yes, that's not implemented.

**Comment by sbernard31** [comment]
Interesting discussion, 
Regarding DTLS connection persistency, I can imagine this could work in a cluster with fixed number of instances.
But I'm wondering if this is something which could work in a scalable cluster environment  (where number of instance change dynamically) ? 

My current understanding, is this could not work ? 
The only way seems to be a shared  persistent connection store, but I remember that you think this could not be possible because of : 
>  the "record sequence numbers" will prevent such a implementation.

(note that this kind of shared persistent connection store could also avoid the need of CID loadbalancing)

@boaks , Do you have new thought about this ?

**Comment by boaks** [comment]
If CID is not used, this persistence approach is mainly limited to a single coap server.
But for many test-setups, this is still fine.

If a cluster is used, the point will not only be, if the dtls context is on the right node, it still will be, if the client has really a stable ip address. If that is true, then other solutions may work.

For me, in sum, it's "easier" and for now more "stable" to go with CID then to invest time in alternative approaches.

I didn't get feedback form others, if an alternative was successful or not.

**Comment by boaks** [comment]
Just in the case, someone else is willing to spend time in it:

See the [ConnectionListener](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/ConnectionListener.java) and [DTLSContext](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DTLSContext.java) and you will find also access to internal data in order to share them using such an alternative approach.

**Comment by sbernard31** [comment]
> If a cluster is used, the point will not only be, if the dtls context is on the right node, it still will be, if the client has really a stable ip address. If that is true, then other solutions may work.

By the past all our devices had dynamic API but nowadays we have more and more device with static IP in production.

> For me, in sum, it's "easier" and for now more "stable" to go with CID then to invest time in alternative approaches.

I'm not sure I get the point here. 
I understand that you says that using CID or static IP solve the issue about persisting connection in scalable cluster environment.
But I don't understand how ? (sorry If I missed an obvious part of the explanation)

**Comment by boaks** [comment]
> I'm not sure I get the point here.

The point is, that I don't have the "static" devices, and therefore use CID. And with that, also the cluster works.

And yes, if the cluster is scaled up or down, then you either get "unbalanced" (scales up), or "lose" (scales down) some connections. But, if the number of nodes doesn't change, it works not that bad. Please remember: with the cid-load-balancer it's easy to overcome an adapted peers-distribution when scaling up. But the cluster then gets unbalanced.

**Comment by sbernard31** [comment]
OK, I got that right. So for now this doesn't really fit our use cases. 
Anyway thx for clarification. :pray: 

Please could you keep the "shared persistent connection store" idea in mind, and let me know if one day you have some news on this topic. 
As I guess we are not the only one who could benefits of a "shared persistent connection store" maybe you could create a dedicated wiki page or issue to explain why you think this idea seems not possible (or too complicate/costly) ?

**Comment by boaks** [comment]
> For MQTT-SN we are using just plain DTLS - DTLSConnector (no CoAP).

You may check PR #1944 , that should enable you to persist a DTLSConnector also without CoapEndpoint or CoapServer.

**Comment by sonny82** [comment]
Thank you.
I just implemented it yesterday and it looks like it works fine (I reused a few lines from the utility classes).
Regarding encryption - I'll try to implement it differently so that I won't have to deal with storing/providing the password.

**Comment by boaks** [comment]
@sonny82 

Does the "graceful restart" work for you?
if you have been able the spend a look at the new persistent API in order to support a `DTLSConnector` without a `CoapEndpoint`, does this work as well for you?
If so, could this issue be closed?

**Comment by sonny82** [comment]
Yes, graceful restart works. For now I just wanted to make a quick PoC to make sure this is doable.
However, I haven't yet tried the new persistent API (I'm currently busy doing other things).
I'll do more testing as part of the next release once I'll start implementing this feature for real use.
I think we can close this issue now. I'll reopen it if needed.

Thank you for you support :)
