### ISSUE TITLE
Feature SSLContext DTLS required

### ISSUE THREAD

**Issue by KeithLaiKB** [eclipse/californium#2006]
In this Test below, it just could be found that SSLContext with TLS protocol, 
_TlsServerConnector connector = new TlsServerConnector(serverSslContext, bindToAddress, tlsConfig);_

Could we apply DTLSConnector with SSLContext?

case:
https://github.com/eclipse/californium/blob/e22893f3c6fe47fc692a965e44a05549ed432450/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java

[californium](https://github.com/eclipse/californium/tree/e22893f3c6fe47fc692a965e44a05549ed432450)/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.[java](https://github.com/eclipse/californium/tree/e22893f3c6fe47fc692a965e44a05549ed432450/demo-apps/cf-plugtest-server/src/main/java)

**Comment by boaks** [comment]
> Could we apply DTLSConnector with SSLContext?

No, using an `SSLContext` for an `DTLSConnector` is not supported.
AFAIK, a `SSLContext` comes mainly with a `KeyManager` and `TrustManager` and will so only be able to support `x509` authentication. Californium supports `PSK` and `RPK` as well, and those doesn't fit into a `SSLContext`.

Usually, the `SSLContext` is somewhere build from loaded credentials, Californium offers for that the [SslContextUtil](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/SslContextUtil.java) which enables an application to load trusts and credentials and provide the loaded data then either as `SSLContext` to the common "x509 only TLS" implementations, or to Californium's more flexible DTLS implementation using [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java). Here you may also provide PSK and RPK credentials. Some documentation about the details can be found in [Scandium - README](https://github.com/eclipse/californium/tree/master/scandium-core).
See also [AbstractTestServer - flexible Credential's setup for DTLS](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java#L400-L422) as example.

Beside of additional support for PSK and RPK, scandium's API offers the possibility to access these credentials in an asynchronous manner, it doesn't block scandium's threads, if these credentials must be loaded on the fly, e.g. from an other service (but the additional times required to do so, obvious slows down the handshakes themself).

**Comment by KeithLaiKB** [comment]
> > Could we apply DTLSConnector with SSLContext?
> 
> No, using an `SSLContext` for an `DTLSConnector` is not supported. AFAIK, a `SSLContext` comes mainly with a `KeyManager` and `TrustManager` and will so only be able to support `x509` authentication. Californium supports `PSK` and `RPK` as well, and those doesn't fit into a `SSLContext`.
> 
> Usually, the `SSLContext` is somewhere build from loaded credentials, Californium offers for that the [SslContextUtil](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/SslContextUtil.java) which enables an application to load trusts and credentials and provide the loaded data then either as `SSLContext` to the common "x509 only TLS" implementations, or to Californium's more flexible DTLS implementation using [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java). Here you may also provide PSK and RPK credentials. Some documentation about the details can be found in [Scandium - README](https://github.com/eclipse/californium/tree/master/scandium-core). See also [AbstractTestServer - flexible Credential's setup for DTLS](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java#L400-L422) as example.
> 
> Beside of additional support for PSK and RPK, scandium's API offers the possibility to access these credentials in an asynchronous manner, it doesn't block scandium's threads, if these credentials must be loaded on the fly, e.g. from an other service (but the additional times required to do so, obvious slows down the handshakes themself).

when I read the code, I found the code below, but there is no code to create such configuration,
how could I **use code to create** new configuration about DTLS  like **new Configuration(DTLS.....)**.

code in [AbstractTestServer](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java#L400-L422):
Configuration dtlsConfig = getConfig(Protocol.DTLS, interfaceType);

**Comment by boaks** [comment]
For DTLS, two configuration layers are required:

The [Configuration](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java) for values. Since 3.0, it supports modules. It comes with javadoc, which is recommended to be read.

So, the very first decision which is required, is to decide, which protocols are used.

E.g. DTLS and plain coap, no TCP

Then you need to register these modules with:

```
CoapConfig.register();
DtlsConfig.register();
UdpConfig.register();
```

After that, you need to decide, if you want to use the file support for these configuration values. Assume, the file is wanted (and supported by your environment), you then you use 

```
Configuration config = Configuration. getStandard();
```

There are a couple of "fine-tunig" function, please read therefore the Configuration javadoc.

Once you have your basic `Configuration`, the second step for DTLS is to create a [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java). That's done using a `Builder` pattern.

```
DtlsConnectorConfig.Builder builder = DtlsConnectorConfig.builder(config);
```

Now you mainly provide your credentials for the variants you want.
Here again, Californium offers many possibilities, and you need to decide, what you need.

Assuming, you want to setup Californium DTLS to use x509, then you need to know, which certificate(s) are intended as server-certificates, and which certificates are considered to be trusted.

Californium itself just requires a implementation of the [NewAdvancedCertificateVerifier](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/NewAdvancedCertificateVerifier.java) provided to the (dtls-)builder's, `setAdvancedCertificateVerifier`. You may use a custom implementation, or the provided [StaticNewAdvancedCertificateVerifier](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/StaticNewAdvancedCertificateVerifier.java).

So, do you know, which certificates you want to trust on the server-side? That will be the mechanism to trust your clients. `SslContextUtil` offers some `loadTrustedCertificates` in order to load them. You may also chose whatever loads your trust-certificates into an array. Once you have that, you need to setup a `StaticNewAdvancedCertificateVerifier`, which also comes with a `Builder` pattern. Check the javadoc there, and you will see, that once you know, what you want to trust, it's straightforward. (If you don't know, which certificates you want to trust, then x509 is not recommended. Yes, common other stuff is simply using the environments java trust-certs. If that is a good idea for coap is something you must decide on your own.)  

For the server's certificate, Californium itself requires a implementation of the [CertificateProvider](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/CertificateProvider.java). You may use your custom
 implementation, or one of [SingleCertificateProvider](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/SingleCertificateProvider.java) or
[KeyManagerCertificateProvider](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/KeyManagerCertificateProvider.java). For both, you need to load the server's certificate chain and private key.

So, do you know, which certificate you want to use? Then you may load a "pem" file or a java keystore using one of the `SslContextUtil.loadCredentials` functions. (Again, if you don't know, which server certificate to use, then x509 is not recommended).

if you have loaded the server's credentials, then, depending on your `CertificateProvider` you pass in the loaded credentials and then set that `CertificateProvider` to the (dtls-)builder. For the `SingleCertificateProvider` that's done with.

```
SslContextUtil.Credentials credentials = SslContextUtil.loadCredentials(...);
builder.setCertificateIdentityProvider(new SingleCertificateProvider(credentials.getPrivateKey(), credentials.getCertificateChain());
```

Once you're ready with the (dtls-) builder, then you `build()` the `DtlsConnectorConfig` and pass that to the `DTLSConnector`.

**Comment by boaks** [comment]
So let me ask: do you know, which server certificate you want to use? And which certificates you trust?
If not, I can't recommend to use x509.

**Comment by boaks** [comment]
Let me add:

The plugtest-server uses the [demo-certificates](https://github.com/eclipse/californium/tree/master/demo-certs). Read the README there to get an overview, which certificates are created there.

The server-side credentials are loaded in [AbstractTestServer.initCredentials() ](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java#L239-L253). As server certificates all certificates with an alias matching "server.*" are included. If you only want the basic ecdsa server-certificate, use "server" instead of "server.*" as alias filter (again see javadoc of `SslContextUtil`). As trusted certificates, it load all certificates from the demo trust store.

The loaded credentials are then applied to DTLS in [AbstractTestServer.addEndpoints()](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/AbstractTestServer.java#L404-L419).

As I wrote above, once it's clear what you want to use as server-certificate and which certificates you want to trust, it may be easier to setup DTLS. With flexibility comes also some complexity.

**Comment by KeithLaiKB** [comment]
> So let me ask: do you know, which server certificate you want to use? And which certificates you trust? If not, I can't recommend to use x509.

I gonna use CA certificate, so is it possible to used? and any extra step is required?

**Comment by KeithLaiKB** [comment]
> A CA certificate is used to trust. So, do you want, that your client's trust that CA? Or the server trust the clients by that CA? Or do you want to use a common CA for both?
> 
> If the server should trust your CA, load the certificate and provide it to the `StaticNewAdvancedCertificateVerifier.Builder`. That's it.
> 
> If the clients should trust that CA, you need to sign the server's certificate with that CA. Then load that server certificate as described above.
> 
> And if you want the CA for both, do both.
> 
> (How a CA is used to sign a server certificate (or client certificates), depends on the tools you use. If you use the java keytool, you find some instructions on that's online docu. And some hints in the [create-keystores.sh - create server certificate and sign it](https://github.com/eclipse/californium/blob/master/demo-certs/certs/create-keystores.sh#L180-L187). You may also use other tools, e.g. openssl. Read the openssl documentation, or e.g. [leshan - credentials](https://github.com/eclipse/leshan/wiki/Credential-files-format) )

I want to create my own CA in server, and sign the certificate, then client use the CA certificate to connect the server, like the one-way SSL does, but I want to apply this in DTLS, could it work?

**Comment by boaks** [comment]
Yes, that works.

The preparation of the certificates depends on your tools to create and sign certificates.
Once that done, load the server certificate into the server. Then

```
DtlsConnectorConfig.Builder builder = DtlsConnectorConfig.builder(configuration);
builder.set(DtlsConfig.DTLS_ROLE, DtlsRole.SERVER_ONLY);
builder.set(DtlsConfig.DTLS_CLIENT_AUTHENTICATION_MODE, CertificateAuthenticationMode.NONE);
builder.setCertificateIdentityProvider(new SingleCertificateProvider(<server's private key>, <servers certificate chain>));
builder.build();
```

Add the CA to the client's trust store.

**Comment by boaks** [comment]
Have you been successful?

Could you create a server certificate signed by your CA? Which tools to you use, and which format has the CA and the server certificate?
 Could you load and use the server certificate with Californium?
And could you load the CA and add it to the trusts in the client/device?

If all is done and working, can we close this issue?

**Comment by boaks** [comment]
You're welcome.

Just as remark:

```
Credentials SslContextUtil.loadCredentials(String credentials);
```

Is able to load ".crt" and ".pem". A ".key" is usually just a ".pem" and you may have easier success, if you just rename it to ".pem".

Using the `loadCredentials(String credentials)`returns a `Credentials`and there you need to check, e.g. with 

```
PrivateKey Credentials.getPrivateKey(); 
X509Certificate[] Credentials.getCertificateChain();
```

which one you have loaded and then pass that result into

```
public SingleCertificateProvider(PrivateKey privateKey, Certificate[] chain,
			CertificateType... supportedCertificateTypes);
```

using

```
new SingleCertificateProvider(credentialsKey.getPrivateKey(), credentialsCrt.getCertificateChain());
```

**Comment by boaks** [comment]
Have you been successful? Could this issue be closed?

I added a section about the [SslContextUtil](https://github.com/eclipse/californium/tree/master/element-connector#sslcontextutil) and the [DTLS X509/RPK setup)[https://github.com/eclipse/californium/tree/master/scandium-core#rpkx509].

**Comment by KeithLaiKB** [comment]
> 

sorry, still need some time to implement, maybe next week

**Comment by boaks** [comment]
Thanks for the feedback.

**Comment by boaks** [comment]
Remove the unused verifier.

dtlsConfigBuilder.setAdvancedCertificateVerifier(verifier)

 that line and the lines above that.

**Comment by boaks** [comment]
Check the plugtest Server for such a Ressourcen.

**Comment by KeithLaiKB** [comment]
> 

Hi, I have tried on the server side, and it can run, but on the client side, it encounters something wrong,
I have created the demo in a repository(https://github.com/KeithLaiKB/java_test_learn_cf_dtls)
server: https://github.com/KeithLaiKB/java_test_learn_cf_dtls/blob/main/dtls_server_workspace1/com.learn.californium.server_dtls/src/main/java/com/learn/californium/server_dtls/v3_2_0/trylearn/concise/MyServer.java

client:
https://github.com/KeithLaiKB/java_test_learn_cf_dtls/blob/main/dtls_client_workspace1/com.learn.californium.client_dtls/src/main/java/com/learn/californium/client_dtls/v3_2_0/trylearn/MyClient.java

but on client side it shows:
Exception in thread "main" java.lang.IllegalStateException: certificate verifier must be set on client for configured TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
	at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.verifyCertificateBasedCipherConfig(DtlsConnectorConfig.java:2208)
	at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:2074)
	at com.learn.californium.client_dtls.v3_2_0.trylearn.MyClient.my_configureToPrepare(MyClient.java:144)
	at com.learn.californium.client_dtls.v3_2_0.trylearn.TestMainClient.myrun(TestMainClient.java:68)
	at com.learn.californium.client_dtls.v3_2_0.trylearn.TestMainClient.main(TestMainClient.java:50)

could you please help me to check where I went wrong? Thank you very much!

**Comment by boaks** [comment]
You nee to get common with x509. While the Server doesn't need a verifier if there  is no Client cert to verify, the Client needs it because the Server sends a cert.
I've currently only limited access. I will answer Further questions from the 24. On.

**Comment by KeithLaiKB** [comment]
> You nee to get common with x509. While the Server doesn't need a verifier if there is no Client cert to verify, the Client needs it because the Server sends a cert. I've currently only limited access. I will answer Further questions from the 24. On.

Thank you for your reply, I try add verifier in client side, and they can run without error.

>  in my repository(https://github.com/KeithLaiKB/java_test_learn_cf_dtls)
>  server: >  https://github.com/KeithLaiKB/java_test_learn_cf_dtls/blob/main/dtls_server_workspace1/com.learn.californium.server_dtls/src/main/java/com/learn/californium/server_dtls/v3_2_0/trylearn/concise/MyServer.java

>  client:
> https://github.com/KeithLaiKB/java_test_learn_cf_dtls/blob/main/dtls_client_workspace1/com.learn.californium.client_dtls/src/main/java/com/learn/californium/client_dtls/v3_2_0/trylearn/MyClient.java

but server side couldn't get message from client, or server couldn't sent the message to client.
and in wireshark, it shows that
1	0.000000	127.0.0.1	127.0.0.1	DTLS	179	Client Hello
2	0.066699	127.0.0.1	127.0.0.1	DTLSv1.2	92	Hello Verify Request
3	0.076924	127.0.0.1	127.0.0.1	DTLSv1.2	211	Client Hello
4	0.131485	127.0.0.1	127.0.0.1	DTLSv1.2	47	Alert (Level: Fatal, Description: Illegal Parameter)

although the server side shows that:
[DTLS-Worker-/127.0.0.1:5684#1] INFO org.eclipse.californium.scandium.dtls.ServerHandshaker - Start certificate identity.

**Comment by boaks** [comment]
Sorry, I can't help you with your code.
I guess, once your common with x509 in general, it will be easier for you to make it working.
And if you start with the demo (see above), and change that "step by step", you will see the step, where it breaks.

**Comment by boaks** [comment]
Maybe, I add some general docu about private/public keys and certificates. But though this project focus on coap and dtls and not on x509, that will take some time. You will be really better off, if you get the x509 knowledge from somewhere else.

**Comment by KeithLaiKB** [comment]
> Maybe, I add some general docu about private/public keys and certificates. But though this project focus on coap and dtls and not on x509, that will take some time. You will be really better off, if you get the x509 knowledge from somewhere else.

but dtls also includes the x509, right?
