### ISSUE TITLE
2.0.0-M4 does not send blockwise messages more than 2048 bytes

### ISSUE THREAD

**Issue by evgeniynickolaev** [eclipse/californium#287]
This the following code:

```
package blockwise_test;

import org.eclipse.californium.core.*;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.core.network.CoapEndpoint;
import org.eclipse.californium.core.network.config.NetworkConfig;
import org.eclipse.californium.core.network.interceptors.MessageTracer;
import org.eclipse.californium.core.server.resources.CoapExchange;
import org.eclipse.californium.elements.UDPConnector;

import java.net.InetSocketAddress;
import java.util.Arrays;

public class BlockwiseTimeoutTest {
    public static void main(String[] args) throws Exception {
        NetworkConfig.getStandard().set(NetworkConfig.Keys.BLOCKWISE_STATUS_LIFETIME, 3000);
        CoapServer server = new CoapServer()
                .add(
                        new CoapResource("block") {
                            @Override
                            public void handleGET(CoapExchange exchange) {
                                byte b[] = new byte[2049];
                                Arrays.fill(b, (byte) 0xFF);
                                exchange.respond(CoAP.ResponseCode.VALID, b);
                            }


                        }
                );
        server.addEndpoint(
                new CoapEndpoint(
                        new UDPConnector(new InetSocketAddress(5683)),
                        NetworkConfig.getStandard()
                )
        );
        server.getEndpoint(5683).addInterceptor(new MessageTracer());
        server.start();

        Thread.sleep(1000);
        new Thread(() -> {
            CoapClient client = new CoapClient("coap://lvh.me/block");
            client.setTimeout(5000);
            CoapResponse resp = client.get();
            if (resp != null && resp.getPayload() != null) {
                System.err.println("Got: " + resp.getPayload().length);
            } else {
                System.err.println("NULL");
            }
        }).start();

        System.in.read();
        System.exit(0);
    }
}
```

I get:

```
INFO: /127.0.0.1:33,886 ==> req CON-GET    MID=  512, Token=9b86e0da186378ad, OptionSet={"Uri-Host":"lvh.me", "Uri-Path":"block"}, no payload
Apr 14, 2017 9:39:48 PM org.eclipse.californium.core.network.interceptors.MessageTracer sendResponse
INFO: /127.0.0.1:33,886 <== res ACK-2.03   MID=  512, Token=9b86e0da186378ad, OptionSet={"Block2":"(szx=5/512, m=true, num=0)", "Size2":2049}, 
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
 .. 512 bytes
NULL

```

But if I set 2048 bytes, everything is OK:

```
<skimmed>
Apr 14, 2017 9:40:55 PM org.eclipse.californium.core.network.interceptors.MessageTracer receiveRequest
INFO: /127.0.0.1:34,750 ==> req CON-GET    MID=  424, Token=2d080c03f02a64dc, OptionSet={"Uri-Host":"lvh.me", "Uri-Path":"block", "Block2":"(szx=5/512, m=false, num=3)"}, no payload
Apr 14, 2017 9:40:55 PM org.eclipse.californium.core.network.interceptors.MessageTracer sendResponse
INFO: /127.0.0.1:34,750 <== res ACK-2.03   MID=  424, Token=2d080c03f02a64dc, OptionSet={"Block2":"(szx=5/512, m=false, num=3)"}, 
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
 .. 512 bytes
Got: 2048
```

Am I doing something wrong? I've removed Californium.properties so they are default.

**Comment by evgeniynickolaev** [comment]
Current snapshot: 1.1.0-20170413.061056-43 has the same behaviour.
1.0.5 works OK with that snippet.

**Comment by boaks** [comment]
Try to increase the value of "MAX_RESOURCE_BODY_SIZE" in "Californium.properties" according your requirements.

**Comment by evgeniynickolaev** [comment]
Thank you very much, it works.
However, I think I am not first nor last wit the question.
I'd like to get an exception if my payload doesn't fit.
What do you think?

**Comment by evgeniynickolaev** [comment]
After some code digging I've learned that it was because of the CoapClient which silently cancelled the response.

```
// BlockwiseLayer
} else if (responseExceedsMaxBodySize(response)) {
	LOGGER.log(Level.FINE, "requested resource body exceeds max buffer size [{0}], aborting request", maxResourceBodySize);
	exchange.getRequest().cancel();
}
```
Then response was skipped and there is no way to know what's wrong with it.
I could make a PR but don't know if raising an exception there is appropriate for all parties.

**Comment by evgeniynickolaev** [comment]
Or maybe the upper layer should receive response in this case too

**Comment by boaks** [comment]
Though there `synchronous` and `asynchronous` calls, I guess throwing an `Exception` alone will not be the favorite solution. I think an new field "Throwable internalError" in `Request` should also be introduced.

**Comment by boaks** [comment]
You may provide a PR, if you comply to the eclipse contribute legals, so you need CLA (contribution license agreement).

https://eclipse.org/contribute/cla

(An eclipse account is required to sign a CLA)

**Comment by evgeniynickolaev** [comment]
Yes, I've made a few commits before.

> I think an new field "Throwable internalError" in Request should also be introduced.
Maybe, but a short variant does not imply an explicit request.

```
Response resp = client.get();
```
It just responds with a null.

Though, now I think setting the log level to ERROR would be enough.
At least for me personally.
Is it OK?

**Comment by boaks** [comment]
May be WARNING (your more warned, that its too large, then that it is an error).
But lets give the others also a chance to tell, why it was implemented in the way above.

**Comment by sophokles73** [comment]
The problem is that we (currently) only have limited ways of communicating the outcome of an operation back to client code using the `CoapClient`. The synchronous methods are not designed to throw exceptions specific to any problems occurring during the exchange with the server. The asynchronous methods allow client code to provide a `CoapHandler` callback. However, its `onError()` method is not invoked when the request gets canceled, e.g. by the `BlockwiseLayer`. This is because `CoapClient.MessageObserverImpl` does not override the default (empty) implementation of `MessageObserverAdapter.onCancel()` accordingly.

It also does not seem right to always invoke `CoapHandler.onError()`, if the request is canceled. Instead, we should probably introduce an `onError` method to `MessageObserver` in order to provide a way for the CoAP stack to communicate problems *up the stack* when an unexpected (and unresolvable) problem occurs during processing of a message.

An alternative for now would be to register your own `MessageObserver` on the outbound request before sending it. You can then react to the `onCancel` event in any way you like.

Regarding the correct logging level: the logging is currently designed from the perspective of the stack, not any client code using it. Thus, the statement is currently logged at level FINE because from the stack's perspective, there is no problem at all, i.e. the stack can handle this situation easily. While I can understand that from a user point of view, this is not very helpful, you need to keep in mind that we are not only dealing with single client scenarios but we are also targeting scenarios with hundreds of thousands clients/servers and corresponding amount of message exchanges. So, we always need to carefully weigh expressiveness vs. verbosity of the log. In this case, I think we should stick to the low log level but work on introducing ways to report exceptional situations to the client code.

**Comment by evgeniynickolaev** [comment]
> An alternative for now would be to register your own MessageObserver on the outbound request before sending it. You can then react to the onCancel event in any way you like.

IMHO it isn't a user-friendly solution. However, thanks for so detailed comment.

**Comment by sophokles73** [comment]
> IMHO it isn't a user-friendly solution. However, thanks for so detailed comment.

I agree, that's why I proposed to introduce a way for client code to be explicitly called back when an error occurs.

**Comment by evgeniynickolaev** [comment]
Yes, I see it's far more complex than I thought.
It may deserve a new github issue.
Anyway, my original issue is solved.
