### ISSUE TITLE
Why an additional ResumptionSupportingConnectionStore

### ISSUE THREAD

**Issue by balsmn** [eclipse/californium#31]
@sbernard31 : Just a thought.

When resuming is considered to be a feature of a Connection why not simply add the one method "markAllAsResumptionRequired" (or any other future methods that would allow resumption for a particular connection based on a session ID) to ConnectionStore interface directly instead of a new Interface ResumptionSupportingConnectionStore and marking ConnectionStore as deprecated?

**Comment by sbernard31** [comment]
to keep backward compatibility.

**Comment by sophokles73** [comment]
@balsmn, if your question has been answered, can you please close the issue?

**Comment by balsmn** [comment]
Actually not. May be the question was mis-interpreted.

@sbernard31 Adding a new method to an existing interface is also a compatible change. What I meant was, if resumption is an inherent property of a Connection, then Connection store shall provide a method to set the same. I don't see the need for an additional ResumptionSupportingConnectionStore.

**Comment by sbernard31** [comment]
>"Adding a new method to an existing interface is also a compatible change" 

In java 7, I don't think so. (In java 8, this is possible by using default/defender method, but in this case it does really help because when we can not resume connection we want to clear the connection store)

This is the only reason of this choice.
([here](https://github.com/eclipse/californium/commit/cfce97ef88c87b6ec486ed451923a191db238381#commitcomment-16233590) more comments about that)

**Comment by sophokles73** [comment]
@balsmn the problem here is that client code can provide its own implementation of the interface to the constructor. However, if Scandium wants to invoke the added method and the object passed in by the client only implments the old version of the interface without the new method we will end up with an ugly runtime exception.

**Comment by balsmn** [comment]
@sophokles73 Yes I agree. We could end up having linkage exceptions if scandium wants to invoke the added method. Thanks @sbernard31 for the link. My bad. I agree with you regarding the incompatible change. Now I could now see more in to this discussion and was very interesting to read about DTLS Handshakes. Thanks @sophokles73 for the wiki page describing the session resumption in detail.
