### ISSUE TITLE
ExchangeObserverImpl.contextEstablished(final Exchange exchange) 

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#311]
```
if (exchange.getRequest() != null) {
   observationStore.setContext(exchange.getRequest().getToken(), exchange.getCorrelationContext());
}
keyToken token = KeyToken.fromOutboundMessage(exchange.getCurrentRequest());
exchangeStore.setContext(token, exchange.getCorrelationContext());
```

Is there a reason, why the correlation context in the "observationStore" is (repeated) adjusted for all "current requests" (e.g. each block in a blockwise)?
I would like to optimize this reducing that to observes and the first block.

**Comment by boaks** [comment]
After a discussion with @sbernard31 about the usage of the `onContextEstablished` (it must be ensured, that all operations according the correlation context are finished before returning from the callbac, otherwise there may be race condition with the response and those operations), I have concerns about the API of `ObservationStore `and `MessageExchangeStore ` `setContext`. Currently every request sent with a correlation context will call this `setContext`. As far as I has seen, the implementation then execute a lookup, to see, if somethng should be stored.

**This causes a lookup for every request.**

Currently this lookup would only be required for observes (therefore #314 does some optimization for the observe store, where this seems to be obvious). For the  `MessageExchangeStore ` this optimization would be only possible, if the documation of setContext is change to limit this for observes. If this limitation is not wanted, I would vote for replace the token or keytoken with the request, so that the implementation could use the request for faster filtering.

**Comment by sophokles73** [comment]
Just as a starting point, I am posting @sbernard31's comment from #314:

> For me it's more important to know, which cases would require a setContext XyzStorage call. For now, it seems to be observe. Are there other use cases?

What do you call `XyzStorage` ? we need context for all Request/Response correlation (observe or not), so for all exchanges.

> Why do we need setContext in both storages? 

Both storages (ObservationStore and MessageExchangeStore) store exchanges. When a correlation context is established we must associate it to an exchange. So it should be stored (persisted for persistent store) that's why there is this `setContext` method. For now, I think there is only persistent implementation of `ObservationStore`, as far as I know `MessageExchangeStore` exist only in memory.  

> Why is one called for the request, the other one for currentRequest? 

About `ObservationStore`, we only store observe exchange (we don't store magical blockwise exchange) so we are only interested by the `request` (as `currentrequest` is about blockwise).

About `MessageExchangeStore`, we store every thing except "long term exchange relation" so in that case we care about blockwise transfert so I suppose this is the idea about why we use `currentRequest` instead of `request`.

FMPOV, setting correlationContext on observation store only for observe request make sense to me. (good optimization)
Without thinking too much , raising the event `onCorrelationContext` only when it really change can not be a bad modification. (using equals not != of course :p)

But if we think more about that, Exchange is used for :
 - Request/Response.
 - ObserverRequest/Response/notification
 - Resquest/Response + magical blockwise

For me in all case, the correlation context should not changed.
With our current implementation, the only case where context is changed (I mean not initially set) is when we do blockwise transfer. The question is "Should we allow to change context for a whole blockwise transfer?" 
Personally, I'll be tented to say "no".
It's not clear to me but the [RFC 7959](https://tools.ietf.org/html/rfc7959#section-7) seems to say "no" too :
_" Where access to a resource is only granted to clients making use of
   specific security associations, all blocks of that resource MUST be
   subject to the same security checks; "_

**Comment by sophokles73** [comment]
@boaks, maybe you can add some comments in reply to what @sbernard31 wrote so that we can get the discussion started. Is there anything that you disagree with?

In direct response to your initial description for this issue:

> As far as I has seen, the implementation then execute a lookup, to see, if something should be stored.
This causes a potential time-consuming lookup for every request.
Currently this lookup are only be required for observes (therefore PR #314 does some optimization for the observe store, where this seems to be obvious). For the MessageExchangeStore this optimization would be only possible, if the documentation of setContext is change to limit this for observes. If this limitation is not wanted, I would vote for replace the token or keytoken with the request, so that the implementation could use the request for faster filtering before the lookup is executed.

An expensive lookup is only expected for the `ObservationStore` since the data contained is supposed to be shared with other nodes. The information in `MessageExchangeStore` on the other hand is not supposed to be shared but is scoped to the local node. In addition, the information in `MessageExchangeStore` is short-lived only, i.e. it is scoped to a single request/response exchange with a peer, whereas the `ObservationStore` contains the information necessary to track observations over a (potentially) longer time (and across nodes after a fail-over). So, FMPOV invoking `MessageExchangeStore.setContext()` on every message being sent with a correlation context should not be a problem. Invoking `ObservationStore.setContext()` only on establishment of the observe relation seems to be a good optimization.

I wonder, though, whether the correlation context of an established observe relation can change over time, e.g. if the server's IP or port changes.

**Comment by boaks** [comment]
> So, FMPOV invoking MessageExchangeStore.setContext() on every message being sent with a correlation context should not be a problem.


```
	/**
	 * {@inheritDoc}
	 * 
	 * This method does nothing because all exchanges are kept in memory and
	 * thus the correlation context will already be set on the corresponding
	 * exchange object.
	 */
	@Override
	public void setContext(final KeyToken token, final CorrelationContext correlationContext) {
		// nothing to do
	}

```

Thanks for the explanation about the `MessageExchangeStore`. Now I get more and more the impression, that the `MessageExchangeStore.setContext()` is simply obsolete :-).
So, what's the purpose of this method? My impression was, that it should allow a "PersistentImplementation", but with "short-lived only" this doesn't make sense.

**Comment by boaks** [comment]
> I wonder, though, whether the correlation context of an established observe relation can change over time, e.g. if the server's IP or port changes.

This depends on a lot of interpretation :-).
Is a resumed DTLS session (more or less just using the same numeric value for the epoch) interpreted as "same epoch" (because of the numeric value) or as "different epoch"?  

But in the last days, there have been some discussions in the core mailing list about the use of the epoch:
https://www.ietf.org/mail-archive/web/core/current/msg08774.html

So, maybe, this is changing ...

**Comment by boaks** [comment]
https://github.com/eclipse/californium/pull/314#discussion_r120403178 sbernard31 

> Without thinking too much , raising the event onCorrelationContext only when it really change can not be a bad modification. (using equals not != of course :p)

https://github.com/eclipse/californium/pull/314#discussion_r120302284 boaks

> There is currently a ongoing discussion about the request response matching in the ietf core mailing list. Before there is a conclusion there, I would not like to fix the behaviour in that way.
> (https://www.ietf.org/mail-archive/web/core/current/msg08814.html).
> 

So, yes, we can optimize this. But I would feel more comfortable, if the discussion in the mailing list came to a conclusion.

And, if we remove the `MessageExchangeStore.setContext()` this optimization seems also to be obsolete.

So I would prefer to concentrate on the usage of that `MessageExchangeStore.setContext()`.

**Comment by boaks** [comment]
https://github.com/eclipse/californium/pull/314#discussion_r119136875 sbernard31 

> We check that request == currentRequest.
> This happens only for blockwise transfer.
> For block2 it's ok as this avoid to set context for each block2 request.
> For block1 this means that correlation context will only be set when the request will be completely sent. I think this is a problem. I think we want to set the correlation as soon as possible.

My intention for checking  request == currentRequest was not to update the request with a correlation context of a follow up request.
@sbernard31 
I don't understand, why this should delay the processing of the correlation context for block1 until this is completely sent. Can you show, why this should happen?

**Comment by sbernard31** [comment]
> I don't understand, why this should delay the processing of the correlation context for block1 until this is completely sent. Can you show, why this should happen?

[A new request will be create for the first block1](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java#L209), so the context will not be set because `request != currentRequest`. After looking more deeply I think for block1 `request == currentRequest` is always `false`. In practice observe request which uses block1 should not happen often but this is not a good reason.

I still think that the real question is "Should we allow to change context for a whole blockwise transfer?" 
And the discussion about DTLS and epoch is more about "what is the correlationContext ?" but I ask "whatever could be the correlationContext, should we allow it to change while blockwiser transfer?"
My response is "no, it must not change".

**Comment by sophokles73** [comment]
> I still think that the real question is "Should we allow to change context for a whole blockwise transfer?"
And the discussion about DTLS and epoch is more about "what is the correlationContext ?" but I ask "whatever could be the correlationContext, should we allow it to change while blockwiser transfer?"
My response is "no, it must not change".

I do not see how it could, actually. Am I missing something?

**Comment by sbernard31** [comment]
It could be changed each time we send a blockwise request. (If I read the code correctly)

**Comment by boaks** [comment]
Thanks for the explanation about block1 request!

RFC 7641, 1.2

> Registration:  A client registers its interest in a resource by
>       initiating an extended GET request to the server. 

I didn't found any other requests then GET mentioned there.  

RFC 7252, 5.5.  Payloads and Representations

>    Both requests and responses may include a payload, depending on the
>    Method or Response Code, respectively.  If a Method or Response Code
>    is not defined to have a payload, then a sender MUST NOT include one,
>    and a recipient MUST ignore it.
> 

But I could not find that definition for GET. But I assume, payload doesn't make sense here, and therefore I don't see block1 being used with observe.

**Comment by boaks** [comment]
Latest from the core mailing list:
https://www.ietf.org/mail-archive/web/core/current/msg08821.html

@sbernard31 
Maybe, this is the time to (re-)propose your 
https://www.ietf.org/mail-archive/web/core/current/msg08004.html

> IMHO, using the DTLS identity seems the better choice. (PSK identity for PSK, public key for RPK, CN for certificate).

**Comment by boaks** [comment]
My sum-up:

1. `MessageExchangeStore.setContext()` if no usage/use-case is reported, I would go for delete it. In the meantime I think adding a comment about the considerations (message sent on return, so no expensive/blocking processing) should do it.

2. `ObservationStore.setContext()` filter by `request.isObserve()`.
Using `request == currentRequest` to filter the first exchange of a blockwise will not work for block1,
but it seems not to make sense to use block1 and observe.
Filtering on the first `Exchange.setCorrelationContext()` makes sense, but with the current ongoing discussion in the ietf core mailing list there is a small probability, that it must be adjusted again.

So just give your vote for:
A. document and test, that observe is not supported for block1 (#314)
B. use the "filter on first  Exchange.setCorrelationContext()" instead of `request == currentRequest`
C. any other useful proposal

**Comment by sbernard31** [comment]
About 1. I'm ok to remove `MessageExchangeStore.setContext()`. For now, my opinion is we don't need to persist this store.

About 2. I still rather prefer the B option, but I can live with A.

**Comment by boaks** [comment]
Related PR is merged and picked to master.
