### ISSUE TITLE
Remove ErrorHandler in scandium

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#339]
Now we can get Handshake exception via `MessageCallback.onError`, I think we can remove `ErrorHandler`. See [discussion](https://github.com/eclipse/californium/pull/334#discussion_r124233339).

**Comment by sbernard31** [comment]
I would like to remove `ErrorHandler`, this should not be a big change. Is there any objection ?

**Comment by sophokles73** [comment]
I have no problem with removing the `ErrorHandler`. I agree that `MessageCallback.onError()` is the better approach in that it provides more information about the context in which the ALERT has occurred.

So, now (before we release 2.0.0) would be a good opportunity to get rid of it because it will break existing (but probably mostly unused) API. If you find the time, please go on. Otherwise, I would volunteer to remove it as well, given that I haven't done a lot on Cf recently ;-)

**Comment by sbernard31** [comment]
I will not have time this week, maybe the next one. So if you want you can go on it.

**Comment by sophokles73** [comment]
I'll give it a try ...

**Comment by sophokles73** [comment]
The more I think about the less convinced I am that we should actually remove the `ErrorHandler`. I agree that we should not use it for the same purpose as the `MessageCallback.onError()` method. However, it provides a way to get notified about a peer closing a session/connection which we would have no other means for if we removed the `ErrorHandler`. That said, I would like to rename it to just `AlertHandler`, because that is its sole purpose, and update the JavaDocs accordingly.
In #530 I had started to move the handler to the `org.eclipse.californium.scandium.dtls` package and use the handler kind of *internally* only. However, I now believe that it would be best to keep it in `org.eclipse.californium.scandium` and to keep registering on the `DTLSConnector` instead of the `Connection`. This is because application code will probably never (need to) get a grip on a particular connection/session but will usually need to set up and configure the `DTLSConnector` anyway. So it seems reasonable to me to also set a handler on the connector if an application is interested in notifications that a peer has closed a connection.

**Comment by sbernard31** [comment]
I'm not sure to see the interest about knowing we receive an alert.
I don't know how to use it for now, except maybe for monitoring but in this case logging seems enough to me.

Currently, my feeling is that this is not useful.

But I will not fight to much for this.

@boaks, maybe an opinion about this ?

**Comment by sophokles73** [comment]
At least it seems to be helpful for implementing test cases :-)

**Comment by sbernard31** [comment]
> At least it seems to be helpful for implementing test cases :-)

If this is the only reason, not sure this is enough to put it in the API, but again this is not a strong opinion.
