### ISSUE TITLE
Blockwise feedback and exchange cleaning

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#358]
I see in BlockwiseLayer, there is blockTimeout.
It seems to be only for outcoming block2 and incoming block1. So this is timeout to wait for the next GET.
When this timer expired we just clean the blockstatus cache.
But should we clean the exchange (using something like exchange.setComplete) ?
And for block2, should we report this timeout with Message.onTimeout (or something else?)

**Comment by boaks** [comment]
Working on #356 I got aware, that if a single block request is timed out, the outer complete request will not be aware of that. I fixed that in `Exchange.setTimedOut()`. The other "errors" need to be checked also.

If two blockwise transfers are simultaneously ongoing, I found it's not enough to clear the "blockstatus" of one, the (client-side) exchange should be also "stopped" somehow. 

Right now, I would guess, that except of the "unaware simultaneous blockwise transfer", usually the "block status" should not require to cleanup the Exchange, because the Exchange should be cleaned up on itself.

**Comment by boaks** [comment]
> But should we clean the exchange (using something like exchange.setComplete) ?
> And for block2, should we report this timeout with Message.onTimeout (or something else?)

As far as I understand, the `BlockwiseStatus` is just a helper for holding or assembling the blocks. Therefore the `Exchange` cleanup is done on the Exchange mechanisms, maybe triggered when processing messages related to the resource. See #363, which addresses the timeout and the complete for several cases.

I also tried to check, if the "ExchangeStore" is empty for `ObserveServerSideTest`; it isn't. 
But without further logging information in the exchange it seems to me to be too time-consuming to fix that.

**Comment by boaks** [comment]
Can we close this?

**Comment by sbernard31** [comment]
I don't think so.

>  should we clean the exchange (using something like exchange.setComplete) ?

I think we should add some test about that. I mean test about block timeout.

> should we report this timeout with Message.onTimeout (or something else?)

Still no answer to this one but maybe this will be drived by tests.

**Comment by sophokles73** [comment]
@sbernard31 
Achim and I are currently trying to identify issues that need to be done in 2.0.0. Is this one of them? Who is working on this?

**Comment by sbernard31** [comment]
I'm working on it. #449 is related to it. #414 is probably related too.

**Comment by sbernard31** [comment]
With #449 and #475, I hope this behave better now.
