### ISSUE TITLE
CertificateRequest#removeTrustedCertificates is skipping to check some values

### ISSUE THREAD

**Issue by AlexITC** [eclipse/californium#364]
The method `CertificateRequest#removeTrustedCertificates` is incrementing the array index twice, causing unexpected behavior like padding the resulting array with trailing nulls or not checking some values.

See line 10 where `i` is incremented while it should not (it is already incremented in the for loop):
```java
	public X509Certificate[] removeTrustedCertificates(X509Certificate[] chain) {
		if (chain == null) {
			throw new NullPointerException("certificate chain must not be null");
		} else if (chain.length > 1) {
			int i = 1;
			for ( ; i < chain.length; i++) {
				if (certificateAuthorities.contains(chain[i].getIssuerX500Principal())) {
					break;
				}
				i++; // THIS ONE
			}
			return Arrays.copyOf(chain, i);
		} else {
			return Arrays.copyOf(chain, chain.length);
		}
	}
```

**Comment by AlexITC** [comment]
if anyone knows, I wonder why are we ignoring the first certificate of the chain, see line 5 (`int i = 1;`).

**Comment by boaks** [comment]
> The method CertificateRequest#removeTrustedCertificates is incrementing the array index twice,

That's done to speedup the expensive security calculations.
(OK, maybe we consider to remove that speedup :-) .)

> if anyone knows, I wonder why are we ignoring the first certificate of the chain

As far as I know, the idea is to send only the "certificate path" up to the first trusted certificate.
Usually the server send the DNs of the certificates, it will trust (CERTIFICATE_AUTHORITIES). So a client can reduce its certificate path up to the first trusted certificate.
Starting at 1 instead of 0 will ensure, that at least the clients certificate itself is contained in the send certificate path. That approach would only fail, if your "chain of trust" is broken, say trust 0, but not 1. But if you assume the chain is broken, I don't see how this should then provide security at all.

**Comment by AlexITC** [comment]
About the speed up, we could keep it if you think is necessary, the null padding is biting me with a NullPointerException, thanks.

**Comment by boaks** [comment]
I'm not sure, what you man with "null padding", can you try to explain it in more details?
It's not the check 

> if (chain == null) {
>     throw new NullPointerException("certificate chain must not be null");
> }
> 

, or?

**Comment by boaks** [comment]
After reading the doc for `Arrays.copyOf` I understand your point :-).

**Comment by AlexITC** [comment]
Exactly, if you want to keep the speed up, we could fix it with `return Arrays.copyOf(chain, Math.min(i, chain.length));` to avoid the null padding.

**Comment by AlexITC** [comment]
in fact, my pull request contains a test that reproduces the behavior, passing an array with 2 elements results in an array with 3 elements.

**Comment by boaks** [comment]
@AlexITC 

Your PR #364 is merged. Could you please retest this issue and close it, if it's solved?

**Comment by AlexITC** [comment]
it seems to be gone, thanks!
