### ISSUE TITLE
What is the latest Californium version?

### ISSUE THREAD

**Issue by JurisPuchin** [eclipse/californium#489]
I see that in the readme, it is recommended that version **2.0.0-M2** should be used.

While on MavenCentral, the latest version is **2.0.0-M5**.

Which is the correct stable version to use?
Where can I find appropriate up-to-date usage examples?

**Comment by vikram919** [comment]
On MavenCentral, the latest stable version is  2.0.0-M5, but does not contain many changes.
Currently Eclipse Californium contributors are planning to release new milestone called 2.0.0-M6.
If you need a stable latest version, as far as my knowledge you need to wait for one more week.

> Where can I find appropriate up-to-date usage examples?

you can use branch 2.0.x which has all recent and current updates.

**Comment by boaks** [comment]
> While on MavenCentral, the latest version is 2.0.0-M5.

Should have changed on friday to 2.0.0-M6.

> Which is the correct stable version to use?

Depends on what you exactly want to do and how you define "stable". 
But, as also in some other open source projects, you can easily try out, which of the branchs/releases fits best to your requirements. My personal favorite is the 2.0.x, that's the one where the most features are added and may be added in the future. But because of those extensions, the API may change in the 2.0.x.
So if "stable" means "no API changes", just take the "1.0.x" but also life with the limitation there. Therefore very carefully test, if the 1.0.x fullfils your requirements in functionality and quality.  

> Where can I find appropriate up-to-date usage examples?
Hopefully in demo-apps. This should be valid for all branches 1.0.x, 1.1.x, and 2.0.x

**Comment by JurisPuchin** [comment]
Thank you for your response!

So, if I am understanding this correctly, there should be no API difference between 2.0.0-M2 and 2.0.0-M5 and M6?

I was asked to  solve some issues with an application that uses Californium, and I found that upgrading from M2 to M5 changed the behavior of my application. That is, the application does not work with M5.

So my next step is to see how the application uses Californium and check whether this matched the correct usage, but I wanted to make sure I have the right code examples of correct usage first.

Briefly, my application needs to send/receive json objects over COAP.

**Comment by boaks** [comment]
> So, if I am understanding this correctly, there should be no API difference between 2.0.0-M2 and 2.0.0-M5 and M6?

You just understand me completely wrong :-).
The 2.0.x API will change frequently, if required. Therefore I wrote above

> the API may change in the 2.0.x.

For the rest of you general questions, I unfortunately can't answer them, because there are full of assumptions and a lot of information is missing (e.g description of the errors), and therefore could not be of any help.

> Briefly, my application needs to send/receive json objects over COAP.   

Briefly, I do this as well.

**Comment by boaks** [comment]
Just to say, if you report single "errors" (starting with the first your application reports when started), we will be able to help you. Please provide then the information which implementations you are using (client- serverside). also, if possible, check, if wireshark captures related to the error could also be reported along with the californium logs.
