### ISSUE TITLE
element-connector-tcp 2.0.0-M6 not released

### ISSUE THREAD

**Issue by swachter** [eclipse/californium#491]
The new modul element-connector-tcp seems to be missing in the release process.

**Comment by sophokles73** [comment]
hmmm, we are (currently) considering TCP support as experimental, so I am not sure if we actually *want* to include that component in milestones.

@boaks @sbernard31 @mkovatsc WDYT?

**Comment by sbernard31** [comment]
Actually, I was thinking that was a mistake and I was searching why it is not available.
Personally,I don't know the current state of `element-connector-tcp`, so I have no strong opinion about that. 

What I know : 
- TCP support was contained in previous milestones release.
- If we don't release element-connector-tcp, we have "coap-tcp" code available in californium.core but no connector available to use it.

So maybe this make sense to integrate it ? **If we want** to insist on the experimental state and if this is feasible,  we can maybe use a different version number ?

@boaks, @sophokles73  did you have change the build config of https://hudson.eclipse.org/californium/job/parent-release/ since I release the 2.0.0-M6 version ? 
because I see : 
```
--projects
californium-osgi,californium-proxy,scandium-core,element-connector-tcp
```
So element-connector-tcp should have been deployed, right ?

**Comment by boaks** [comment]
Yes, I already corrected the jenkins job and added the `element-connector-tcp`.
I would prefer to provide the tcp stuff by default, because some users I know, prefer to use a "more stable milestone" than "SNAPSHOT" or self-build "SNAPSHOT".

**Comment by boaks** [comment]
And just to say, I got also some additional feedback I want to adjust before we create M7 :-).

**Comment by sophokles73** [comment]
@boaks sounds good to me :-)

Do we want to create a element-connector-tcp-2.0.0-M6 artifact or just wait for the M7?
The former is possible but would require a little tweaking of the release build job. So, if we can live with waiting for M7 I'd rather do that ...

**Comment by boaks** [comment]
Wait for M7.

**Comment by boaks** [comment]
@swachter 
Thanks for reporting, I close it and will have a eye on the fixes and tcp when we release the M7.

**Comment by AlexITC** [comment]
I don't understand, what's wrong with this library in M6? We are trying to upgrade to Leshan 1.0.0-M5 which depends on Californium M6, and we depend on the TCP/TLS connectors.

We are using the library at our own risk anyway, at the moment we would have to deploy it to our internal servers which is not ideal because we haven't changed anything.

**Comment by boaks** [comment]
> I don't understand, what's wrong with this library in M6? 

Nothing, we just forget to add this library to the jenkins job's project list, when we split it into a separate module.

FMPOV, I would like to finish PR #521 and the we can trigger a next milestone release to check the jenkins job as preparation for the release.

**Comment by boaks** [comment]
@AlexITC 

So the 2.0.0-M7 is released. Please check and report, if issues occur.
