### ISSUE TITLE
Scheme not set on Maven Central 1.0.4 version

### ISSUE THREAD

**Issue by MehdiFal** [eclipse/californium#51]
Hi, 

Just a heads up for other developers so they don't spend time scratching their heads while investigating why the scheme is always null like I did the past 2 days.

On the class : `package org.eclipse.californium.core.network.CoapEndpoint` inner class `InboxImpl` method `private void receiveMessage(RawData raw)`

The versions on the Maven Central Repo don't contain this line : 
`request.setScheme(raw.isSecure() ? "coaps" : "coap");` which leads to the scheme not being set.

It's set however on the `1.1.0-SNAPSHOT`, so you may want to use it (by building the source from the Github repo).

Thanks.

**Comment by sophokles73** [comment]
@MehdiFal,

thakns for pointing this out. However, this is not by mistake but is due to the fact that the 1.0.x bug fix releases do not contain the changes in Scandium necessary to actually determine whether an incoming request was received over a secure connection or not. This is only available on master and will thus become part of Californium 1.1.0.

Regards,
Kai

**Comment by MehdiFal** [comment]
Thanks @sophokles73 !
