### ISSUE TITLE
PSK identity requires extension for SNI

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#511]
Branch 2.0.x

The `PreSharedKeyIdentity` doesn't obey a optional indicated server name. Therefore the `Principal` equals check may report accidently the same `Prinicipal`, if the same identiy name is used for different servers.

Requires extension of `PreSharedKeyIdentity` and fixes in `ServerHandshaker` and `ClientHandshaker`.

**Comment by boaks** [comment]
Just to mention:
Without a fix, it must be ensured, that a PSK identity is not reused for a different SNI-domain. Otherwise californium is not able to distinguish between such two endpoints with same PSK identity but different SNI.

**Comment by sophokles73** [comment]
Is this a problem only for PSK identities? Since the client can use SNI for any type of client authentication mechanism I would expect this to be a problem for RPK and X.509 client certificate identities as well, i.e. we should probably scope all of the `Principal`s we use to represent the authenticated client to the `ServerName`, or am I mistaken?

**Comment by boaks** [comment]
I assumed, that the public keys of x.509 and RPK are generally unique, otherwise the security seems to be 
broken in a more general way.

**Comment by boaks** [comment]
Fixed with PR #643
