### ISSUE TITLE
Retransmission issue

### ISSUE THREAD

**Issue by calvingao** [eclipse/californium#52]
I was testing the CoAP in a lossy connection environment and got some problem in retransmission.

I tried to send CON requests (GET, PUT) in the synchronous mode from a client to a server. With a probability of packet loss, a percentage of requests may not be delivered to the server. That triggers the retransmission from the client. These part works well and I can find those requests successfully delivered from the retransmission and processed to the server .

As it is described in the RFCs. The responses are sent back in an ACK back to the Client. (which I can confirmed using the ".advance().getType" ). Once the original request is not acked, it can be either the request was not delivered to the Server, or the ACK was not delivered back to the Client. 

The problem I experienced occurred in the second situation. If the Server received and responded to the original request, but the ACK was not delivered, the Client should resend the request. However, the re-sent request was not responded by the Server that had already responded to the original Request. As a result, no ACK would be sent to the Client and the finally the Client received no response to the Request.

For example, in a connection with 20% packet loss, I can get [1-(20%)^5 = 99.97%] of my request delivered to the Server. If the retransmission works properly, I should get [1-(36%)^5 = 99.40%] of my request finally acknowledged by the Client. However, I got 99.9% of my request processed in the Server side, and only about 80% of my total requests acked in my experiment. That indicates the Server did not respond to any retransmitted request whose original request had been responded but the response was lost.

I tried both GET and PUT and get the similar result as above. 

I guess it may be because of the way a server deal with the MessageID or TokenID, which prevent the server from processing an already processed request. Just my guess.

**Comment by sophokles73** [comment]
@calvingao,

is this still an issue for you? I have just created a test case for the situation you describe, i.e. server's ACK containing the piggy-backed response is lost and client re-transmits its request. The test runs without problems so I would be interested to know where you stand with this.

BTW Which version of Californium are you using?

**Comment by DanielMaier-BSI** [comment]
Hi,

I think we observe a similar behaviour in conjunction with Leshan with the following message flow:
- LWM2M client sends register request
- LWM2M server receives register request
- LWM2M server sends piggy-backed response
- LWM2M client does not receive response because of networking issues
- LWM2M client retries request
- LWM2M server receives request
- LWM2M server identifies message as a duplicate and logs that response gets sent again
- LWM2M server does NOT send response (Does not appear in MessageTracer)

Here are some Logs that we create with the help of a MessageTracer:
```
09:17:21.187    x.y.z.LogMessageTracer                                            /23.23.23.23:4242 =RX=> req CON-POST   MID=47866, Token=, OptionSet={"Uri-Path":"rd", "Uri-Query":["ep=XYZ","b=UQ"]}, "</1/0>,</3/0>,</5/0>,</1".. 42 bytes
09:12:57.497    org.eclipse.californium.core.network.stack.ReliabilityLayer       Respond with the current response to the duplicate request
09:12:57.497    org.eclipse.californium.core.network.Matcher                      Duplicate request: CON-POST   MID=47866, Token=, OptionSet={"Uri-Path":"rd", "Uri-Query":["ep=XYZ","b=UQ"]}, "</1/0>,</3/0>,</5/0>,</1".. 42 bytes
09:12:57.497    x.y.z.LogMessageTracer                                            /23.23.23.23:4242 =RX=> req CON-POST   MID=47866, Token=, OptionSet={"Uri-Path":"rd", "Uri-Query":["ep=XYZ","b=UQ"]}, "</1/0>,</3/0>,</5/0>,</1".. 42 bytes
09:10:46.905    x.y.z.LogMessageTracer                                            /23.23.23.23:4242 <=TX= res ACK-2.01   MID=47866, Token=, OptionSet={"Location-Path":["rd","XYZ"]}, no payload
09:10:46.898    x.y.z.LogMessageTracer                                            /23.23.23.23:4242 =RX=> req CON-POST   MID=47866, Token=, OptionSet={"Uri-Path":"rd", "Uri-Query":["ep=XYZ","b=UQ"]}, "</1/0>,</3/0>,</5/0>,</1".. 42 bytes
```

We are using version 2.0.0-M2. We only get this issue sporadically with a live system, but can not reproduce it.

Are there any news on this issue or does anyone has an idea? We will keep trying to reproduce this.

Thanks
Daniel

**Comment by boaks** [comment]
Using PR #523 and #524 the issue could be retested.

Start NAT emulator with:

> :6783 localhost:5783 20

(forward 6783 to 5783, drop 20% of the messages)
and the BenchmarkClient with:

> coap://localhost:6783/benchmark 500 200 nonestop

results in:

> 100000 requests sent, 100000 expected
> 100000 requests in 507177ms, 197 reqs/s
> 54564 retransmissions (54,56%)
> 501 transmission errors (0,50%)

So about 99,5% of the request are successful.

Using asymmetric message dropping (more test-weight on response resending) 

> :6783 localhost:5783 -f5 -b20

(forward (request) 5% drops, backwards (responses) 20% drops)

results in:
> 100000 requests sent, 100000 expected
> 100000 requests in 217846ms, 459 reqs/s
> 30796 retransmissions (30,80%)
> 42 transmission errors (0,04%)

That shows, that the issue is fixed.
