### ISSUE TITLE
Restoring observe relations after Californium restart

### ISSUE THREAD

**Issue by eugene-nikolaev** [eclipse/californium#535]
Hello!

In my case:
- an embedded device connects to a Californium server.
- server sets up an observe relation
- embedded device sends notification when has data
- I restart a Californium server due to redeploy and 
new instance of Californium does not know about that relation since they were stored in-memory
so responds with RST.

I'd like to restore that observe relation somehow.
Or at least catch that unknown Observe notification.

@boaks wrote in cf-dev:

> here is some to define in the wording, e.g. server and client, and coap-server and coap-client. Because, if you restart the server, you restart the coap-client of your observes. There is some kind of support for that, because leshan requires that as well. But it’s currently not “out of the box”.

> The easier solution is, just to reestablish a new observation, when you server (coap-client) restarts.

Yes, so I restart the coap-client of observes and lose observe relations.

The issue is that my embedded device goes offline after sending an observe notification, until it gets some data.

Well, I realize there is no such option out-of-box, but I'd like at least to catch an Observe notification which goes nowhere. Is it possible?

**Comment by sbernard31** [comment]
You talk about Californium server, but you say it sets up an observation relation, so I suppose you are using it as a CoAP client. 

In this case with the Californium 2.0.x, you can implement your own [ObservationStore](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/observe/ObservationStore.java) and so persist observation in a persistent store/file.

**Comment by eugene-nikolaev** [comment]
Oh yes, sorry for that confusion.
My server actually is both client and server, it receives requests from embedded devices but can also send request to them. So the embedded devices too.

Thanks, glad to know such store exists - I'll use it after migrating to 2.0.

But is there any workaround for 1.x?

Well, I see for now I could implement an Interceptor, parse message there and decide if it is of a broken relation so start a new observation. An embedded device will have to wait for some time after it has sent an observe relation to receive a new relation (if any).

**Comment by boaks** [comment]
For 1.x californium unfortunately doesn't offer that. FMPOV it would require too many changes, therefore it's done in 2.0.x.

So the only "solution" may be, that you add some kind of persistence to your server, which stores the observed URL and reregister these observes after restart. This also helps to limit "leaks", when notifies are send while your server is down, because reregister means also, that you get the current value. 

When you migrate to 2.0.x, you need to be careful, if you use DTLS, because for coaps, there is an additional issue of the definition of request/response matching according RFC7252, 9.1.2

https://tools.ietf.org/html/rfc7252#section-9.1.2

This would required to save the DTLS session (and connection) also.
There have been a lot of discussion about that, see 

https://www.ietf.org/mail-archive/web/core/current/msg08821.html

So in the end, if you can/are allowed to use a none compliant solution, you may use a different `EndpointContextMatcher`, see javadoc of `EndpointContext` 

https://github.com/eclipse/californium/blob/2.0.x/element-connector/src/main/java/org/eclipse/californium/elements/EndpointContext.java

**Comment by eugene-nikolaev** [comment]
> This would required to save the DTLS session (and connection) also.

This is exactly what I need! The next thing will be to restore the DTLS session.

Thank you all very much!

**Comment by boaks** [comment]
Just to mention:
The DTLS session is one thing to store, but would require a "resumption handshake" from the client (coap-server). The DTLS connection would require to save the epoch and record number also (which is changing on every message).

FMPOV, the most usage of RFC7641 observe/notifies is simple a misdesign! 
If you not want to observe something for couple of minutes which changes the value every couple of seconds, RFC7641 mostly comes with more pain than help.

I would consider to use POST from the client to the server, that's much more natural. The POST must contain all information to process it (see REST), so its easy to restart the server without care about the communication arefacts. You still may configure that using a PUT request from server (then coap-client) to the client (coap-server), but also for the client it's easier to save that PUT, than the communication artefacts as token and DTLS session. The drawbacks are, that you need to know, which PUT is required the trigger that POST. That's system specific and so the client and server must match.

**Comment by eugene-nikolaev** [comment]
This input is quite valuable, thank you very much! I felt that long-living observations could lead to pain but didn’t manage to formulate it in so clear way.
