### ISSUE TITLE
Scope of release 2.0.0 (2018 - deprecated :-) )

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#556]
Dear californians,

we currently plan to release californium 2.0.0 and it seems that we have two options:

1. release with the exchange leaks mentioned in issue #429. These leaks occurs as far as we know, only on "blockwise notifies". There seems to be also some additional rare threading issues in the blockwise layer.

1. release with PR #551, which seems to fix the issue #429, but comes with 4000 lines changed (and potential issues caused by those changes). This removes some synchronization in the blockwise layer to prevent deadlock, but it doesn't solve other threading issues for that blockwise.

Variant 1 we should be able to start the release process within one or two weeks.
For variant 2 a review of PR #551 is required and currently there is no timeline from the reviewer for that.

So any opinions?

**Comment by AlexITC** [comment]
do we really need a release now?

**Comment by boaks** [comment]
The last major release was long ago. 
And we "closed 2.0.0 the feature list" last year.
So I think, we should have a release 2.0.0 soon. 
And then collect the features and issues for the next release.
But let's see, what the users want :-).

**Comment by sbernard31** [comment]
It seems there is not so much urgency/community needs about releasing a 2.0.0 ?

**Comment by sophokles73** [comment]
Based on the sparse feedback and some discussions I had with @boaks , it seems that there is not much need in the community for an imminent 2.0.0 release of Californium.

This has the advantage of giving us more time to address some of the more challenging issues we are still facing around blockwise transfers triggered by notifications :-)

My personal interest in a 2.0.0 release is mainly driven by my intent to get a CoAP protocol adapter for [Eclipse Hono](https://www.eclipse.org/hono) implemented based on Californium. In order to include such an adapter in upcoming Hono releases, we will need to build on top of a *released* version of Cf. So AFAIC we can live with Californium milestones for some time but once we are in a position to release the CoAP protocol adapter as part of Hono, we would definitely be in need of the 2.0.0 release.

**Comment by akansal1** [comment]
@sophokles73 I am interested in COAP adapter in Eclipse Hono, is there any update on status of  this ?

**Comment by boaks** [comment]
the adapter is developed within the hono project. the current PR is based on hono 0.6-M2.
See
https://github.com/eclipse/hono/pull/599

Yesterday I started to update my PR to 0.6 as base, so I will update the PR in the next day..

**Comment by boaks** [comment]
Currently I collect my topics for release 2.0 - 2019. 
When I'm finished, I'll create a new issue :-).

**Comment by boaks** [comment]
Deprecated, replaced with issue #905
