### ISSUE TITLE
token mismatch after 65536 (=2^16) requests/responses

### ISSUE THREAD

**Issue by Endebert** [eclipse/californium#57]
Hi Californium team,

I believe I found a somewhat strange problem inside the californium core.  This was originally discovered after doing performance tests with an application that is based on leshan (See initial issue [here](https://github.com/eclipse/leshan/issues/145)).

I have tried to do some debugging of the core using leshan, and I found out beginning with the 65537th response (i.e. after sending 2^16 responses), `sendResponse` of `org.eclipse.californium.core.network.Matcher` is being called with the wrong exchange object.

The test setup looks as follows: I have a leshan server and client, and the client is registered on the server. I then send http requests to the leshan server, which leads to coap requests being sent to the leshan client, to which the client responds. After 65536 requests, the server is unable to to match the response to the initial request, because the tokens don't match.

To better illustrate the problem, I have added some log prints to `sendRequest`, `sendResponse`, `receiveRequest` and `receiveResponse`. This is what happens around the 65537th request, when I run my test:

Server side:
```
...
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendRequest
WARNING: Sending request with mid KeyMID[20394] and token KeyToken[dc89]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveResponse
WARNING: Received response with mid KeyMID[20394] and token KeyToken[dc89]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendRequest
WARNING: Sending request with mid KeyMID[20395] and token KeyToken[1b502f9c21]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveResponse
WARNING: Received response with mid KeyMID[20395] and token KeyToken[1b502f9c21]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendRequest
WARNING: Sending request with mid KeyMID[20396] and token KeyToken[4dbb3da333b5]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveResponse
WARNING: Received response with mid KeyMID[20396] and token KeyToken[53]
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveResponse
WARNING: Discarding unmatchable piggy-backed response from [/127.0.0.1:57,885]: ACK-2.05   MID=20396, Token=53, OptionSet={"Content-Format":"unknown/1542"}, c6 01 2d 31 32 36 2e 30 
```

Client side:
```
...
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveRequest
WARNING: Received request with mid KeyMID[20394] and token KeyToken[dc89]; exchange hash: 1,904,375,366
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendResponse
WARNING: Sending response with mid KeyMID[20394] and token KeyToken[dc89]; exchange hash: 1,904,375,366
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveRequest
WARNING: Received request with mid KeyMID[20395] and token KeyToken[1b502f9c21]; exchange hash: 740,501,474
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendResponse
WARNING: Sending response with mid KeyMID[20395] and token KeyToken[1b502f9c21]; exchange hash: 740,501,474
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher receiveRequest
WARNING: Received request with mid KeyMID[20396] and token KeyToken[4dbb3da333b5]; exchange hash: 940,539,153
Jun 15, 2016 6:05:47 PM org.eclipse.californium.core.network.Matcher sendResponse
WARNING: Sending response with mid KeyMID[20396] and token KeyToken[53]; exchange hash: 642,583,859
```

As you can see from the log prints, when the client tries to respond to the request with MID `20396`, `sendResponse` is called with the wrong exchange object (as observable by the exchange hashes printed in the log), which leads to the wrong token being used, and the server side is unable to match the response to the initial request.

From this point on, every time the client tries to respond to a request, the wrong exchange object is used.

This test was done using the current master branch of californium.

I hope this information is enough for you to find the source of the problem, since so far, I was unable to.

**Comment by Endebert** [comment]
After further testing and thanks to the feedback of @sbernard31 [in the original issue](https://github.com/eclipse/leshan/issues/145) in the leshan repository, this problem stems from the deduplicator used in californium.

I see that there are two deduplicators to choose from, and based on my test results it seems that the other CropRotation deduplicator works for much longer, but I've also managed to reach its limits.

Now I understand that this is not really a bug in the code, but before closing this issue, if possible I would like to get feedback from you on how to handle this problem. What do you think is best practice in this situation? Obviously I can't disable deduplicators for the performance tests, but what can I do to keep the system stable under heavy load?

Since the deduplication algorithms are based on MIDs of which there are 2^16 possible values, might it be possible to implement a fail-safe in case the maps used by either of those deduplicators reach this size? For example, in the CropRotation deduplicator, the 3 maps used are rotated on a schedule. Two are in use, while the third is cleared. Now in `findPrevious()`, there could be a check of the size of the current maps, so that if both of them reach the max size (i.e. 2^16), the rotation of maps is manually invoked. Or is the catching of duplicate messages for the duration of the exchange lifetime more important than the stability of the system?

Lastly, if there is no solution to keep the system stable under heavy load with any of the two deduplicators, would consider implementing a deduplicator that guarantees stability, or accept a new deduplicator implemented by us? One solution could be an implementation similar to the CropRotation deduplicator, that uses a dynamic amount of maps.

**Comment by sophokles73** [comment]
@Endebert,

thanks for raising this issue. My understanding is that stability is not the issue here (it looks like Californium is working perfectly stable all the time). However, it doesn't seem to work as you had expected it to ;-) AFAIK some of your expectations are justified by the CoAP spec while others are not.
Here's what I think:

On the CoAP server side (the leshan client) Californium seems to actually work as designed, i.e. it (correctly) recognizes incoming CON requests using an MID it has already received (and processed) within the last EXCHANGE_LIFETIME secs as duplicates and therefore simply returns the response sent for the previous request with the same MID. This is what you see in your log file for MID 20396.
We could think about altering the duplicate detection to also include the token used in the CON request but this is kind of *thin ice* as this behavior is not covered (sanctioned) by the spec. In fact, the spec is very clear regarding the fact that such requests are to be considered duplicates...

However, I do not consider this a stability issue but instead a case of *out-of-scope expectations*. In your test case the CoAP server (representing the device side) is implemented as a software component running on multi-core hardware which is not very typical for CoAP's intended use-case of constrained devices. It doesn't seem realistic to me that the device should support the processing of several thousand requests/sec. The other direction, on the other hand, makes total sense to me. The leshan server should of course be able to process thousands of CoAP requests (from thousands of clients/devices) per sec and it should also be able to send thousands of CoAP requests to (thousands of) clients/devices per sec. Here's where Californium seems to have an issue. Californium currently uses an overly simplistic approach to generating MIDs (which is to simply increment and wrap a global counter). As @sbernard31 already pointed out this is in compliance with the spec. However, Californium currently doesn't seem to verify whether the MID at hand has already been used in an unacknowledged CON during the last EXCHANGE_LIFETIME secs and therefore simply sends out the request (re-)using the MID (with a new token). I consider this a bug which we need to fix. We should also improve MID generation by scoping the MID counter to endpoints, thus being able to send the full 250 CONs per sec to each individual endpoint.

So, what does this mean for your performance tests? You will probably not be able to test leshan's (outbound) request/response throughput the way you intended to. This is mainly due to the fact that you are testing a scenario that CoAP was not designed for (i.e. exchanging thousands of messages per sec between a single pair of endpoints). You way implement your own deduplicator which simply returns false for every MID received (effectively turning duplicate detection off) for conducting your test. However, I do not think that the results you get out of this will have any relevance for real world scenarios. If your test is only about testing leshan's server component's max (i.e. theoretical) throughput you might be better off with running the test in a single VM, using a mock implementation of `LwM2mRequestSender` ...

**Comment by sophokles73** [comment]
BTW this seems to be related to #30 as well ...

**Comment by Endebert** [comment]
@sophokles73 

Thank you very much for you detailed response. Indeed it seems we are trying to use coap for purposes it was not designed for. We will discuss this internally to figure out how to proceed.

You may close this issue if you'd like, or keep it open to track the issue about MID reusage.

Again, thank you very much so far.

**Comment by sophokles73** [comment]
I have opened #63 for tracking the problem of erroneous MID reusage ...
