### ISSUE TITLE
Adding Curve25519 Elliptical curve key to scandium

### ISSUE THREAD

**Issue by vikram919** [eclipse/californium#595]
@boaks 
Hello,
Can we configure DTLS scandium to add Elliptical Curve25519 keys ? as single key can be used for DSA as well as derving secret key using ECDH algorithm. 
Thank you!

**Comment by boaks** [comment]
> Can we configure DTLS scandium to add Elliptical Curve25519 keys ?

Depends on "we" and "configure" :-).

If "we" (excluding me) is preparing a PR and that passes the CQ check (mandatory for crypto), yes we can add it scandium and make it available to be used by "configuration".

**Comment by vikram919** [comment]
> If "we" (excluding me) is preparing a PR

yes, I can do that. But californium need to consider adding an extra dependency for generating X25519 ECDH keys.

https://tools.ietf.org/html/draft-ietf-tls-tls13-28 TLS 1.3 [Section 4.2.7](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#section-4.2.7)  draft discuss on adding supported curve extensions to perform ECDH key exchange using X22519 algorithm.

**Comment by boaks** [comment]
If the "extra dependency" complies to the eclipse rules (clear authorship, license), then an additional dependency should not be a show stopper :-).

**Comment by boaks** [comment]
@vikram919 

Any progress with the PR? Do you actual work on this?

**Comment by vikram919** [comment]
@boaks 
I found no library that provide PKCS8 public key representation of X25519 DH keys, bouncy castle provide X25519 keys in raw bytes to perform DH here is the example https://github.com/bcgit/bc-java/blob/master/core/src/test/java/org/bouncycastle/math/ec/rfc7748/test/X25519Test.java  and library: 'net.i2p.crypto:eddsa:0.3.0' https://github.com/str4d/ed25519-java  provide ed25519 keys in native java encoding.

I would like to know, can we add ECDH keys in bytes rather than PKCS8 encoded PublicKey  at client and server key exchange?

**Comment by boaks** [comment]
Unfortunately, all eclipse CQ for "bouncycastle" I found have been either rejected or are withdrawn.
So I'm not sure, that creating a new CQ for "bouncycastle" will be successful.

I'm currently not able to spent time in understanding X25519 and so I can't answer the related questions.

Only in general, AFAIK: 
Both DTLS asymetric variants, RPK (raw public key) and X.509, are based on using the public key in ASN.1 DER encoded format. So that's a fundamental requirement. That ASN.1 DER public key contains an OID for the key type (see https://tools.ietf.org/html/rfc5280#section-4.1.2.7). 

So at least, that encoding must must be provided.

Then there are two use-case:
A. convert the java `PublicKey` implementation of the X25519 into that ASN.1 DER
B. convert the ASN.1 DER into a X25519 java `PublicKey` implementation

A depends mainly on the implementation provided in the PR
B. requires several changes (and tests, tests ...). AFAIK I see, that 
https://github.com/eclipse/californium/blob/2.0.x/element-connector/src/main/java/org/eclipse/californium/elements/util/Asn1DerDecoder.java must be extended and usages of `KeyFactory.generatePublic()` must be analysed and potentially adjusted.

If this all could be done successful right now, or, if you hit serious issues, is out of my knowledge.

**Comment by vikram919** [comment]
@boaks 
Thanks for the information.
https://tools.ietf.org/html/draft-ietf-curdle-pkix-10 
It is a draft that explains how to encode X25519 and Ed25519 keys in ASN.1 format.

**Comment by vikram919** [comment]
@boaks  
First let me implement PreSharedKey and PskKeyExchangeModes Extensions that support psk only and psk_de modes of psk, as discussed in https://github.com/eclipse/californium/issues/656
and I will see about this enhancement.

**Comment by vikram919** [comment]
@boaks 
More information https://bugs.openjdk.java.net/browse/JDK-8189806 java jdk 11 pre release provide X25519 and X448 keys as KeyExchange Algorithms

**Comment by boaks** [comment]
ECDHE is already implemented when java 11 is used.
PR #1395 will add EdDSA support for either java 15, or java 11 and the external library `net.i2p.crypto.eddsa`.

**Comment by boaks** [comment]
PR #1395 is merged.
