### ISSUE TITLE
Are we currently supporting OAuth2  with CoAP

### ISSUE THREAD

**Issue by GPrathap** [eclipse/californium#65]
I have read a little bit about these[1-2].  It seems like CoAP is to be supported OAuth2. Is this feature in progress or on the roadmap. If you like I would like to take an initiate in order to develop this feature. 
1. https://tools.ietf.org/html/draft-tschofenig-ace-oauth-bt-00
2. https://datatracker.ietf.org/doc/draft-selander-ace-object-security/?include_text=1

**Comment by sophokles73** [comment]
Hi @GPrathap,

sorry for the delay, I was very busy with some other projects and with integrating Joe's PR for adding TCP support.
Coming back to your question: we currently have no plans for implementing this ourselves (simply because none of us currently seems to have a use case for it at hand).
However, this should not stop you from implementing support for it and contributing it. Since both of the referenced documents are drafts only, I would, however, consider them *experimental* only, though. I would therefore suggest that you do the work (if you are still motivated) on the 2.0.x branch (which also contains some other experimental features) ...

**Comment by GPrathap** [comment]
Sure I would like to contribute on this. So once initial plain is made will send explaining what would be the my approach on this.
