### ISSUE TITLE
EC Diffie Hellman key exchange authenticated with PSK?

### ISSUE THREAD

**Issue by vikram919** [eclipse/californium#656]
Currently 
```java
TLS_PSK_WITH_AES_128_CBC_SHA256
TLS_PSK_WITH_AES_128_CCM_8_SHA256 
```
are the two cipher suits that are available for PSK mode.
Can I know why 
```java
TLS_DHE_PSK_WITH_AES_128_CBC_SHA 
TLS_DHE_PSK_WITH_AES_128_CCM8_SHA
``` 
are not supported by californium project, is it a plan for future releases ?

**Comment by sophokles73** [comment]
IIRC we focused on implementing the cipher suites that are/were mandatory for LWM2M 1.0. Since the DHE based PSK cipheres were not mandatory, we did not implement them.

However, there seems to be a need for PSK based ciphers that provide perfect forward secrecy in order to address the problem of plaintext handshake messages in DTLS 1.2. So, implementing the ciphers defined in [1] could be a valuable addition. Personally, I would be more than happy to accept a PR for it. However, it would probably require some refactoring in Scandium first, in order to more cleanly separate the DHE related code from the particular cipher(s).

[1] https://tools.ietf.org/html/rfc4279#section-3

**Comment by vikram919** [comment]
@sophokles73 
> Personally, I would be more than happy to accept a PR for it.

I am glad to work on it.

> However, it would probably require some refactoring in Scandium first, in order to more cleanly separate the DHE related code from the particular cipher(s)

Thanks for the information, I will do that.

**Comment by vikram919** [comment]
https://github.com/eclipse/californium/pull/658
