### ISSUE TITLE
Examples of implementing Get and Post using Cf library

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#667]
We need to implement a CoAP server using Cf library. 
Can we get some sample reference code where methods like GET  and POST are already implemented (as per RFC7252) which can help in reducing our development time (i.e. will eliminate starting from scratch)? 
Thanks.

**Comment by boaks** [comment]
you may find several examples in "demo-apps", especially in "cf-plugtest-server\src\main\java\org\eclipse\californium\plugtests\resources" you see many resource implementations.

But I'm not really sure, what the target of your question is? For Californium/CoAP GET and POST are just "Methods", they are mapped to calls of CoapResource.handleGET and CoapResource.handlePOST and the expected behaviour of your overriding implementation of these methods is define in RFC7252 (Response codes etc.) https://tools.ietf.org/html/rfc7252#section-5.8

**Comment by jas-singh14** [comment]
@boaks , thanks for your inputs.
