### ISSUE TITLE
My first notification was dropped

### ISSUE THREAD

**Issue by JavaProgrammerLB** [eclipse/californium#673]
### My first notification was dropped 
- the onLoad(CoapResponse response) was invoked when client received the ACK of Observe request from Server
- then CoapClient drop the first NON notification with payload
- then onLoad handle the second notification successful
- the third notification successful... 
### I want to know how can I catch the first notification
- In my code I use **coapClient.useCons();** to expect load the first notification but the ack

My Observe:
![observe](https://user-images.githubusercontent.com/3973419/41693522-4358f496-7538-11e8-89b5-5c7aabffc273.jpg)

After My code run:
![now](https://user-images.githubusercontent.com/3973419/41694068-f38368f4-753a-11e8-8f6d-6803dbe813c9.jpg)

Californium log:
![log](https://user-images.githubusercontent.com/3973419/41693569-89c39f62-7538-11e8-9e79-79d761812200.png)

tcpdump packages:
![image](https://user-images.githubusercontent.com/3973419/41694356-8314ccf0-753c-11e8-9627-e7882b839f73.png)

```
CoapClient coapClient = new CoapClient();
coapClient.setURI("http://*.*.*.*:5683/t/d");
coapClient.useCons();
coapClient.observe(new ObserveHandler());
```

I use: <version>2.0.0-M6</version>

tcpdump cap file:
[devicebus-nbiot-access4.cap.zip](https://github.com/eclipse/californium/files/2121799/devicebus-nbiot-access4.cap.zip)

**Comment by boaks** [comment]
What is your client implementation?

The ACK (first response) contains a OBSERVE 0, response code 2.05 Content, but no payload !!!! 
The fist NON (MID: 7510) also contains OBSERVE 0, response code 2.05 Content, an payload  
The second NON (MID: 7513) also contains OBSERVE 3, response code 2.05 Content, an payload

According https://tools.ietf.org/html/rfc7641#section-3.4, the first NON is not newer than the ACK.
Therefore the NON is filtered out!

FMPOV, your client implementation is not proper working (I hope, it's not californium .-) ) 
It doesn't prepare the observe option of the ACK response proper not does it send the proper first payload in the response.

See also 
https://tools.ietf.org/html/rfc7641#appendix-A.1

The response to GET has observe 0 and payload, the next notification has observe 9 (and payload), and then 16 (and payload).
So that observe option sequence will work. It takes the first payload from the response and then the payload of the following notifies.

**Comment by JavaProgrammerLB** [comment]
@boaks thanks for your answer，
- I get your point that the observe option in response order the notification.
- my client implementation is Californium 2.0.0-M6.
- Can you give me some suggestion to fix the issue: ignore the ack, **handle the notification**

**Comment by boaks** [comment]
> What is your client implementation?

Sorry, I was wrong, the coap server implementation is important, it generates the suspicious ACK.
If it is also californium 2.0.0-M6, I would appreciate, if you could provide some informations about the examples your using.

**Comment by boaks** [comment]
> Can you give me some suggestion to fix the issue: ignore the ack, handle the notification

Fix the server to sent proper ACK responses, or really just a plain ACK. But this depends on your servers possibilities.

**Comment by JavaProgrammerLB** [comment]
@boaks thank you very much.
The Observe server is run in our customer's IoT device, maybe implement in C.

**Comment by JavaProgrammerLB** [comment]
@boaks thank you a lot.

- In my case, I can't modify the Observe server's code logic.

- I try to add an if block in ObserveNotificationOrderer.java and modify some code to pass the unit test, which is an informality method to solved my problem.

ObserveNotificationOrderer.java:
![image](https://user-images.githubusercontent.com/3973419/41756498-74786764-760f-11e8-8e44-f39ab5299c81.png)
