### ISSUE TITLE
Why reregistration is forced for every observe relation?

### ISSUE THREAD

**Issue by KMax** [eclipse/californium#70]
As I can see from my experiments and the source code, if the server doesn't set `Max-Age` header each observe relation is forced to be reregistered once a minute. Why is that? And how can I disable it?

At [CoapClient:1045](https://github.com/eclipse/californium/blob/295217ddeb7e53089ae23571946b6d7a0b0dd8d7/californium-core/src/main/java/org/eclipse/californium/core/CoapClient.java#L1045) the `prepareReregistration` method is called which in its turn creates (Cf. [CoapObserveRelation:192](https://github.com/eclipse/californium/blob/295217ddeb7e53089ae23571946b6d7a0b0dd8d7/californium-core/src/main/java/org/eclipse/californium/core/CoapObserveRelation.java#L192)) a Runnable executing `reregister()` in 60+2 seconds after the last delivery, because by default the `Max-Age` is equal to 60 sec.

**Comment by KMax** [comment]
This what the [RFC 7641 3.3.1 Freshness](https://tools.ietf.org/html/rfc7641#section-3.3.1) says:

```
It is RECOMMENDED that the client does not issue 
the request while it still has a fresh notification/response 
for the resource in its cache.
```

I understand that `RECOMMENDED` is not the same as `MUST`, but anyway it really useful to check whether a new response was received before sending the reregisteration request.

**Comment by sophokles73** [comment]
HI @KMax,

the `CoapClient` sets a timer based on the most recently received response's `MAX_AGE` option (60 secs if not explicitly set on the response) to re-establish an observation in order to compensate for a server having crashed or *forgotten* about the observation. The *re-establishing* request, however, is **only** sent out to the server if no further response (notification) arrives before the previous response's `MAX_AGE' has expired (+ 2 secs). This is made sure in [CoapObserveRelation.java:185](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/CoapObserveRelation.java#L185) by canceling the previous *re-establishment* job.
