### ISSUE TITLE
Make socket in connector accessible

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#704]
I would like to access to socket in connector. (add or make getter public)

It will be use for tests or prototyping. (example of use case sending UDP keep Alive)

Any objection ?

**Comment by boaks** [comment]
I would prefer to add a receive listener and raw send.

For the mid future, I would prefer to use plain connector for dtls instead of a socket.
This would make it easier to additionally use sockets with nio async communication to improve the possible number of connectors without the requirement of separate receive threads.

**Comment by sbernard31** [comment]
I only need a raw send is it ok if I just add this ?

**Comment by boaks** [comment]
sure.

**Comment by boaks** [comment]
I guess, it's not longer required for 
https://github.com/eclipse/leshan/issues/542

Or do you still think, it's a good idea?

**Comment by boaks** [comment]
OK, then go for it.

**Comment by sbernard31** [comment]
Finally, I find another way for Leshan tests. So I close this issue.

Don't be surprised, if I reopen it later :wink:

**Comment by lhotari** [comment]
I would also need this feature. I'm currently using reflection to access the socket. The use case is for sending empty UDP packets from the server to clients to keep UDP "streams" active in firewalls and routers between the server and the client. 

As a side note, there is a glitch with this type of keep-alive solution. Some embedded devices use modem chips with an UDP IP stack controlled by AT commands over a serial interface. Some modem chips have implemented UDP handling in a way that they terminate the UDP stream when they receive an empty UDP packet and there is no way to configure this behaviour in the modem chips. To support these type of devices, a different type of keep-alive solution must be used. DTLS clients should ignore invalid records ([RFC6347: 4.1.2.7.  Handling Invalid Records](https://tools.ietf.org/html/rfc6347#section-4.1.2.7)), but I agree it's not a beautiful solution . 
One alternative is to send a single byte in the UDP packet or use the more heavy-weight "COAP ping".

I'm looking forward that [IETF Draft: DTLS Connection ID](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls-connection-id/) spec would help with the NAT problems so that a keepalive packet solution wouldn't be needed at all. That will take time until that solution is a RFC and gets implemented in Californium and actual devices, so that's why I'm interested in the keep-alive solution as a temporary mitigation.

I'd like to replace my current reflection based hack to send keepalive packets. One solution is where the DTLSConnector class would have to be subclassed to get low-level access. I'd be happy with a solution where the "sendNextDatagramOverNetwork" method in DTLSConnector would be protected instead of being private. I don't specifically need access to the socket itself, but perhaps "getSocket" could be protected too. Would it be possible to make "sendNextDatagramOverNetwork" and "getSocket" protected in DTLSConnector?

**Comment by sbernard31** [comment]
Personally, I'm not again making "sendNextDatagramOverNetwork" and "getSocket" public with javadoc warning.

@boaks explain above its concern about exposing `getSocket`, so maybe if you don't really need it we can just start with `sendNextDatagramOverNetwork`?

**Comment by lhotari** [comment]
Thanks for the views on the topic @boaks & @sbernard31. Changing `sendNextDatagramOverNetwork` access from `private` to `protected` instead of exposing it with `public` access would help keeping the API limited. One would have to subclass DTLSConnector to be able to access and make use of it.

The raw receive & send API sounds great, but perhaps complicates things unnecessarily. I guess there are other use cases for it which justify having a complete API?

**Comment by boaks** [comment]
> Changing `sendNextDatagramOverNetwork` access from `private` to `protected` instead of exposing it with public access would help keeping the API limited.

Sounds good. As long as the other use-cases are unclear (or not reported), I think, that 's a good solution.

**Comment by sbernard31** [comment]
@lhotari, I made this little change (commit 3ff2636)
It should be available in the next release, you will soon be able to remove you reflection code ^^

**Comment by lhotari** [comment]
Thanks @sbernard31 , LGTM
