### ISSUE TITLE
Cluster of Scandium servers

### ISSUE THREAD

**Issue by mb590721** [eclipse/californium#771]
Hi,

We are currently using Scandium on a project which and we have established a LB (Load Balancer) which keep track of the IP address to forward the request to the same server each time. Devices connecting to our cloud are sleeping (for battery purpose) most of the time so the server is a slave and never contact them first.

We face a problem when we are updating the application. When we shut down one of the server behind the LB, requests are forwaded to another server which ignore the request because it isn't aware of this dtls session and can't decrypt the request.

I would like to know if there is there a way to shared the `InMemoryDtlsStore` accross the cluster (with an Hazelcast or other for example) ?
Is it a good way to make things ?
Is there another way to do it ? (Server asking for handshake on request which it can't decrypt ?)

At a more general level, have someone already work on a cluster of Scandium servers ?

We use the 2.0.0-M1 version of Californium, Scandium etc.. but if a feature is available in another version we may be able to upgrade to it.

Thanks a lot and hope it's enough comprehensible !

**Comment by mb590721** [comment]
I just saw that in the `org.eclipse.californium.scandium.DTLSConnector` class the `processApplicationDataRecord(Record record)` method just log a message to say that a record from a peer without session was received.

If I want to override this to launch a new handshake (if possible) or a dedicated error I need to override the `start()` and `restart()` method which don't seems a good way to do things since i would have to copy/past a lot of code. Any thoughts about that ?

**Comment by sbernard31** [comment]
> I would like to know if there is there a way to shared the InMemoryDtlsStore accross the cluster (with an Hazelcast or other for example) ?

There is no way in scandium to share/persist connection.

> Is it a good way to make things ?

A good question, I asked myself too. Currently, we are far to provide a way to share connection.
And I'm not sure this will work with your use case. All your cluster instance should have been see with the same ip address/port at client side, is it the case ? 

> Is there another way to do it ? (Server asking for handshake on request which it can't decrypt ?)

The only solution I can see is to make a new handshake each time your device wakes up.
It could try to do an abbreviated handshake to save some bandwidth and CPU. (which will fallback on fullhandshake if session is not handle by the server)

 After that an optimization could be to try to share session between cluster instance. Look at SessionCache and ClientSessionCache (in 2.0.0-M12) to maximize the number of abbreviated handshake.

 In a general way, when you device request timeout, server probably lost the connection and just ignore your packet, so you should rehandshake.
 
Other clues which require to implements new feature in scandium :
- not really convinced but maybe [heartbeat extension](https://tools.ietf.org/html/rfc6520) could help to know quickly if the connection is lost.
- [dtls connection id](https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-01) is very promising for cluster because connection is no more identify by address/port but with an id and so you could imagine to make the loadbalancing using this connection id (see http://archive.linuxvirtualserver.org/html/lvs-users/2017-10/msg00004.html)

As your problem is very similar to LWM2M queue mode, I just let a last link about that :https://github.com/eclipse/leshan/wiki/Using-Leshan-server-in-a-cluster

**Comment by boaks** [comment]
Just for the future:
Does your client support the "connection id" (https://tools.ietf.org/pdf/draft-ietf-tls-dtls-connection-id-02.pdf)?

**Comment by mb590721** [comment]
I asked to the team in charge of the client development, they will check that as soon as they can. In the meantime I can tell you that we use the 1.2 version of DTLS so I think the client should support the "connection id".

**Comment by boaks** [comment]
Just to be more precise:

> **for the future**

means, it's currently also not implemented in scandium ;-(. 
Therefore I asked. Once upon a time, it may be implemented. 
But for my self it has no high priority. And currently not too many clients seems to support it.
Just if you plan for it, let us know. May be, we change the prios.
