### ISSUE TITLE
Regarding observe notification

### ISSUE THREAD

**Issue by jjh1jjh** [eclipse/californium#825]
Hi, there
I'm trying to transfer piggy-backed response for CoAP Observe notification. Coap server ignores the piggy-backed response when receiving the ack. The log is like the following.
>>> INFO [Matcher]: Ignoring unmatchable piggy-backed response from ...
I think coap server transfers observe notification using response. I logged it using MessageInterceptor. When coap server transfers observe notification, the sendResponse function is called. That means, Match class doesn't take case the message for piggy-backed response. So, my query is why coap server transfers observe notification using response. I'm not able to find any related spec for this issue. Please, check it.
Thanks and Regards,
Jang.

**Comment by boaks** [comment]
I'm not sure, do you use 1.0.n?

And your logging message is from Matcher.java, line 400, "Ignoring unmatchable piggy-backed response"? That is caused by a received piggybacked response (ACK-message), but there is no matching request (exchange)  for that ACK.

That rise the question, which implementation do you use on the peer, which sends that ACK?
Could you provide a wireshark capture of your message exchanges?

**Comment by boaks** [comment]
> When observe notification is transferred to CoAP Client, sendResponse function in Matcher.java is called (I checked it using MessageInterceptor interface).

> I'm developing CoAP Client side(not using californium library)

That seems to be wired to me! I guess:
You use a device (lwm2m?) client, which is using a c-implementation.
And a cloud-server, which is using californium (leshan?).
For CoAP, the device may be a coap-client and -server, depending on the exchanged messages. That's also true for the cloud-server, it may be both, coap-client and coap-server. That's one feature of CoAP, it's simple to exchange the role and direction of the message flow. 
In LWM2M, using observe/notify, your cloud-server is the coap-client (it sends the request, in hat case the observe-request), and the device is the coap-server (it send the response and the notify-responses).

So, what you should see:
the californium coap-client should sendRequest and receiveResponse (notifies are simply received as responses, they are just a special kind of responses).
the californium coap-server should receiveRequest and sendResponse (notifies are simply send as responses, they are just a special kind of responses)..
Therefore:
If cloud-server's coap-client calls sendResponse, then it is not the coap-client, it is the coap-server, which response to a request. Californium offers a MessageTracer, may be you can use it to create logs of your exchanges? Or, because it usually is the best an easiest,  provide the wireshark capture!

With you description, I'm not sure, what happens in your case. 
Alternatively, you may check, if this happens also in californium 2.0.x (2.0.0-SNAPSHOT or 2.0.0-M12).

**Comment by jjh1jjh** [comment]
Thanks for your supports. I attached wireshark capture, and explaining the details.
[coap_observe_ack_20181217.zip](https://github.com/eclipse/californium/files/2684960/coap_observe_ack_20181217.zip)

- CoAP Client: 192.168.0.2, CoAP Server: 192.168.0.3
- Packet#1,2: In order to register observe coap client is checking the uri.(You can ignore it)
- Packet#3,4: Register observe relation between coap client and server.
- Packet#5,7,9,11,13: Observe notification from CoAP Server. After 30 sec(Packet#4), CoAP server transfers observe notification. At this time, sendResponse function is called.
- Packet#6,8,10,13,14: Ack message for observe notification from CoAP Client. This ack message includes simple text, "Observe ACK with payload".

Even if CoAP Server received the ack(#6,8,10,13,14) message from coap client, CoAP server is ignoring this message. It think I already explained the cause of this issue.

**Comment by boaks** [comment]
> CoAP Client: 192.168.0.2

So that's californium?

> CoAP Server: 192.168.0.3

that's a different implementation?

> Packet#6,8,10,13,14: Ack message for observe notification from CoAP Client. This ack message includes simple text, "Observe ACK with payload".

So theses ACK's are from the californium CoAP client? 
That's really mystic to me. A ACK for a CON response (notify) must be empty. 
How do you provide the payload "Observe ACK with payload"? Can you provide the snippet for that?

**Comment by boaks** [comment]
My assumption:
Though the ACK for the CON response/notify is a "piggybacked" and not "empty", it breaks the exchange keeping. But I'm really wondering, why it is piggybacked and not just empty.

**Comment by jjh1jjh** [comment]
Dear boaks,
I'm sorry to make you confused. CoAP client is not californium. CoAP Server is californium. Now, I'm just checking ACK can include payload for observe notification.
I want to know why the observe notification is CON response (As you mentioned before, A ACK for a CON response (notify) must be empty). I think the observe notification should be CON request. Additionally, I'm not able to find any relevant spec.

**Comment by boaks** [comment]
Thanks!
So let me show, how I think it should be:
The client sends a CON GET observer request (3, pass)
The server response with a piggybacked ACK (4, pass, even if I wonder, why the payload is empty.)
The server notifies with a CON response (5, pass, you may setup your CoapResource to use NON, but in general this should work).
The client ACK the CON response, but that ACK must be empty. (6, broken by none empty ACK).
  
> I think the observe notification should be CON request. 

No, notifies are responses.

> Additionally, I'm not able to find any relevant spec.
Sorry, you mentioned that earlier, but I missed it.

https://tools.ietf.org/html/rfc7252

Basic specification, including message type, CON, NON, ACK, and RST, and request/response, including separate and piggypacked in 
https://tools.ietf.org/html/rfc7252#section-5.2.

https://tools.ietf.org/html/rfc7641

Observe/Notify. Notifies are just special multiple responses.

So, if the notify is a CON response, then 
https://tools.ietf.org/html/rfc7252#section-5.2.2 says:

> If the server then sends a Confirmable response, the client's
> Acknowledgement to that response MUST also be an Empty message (one
> that carries neither a request nor a response). 

That's the violation.

**Comment by boaks** [comment]
If you want to check, if NON notifies are working, you may use `CoapResource.setObserveType` with `Type.NON`.

**Comment by boaks** [comment]
And consider to use the 2.0.0-M12 to check your interoperability.

**Comment by jjh1jjh** [comment]
Thanks for your supports! I understand what you are saying.
