### ISSUE TITLE
how create scenario wsn node sensor / server cloud

### ISSUE THREAD

**Issue by jabberimaher** [eclipse/californium#842]
Hi,
Please  i want to create scenario wsn with californium : a node sensor would to authenticate with a cloud server and i want  measure the consumption energy of the sensor and the needed time of authentication.
best regards

**Comment by boaks** [comment]
Energy consumption:
in my experience the most "device platforms" don't include "commands" to measure energy. You may use physical  tools (e.g. multi-meter or what ever fits for you) to measure that.

Time:
To measure times is very common. It should be easy to find, how time could be measured.

**Comment by jabberimaher** [comment]
if i understood your suggestion, i need to connect a sensor to my computer and configure it with californium, then i measure the energy by a physical tool, i thought californium generates results like other simulators like that contiki os and omnet ++.
so how to connect and configure a sensor node to californium.
best regards

**Comment by boaks** [comment]
Californium is no simulator! It's a java library, implementing CoAP (RFC7252) and DTLS (RFC6347). 
If you have a "sensor", which is able to communicate using CoAP and DTLS, you may use that sensor to send CoAP messages over DTLS to a host running an application using californium. 
Californium comes also with a collection of demo-apps, e.g. "cf-secure". This contains a java coap-client and coap-server and they can exchange coap-messages using DTLS.
If in you analysis the sensor is the client (and PUT/POST it's data) or the server and the data is fetched with GET, depends on you. Both is possible.
I'm not sure, may be you talk to your supervisor and show him, that you can run the demo-apps. Maybe she/he has a idea for you to continue.

**Comment by jabberimaher** [comment]
Professor from your wide experience, I try to test some authentication schemes including dtls, can I use the dtls implementation library to test another authentication scheme that is based for example on the login and password ...
if not it is better to look for another tool to save time.
i am very very grateful for your help and advice
thank you for your patience

**Comment by boaks** [comment]
> I try to test some authentication schemes including dtls, can I use the dtls implementation library to test another authentication scheme that is based for example on the login and password ...

You need detailed knowledge of the used authentication schemes.
And you may need to be able to implement the missing stuff based on your knowledge in java.

(D)TLS offers, what is specified. And MDA is not a part of (D)TLS.  (D)TLS offers PSK ciphersuites, and certifikate ciphersuites. If PSK doesn't fulfill your requirements for "login and password" (why ever), you may also use a certificate ciphersuite without client authentication and then implement a login and password over that on your own.

Since some months, the ri.se has spent californium a OSCORE implementation (see oscore-cf). That offers you also a kind of authentication (but I'm the wrong person to be asked about that).

But in fact, this all requires, that you implement something in java on your own.

> if not it is better to look for another tool to save time.

I'm not sure, if you can find something ready, that matches your requirements "out of the box".
Therefore I proposed, that you present your "so-far" results and experience to your supervisor.

> your wide experience
Energy- and time-consumption in crypto technic could be classified into two groups:

- asymmetric crypt functions with a very high consumption of "time & energy" (heavy) (e.g. RSA, ECDSA, ECDHE)
- simple function (symmetric crypt functions or hash) with low consumption of "time & energy" (light) (e.g. AES, SHA)

There are also differences within these classes (e.g. ECC based functions are faster than RSA), but the most benefit could be achieved selecting "hardware support" (e.g. using a mikro-controller with ECC support), but that's out of scope of a java implementation. 
Therefore it's up to your supervisor to define the scope of your analysis. With java you may get results, which are very different to results using mikro-controller with crypto hardware. 

Though the consumption (and security features) of these two classes are very different, (D)TLS introduces some ideas to benefit from the security features of the heavy functions but use the light function for the most stuff. (D)TLS achieves this, if the intended usage is the exchange of multiple messages between two peers. For that, the peer's establish a common security context, which is then be used to securely exchange messages. That is called a "handshake". (D)TLS only uses heavy functions in the handshake and offers even handshakes using only light function (but with a lower resulting security). The payload messages itself are always using light functions only. With that, your results will depend hard on the number of handshakes compared to the number of payload messages. So, also for that, you will need some assumptions from your supervisor.

Last comment:
To reduce the number of handshakes for DTLS, some extensions are discussed. With that, it may get "cheaper".
And a hint, what others do to measure the power consumption:
https://raspi.tv/2018/how-much-power-does-raspberry-pi-3b-use-power-measurements
