### ISSUE TITLE
For LWM2M 1.1 support : Support for Coap over TLS and Coap over SMS

### ISSUE THREAD

**Issue by sgoyaldel** [eclipse/californium#881]
# Please providing basic issue information

Issues may be answered much faster, if you provide more details ahead!

* branch your faced the issue. Currently 
   * 1.0 is the release, 
   * 1.1 is the master, 
   * and 2.0 is the development branch
* If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
  commit your using
* If your issue is related to your own snippet, please provide that
* If you have logs, please provide them
* If you have tcpdump captures (wireshark), please provide them.

**Comment by sbernard31** [comment]
When you say OMA 1.1, I suppose you are talking about LWM2M v1.1 ?

Californium is a CoAP implementation and not a LWM2M implementation.

LWM2M is based on CoAP and so maybe there is missing feature in Californium needed to implement LWM2M v1.1 features. I don't know the LWM2M 1.1 specification enough to say what is missing.

Anyway, you are talking about **Observe-Composite** and **Cancel Observation-Composite**, those are LWM2M feature.

Reading quickly the specification, I didn't see what is missing in Californium 2.0.0-M13 to implement those features.

So could you be more precise ? Which CoAP feature is missing ?
By the way you could provide a real issue message instead of the default one which encourages you to **provide basic issue information** :smile:
(You can edit your message if you want)

**Comment by sgoyaldel** [comment]
Sorry for this. I have change the subject.
Basically, i want to enquire about , OSCORE, Coap over TLS for Blockwise transfer, copa over SMS support

**Comment by sbernard31** [comment]
So this is pretty much the same issue than #863.
