### ISSUE TITLE
Set Reliability layer parameters like ACK_TIMEOUT, ACK_RANDOM_FACTOR dynamically for every down link request.

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#962]
Hi ,

Californium Version  : 2.0.0-M14. Leshan leshan-1.0.0-M11.

I have a requirement to change the re-transmission timer based on the device ack time .
Is there any way to set re-transmission timer factors like ACK_TIMEOUT, ACK_RANDOM_FACTOR dynamically while framing downlink request?

Thanks,
Madhu.

**Comment by boaks** [comment]
That's not implemented. If you want to patch it experimentally, you may add the fields to the `Request` and adapt `ReliabilityLayer.updateRetransmissionTimeout`.

If you use DTLS it may be harder, because it's not that easy to find out, which device is communicating with you.

**Comment by madhushreegc** [comment]
ok. Thank you.

**Comment by boaks** [comment]
If possible a, a contribution would be welcome :-).

**Comment by madhushreegc** [comment]
Sure.

**Comment by boaks** [comment]
See PR #1069 .

**Comment by boaks** [comment]
Solved with PR #1077

**Comment by madhushreegc** [comment]
Thank you for making reliability layer as configurable . 

I have a question on EXCHANGE_LIFETIME attribute . This value is calculated based on EXCHANGE_LIFETIME = ACK_TIMEOUT * (2^MAX_RETRANSMIT - 1) * ACK_RANDOM_FACTOR + 2 * MAX_LATENCY + PROCESSING_DELAY .

How EXCHANGE_LIFETIME value is considered for clean up now?  Is it also configurable for downlink?

**Comment by boaks** [comment]
> I have a question on EXCHANGE_LIFETIME attribute . This value is calculated based on EXCHANGE_LIFETIME = ACK_TIMEOUT * (2^MAX_RETRANSMIT - 1) * ACK_RANDOM_FACTOR + 2 * MAX_LATENCY + PROCESSING_DELAY .

In californium the `EXCHANGE_LIFETIME` is configured, it's not calculated out of the others.
And it's not include in the `ReliabilityLayerParameters`. 

It's currently used as default request timeout by the `CoapClient` for synchronous request. But single block request may timeout earlier or later by these `ReliabilityLayerParameters`. If  later, then a larger timeout may be configured for that `CoapClient`.

The main use of the `EXCHANGE_LIFETIME` is the deduplication. It prevents the MID `MessageIdTracker` from reusing the MID too early (message sender), and as timeout for the deduplicator (message receiver). Especially the usage as timeout for the deduplicator is challenging, because in fact it depends on the `ReliabilityLayerParameters` of the other peer!

**Comment by madhushreegc** [comment]
You said 
In californium the EXCHANGE_LIFETIME is configured, it's not calculated out of the others.

What is the configured value in Californium used in deduplication. Is it configurable?

**Comment by madhushreegc** [comment]
Understood . Thanks a lot .

**Comment by boaks** [comment]
Your welcome. 
Just to mention: in my experience, the 100s processing delay + the time for sending the response back creates a wide range, so that with adapting the parameter (not to much) on the one side without adapting them on the other side, the deduplication still works good enough.

**Comment by madhushreegc** [comment]
Yes . Thank you for your detailed explanation.

**Comment by madhushreegc** [comment]
Californium ReliabilityLayerParameters is integrated with Leshan now?

**Comment by sbernard31** [comment]
Only in the master branch. (it will be available in next release)

**Comment by madhushreegc** [comment]
I want to set parameters for every down link request .

Could you please help me to point to class name in master branch . I checked CoapRequestBuilder class but could not find the placeholder to set the parameters .
