### ISSUE TITLE
cf-oscore should set a meaninful PeerIdentity in the EndpointContext

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#974]
This concerns cf-oscore in M15.

It would be nice if cf-oscore could set a meaningful value for the PeerIdentity in the EndpointContext, e.g. ID Context || Sender ID from the matching OSCORE context.

**Comment by LudwigSeitz** [comment]
Perhaps some explanation on why this is useful: If two parties use OSCORE, they are implicitly authenticating each other (by possession of the correct OSCORE context), the authenticated identity can be useful e.g. for access control. I believe the authenticated identity is ID Context || Sender ID  (if ID Context is not null, otherwise just Sender ID).

**Comment by boaks** [comment]
I agree. 
Do you see any technical challenge?
Is there anything else hold you up to implement it and contribute it (beside of the time :-) )?
AFAIK, just derive a implementation class from `java.security.Principal` as the other `Identity` implementations in `org.eclipse.californium.elements.auth`.

**Comment by LudwigSeitz** [comment]
Besides time nothing, either Rikard or me could provide this, I just added the issue to document the need and have a discussion if needed.

**Comment by rikard-sics** [comment]
Yes, I have discussed this with Ludwig and can certainly do it in a future pull request.

As far as the best way to do it, would it be to set a Principal, accessible via getPeerIdentity() as with DTLS? Or should I rather extend californium/elements/EndpointContext.java with some other method to get OSCORE-related information?

It could for instance be the case that an application is using both DTLS and OSCORE for a communication channel.

**Comment by rikard-sics** [comment]
> Do you see any technical challenge?
> Is there anything else hold you up to implement it and contribute it (beside of the time :-) )?
> AFAIK, just derive a implementation class from `java.security.Principal` as the other `Identity` implementations in `org.eclipse.californium.elements.auth`.

Just to clarify if this is a potential issue but what if a certain connection is using both DTLS and OSCORE? In such case should information related to both OSCORE and DTLS be stored in the same Principal? Or would it be better to implement a separate method for OSCORE like getOscoreIdentity? Otherwise OSCORE and DTLS may conflict and overwrite each other's peer information.

**Comment by boaks** [comment]
> using both DTLS and OSCORE?

Just my first thoughts: 
Make it configurable. I'm not sure, if someone who uses both DTLS and OSOCRE, requires to get both. I would assume, that being able to select, which one is used, would be a good first approach. If a use-case comes up with both, then it would also be possible to extend it.

**Comment by boaks** [comment]
Maybe you can check PR #996, if the 

```
	public final Set<Principal> getExtendedInfo() {
		return additionalInfo;
	}
```

would generally work for you. 
For me, I'm not clear, if a `Map<String,Principal>` would be better to select the special Principal by a tag.

If the Set or Map looks good for you, I would, after merging PR #996, add a `amend(Set<Principal> additionInfo)` similar function to the `AddressEndpointContext`.

**Comment by rikard-sics** [comment]
> would generally work for you.
> For me, I'm not clear, if a `Map<String,Principal>` would be better to select the special Principal by a tag.
> 
> If the Set or Map looks good for you, I would, after merging PR #996, add a `amend(Set<Principal> additionInfo)` similar function to the `AddressEndpointContext`.

Yes, the current approach I was working on was to simply create a new AddressEndpointContext with the exact same information except also a Principal. Having a way to modify the existing AddressEndpointContext to change set the Principal would be useful.

**Comment by rikard-sics** [comment]
I have now created a PR regarding this. For now it does not overwrite any information set for DTLS by Scandium. Also currently I am creating new endpoint contexts but I could switch to an approach of modifying them as you suggest in your latest post if I add that functionality to the AddressEndpointContext.

**Comment by boaks** [comment]
Though 2.0.0-M16 is released, I was able to spend some more time into it.

Let me start to explain, why we introduced the `EndpointContext` and the `Principal`:

RFC7252 defines two rules to match request and responses:
[request-response-matching](https://tools.ietf.org/html/rfc7252#section-5.3.2)
[DTLS request-response-matching](https://tools.ietf.org/html/rfc7252#section-9.1.2)
  
However, if devices are intended to sleep or don't exchange messages for a while, it may happen, that a NAT changes that endpoint and so the matching will fail. For normal request that seems to be no issue, but for [observe/notify](https://tools.ietf.org/html/rfc7641) that causes pain.
There have been several discussions about that, and the currently final statement was.
[Carsten Bormann](https://mailarchive.ietf.org/arch/msg/core/h8NoXBwt3ttVkB5QZglMoW6Y--Y)

Since that, there was no general update for that matching and we decided to go for a flexible matching pattern. The `EndpointContext` provides all information, which may be used to match request and responses and the `Principal` is one of those artefacts (but it relies on unique credentials and so may not be always applicable) see the `PrincipalEndpointContextMatcher`.

There is also a second usage of this `EndpointContext`, it ensures, that a message is only sent, if the intended context is still the available one.

The OSCorePrincipal seems for me to be not used for these cases, or? 
If not, the `EndpointContext`offers already a way to amend information for the upper layers, it's the "none critical entries". With that you may add a `String` by a tag to the `EndpointContext`.

So, lets try to see, if the `OSCorePrincipal` is used as `Principal` and if it could be used for the two functions, request/response matching, and sent context. Do you have an ideas?

**Comment by rikard-sics** [comment]
> The OSCorePrincipal seems for me to be not used for these cases, or?
> If not, the `EndpointContext`offers already a way to amend information for the upper layers, it's the "none critical entries". With that you may add a `String` by a tag to the `EndpointContext`.
> 
> So, lets try to see, if the `OSCorePrincipal` is used as `Principal` and if it could be used for the two functions, request/response matching, and to validate the security sent context. Do you have an idea?

Yes, I see your points. Let me think about this further. Sorry if I am a little slow in responding as I'm traveling currently.

**Comment by boaks** [comment]
> Sorry if I am a little slow 

your welcome. I was much more delayed than you. 
For me it is a question, if using `Principal` (instead of `String` in the map entries) makes sense for use-cases you see.

**Comment by rikard-sics** [comment]
> The OSCorePrincipal seems for me to be not used for these cases, or?
> If not, the `EndpointContext`offers already a way to amend information for the upper layers, it's the "none critical entries". With that you may add a `String` by a tag to the `EndpointContext`.

Yes using the map of strings in the EndpointContext related classes could be a solution. The problems I see with that is it seems the AddressEndpointContext does not support this map. So support would have to be added to it.

Also the Sender ID and Context ID are really byte arrays but I suppose they could be expressed as a text representation of their byte string. So SenderID = new byte[] { 0xAA, 0xBB } would be "AABB" and SenderID = new byte[0] would be only "".

Possibly map keys giving the Sender ID and Context ID as their text equivalents could also be added when they are strings. So SenderID = new byte[] { 0x63, 0x6C, 0x69, 0x65, 0x6E, 0x74 } would be "client".

> So, lets try to see, if the `OSCorePrincipal` is used as `Principal` and if it could be used for the two functions, request/response matching, and to validate the security sent context. Do you have an idea?

Regarding response/request matching it could be possible to say that if a NAT changes the remote endpoint during an ongoing observation the endpoints should still match if the context ID and sender ID are the same and the OSCORE message validation succeeds. However normally the sender ID is not included in response messages.

Currently OSCORE matches requests/responses by letting CoAP handle that with the Token and endpoint matching. But in principal if a NAT changes the remote endpoint but the Token still matches an ongoing observation and the OSCORE validation of the message succeeds it could be considered still the same endpoint. 

Fundamentally for OSCORE an incoming request should be matched to its context using the Sender ID and Context ID. An incoming response will use the Token to match it to its context.

**Comment by boaks** [comment]
The "matching" based on the "endpoint context" was introduced, because the CoAP (protocol layer) is executed independent from the DTLS layer. While a CoAP server prepares a response, a new handshake may change the device. Without checking the session or principal, the response would be sent, using the new negotiated keys, and so the device could decrypt that message. The same may also happen for a CoAP client and so the response form a different server may accidentally delivered as responses. The data this matching is based, is extracted out of the handshakes and therefore considered to be valid.

I tried to understand the OSCORE code, but the "sender/recipient id" is currently not really used and your comment "However normally the sender ID is not included in response messages." makes me feel strange about that the source of these ids.

Would it be possible to provide some examples using these ids?

**Comment by rikard-sics** [comment]
> I tried to understand the OSCORE code, but the "sender/recipient id" is currently not really used and your comment "However normally the sender ID is not included in response messages." makes me feel strange about that the source of these id
>
> Would it be possible to provide some examples using these ids?

When a client sends an outgoing request the context to use is found using the URI of the request. The request is then protected with OSCORE using security material from the context (basically encrypted with the Sender Key). The Sender ID of that context is put in the OSCORE option of the outgoing request. The client notes the Token of this outgoing request and which context was used.

When the server receives an incoming request the context to use is found using the Sender ID in the OSCORE option. Then the request can be decrypted and checked with information from that context (basically decrypted with the Recipient Key).

The server then protects its response with the Sender Key of the same context, and transmits it to the client. Note that the Sender ID does not have to be included in the OSCORE option of a response. (But for instance in the Group OSCORE protocol it must be included since there can be multiple servers sending responses.)

The client then receives the response and identifies which context to use to unsecure it using the Token in the response. The reason the Sender ID does not have to be included in responses is that the client can understand which context to use from the Token in the outgoing request. It knows that for one request there is only one response and when the response comes can look up from the Token which context to use to unsecure the response.

https://tools.ietf.org/html/draft-ietf-core-object-security-16#page-25
> The 'kid' parameter.  The value is set to the Sender ID.  This
> parameter SHALL be present in requests and will not typically
> be present in responses.  An example where the Sender ID is
> included in a response is the extension of OSCORE to group
> communication [I-D.ietf-core-oscore-groupcomm].

> https://tools.ietf.org/html/draft-ietf-core-object-security-16#section-8.4
> 8.4 Verifying the response
>
> 2. Retrieve the Recipient Context in the Security Context associated
> with the Token.

The Recipient ID (and Sender ID and other parameters) will be included in the generation of security material like Sender Key and Recipient Key. Also the Sender ID of the client is the Recipient ID of the server, the Recipient ID of the client is the Sender ID of the server.

So when a server gets a request it will have the Sender ID of the client in the OSCORE option, when the server then searches for the correct context to use it will look for a context with a Recipient ID that matches the Sender ID of the client. So in that sense both the Sender ID and Recipient ID are used.

Additionally as in the case of LWM2M where the server can send requests to the client, the server's Sender ID (client's Recipient ID) will be included in outgoing requests. OSCORE uses the same context for communication in both directions. If a node (server or client) is sending a request it will include its own Sender ID in the request and the other node will look up the corresponding context with that Recipient ID.


But as a conclusion it may very well be the case that using a Principal for OSCORE is excessive since as you explained DTLS uses it for specific purposes that may not be relevant for OSCORE (or that OSCORE is taking care of that internally in a different way). Fundamentally we wanted this Principal not for request/response matching or checking that the security context is still available but to provide some information to the application about the OSCORE parameters used for a CoAP message. (More specifically in Ludwig's case checking what Sender ID and Context ID an incoming request came from.) For me using the map of strings in the EndpointContext seems to fulfill this purpose. If a need for a Principal for OSCORE is raised in the future we could revisit it then.

**Comment by boaks** [comment]
Thanks for the explanations! As far as can see, on the server side it's simple the oscore layer, which takes care of the right ids and contexts and so I don't see the "uncontrolled" changes. On the client side, the "token" seems to be the main ID to lookup for the other stuff. Failure on that should end up in MAC violations and so don't require "endpoint matching".

> For me using the map of strings in the EndpointContext seems to fullfill this purpose.

I also think, that this is the best fit for the use-cases so far.

> The problems I see with that is it seems the AddressEndpointContext does not support this map. So support would have to be added to it.

Please have a look at [MapBasedEndpointContext.addEntries](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L209), usually that should do the trick when you add your attributes with [KEY_PREFIX_NONE_CRITICAL](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L40) as prefix for your key(s).

**Comment by rikard-sics** [comment]
> Please have a look at [MapBasedEndpointContext.addEntries](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L209), usually that should do the trick when you add your attributes with [KEY_PREFIX_NONE_CRITICAL](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L40) as prefix for your key(s).

Yes I can add strings if the endpoint context is of that type or subtypes. But in the code I have now in the OSCorePeerIdentityHandler.java (https://github.com/eclipse/californium/pull/1002/commits/4bfe85d49831a1e95fe17c6e0d2ad370646975fd) I see that the types of endpoint contexts already set from elsewhere in Californium for the messages are as follows:

- Sending Request: AddressEndpointContext
- Receiving Request: UdpEndpointContext
- Sending Response: AddressEndpointContext
- Receiving Response: UdpEndpointContext

So for setting strings when receiving a response or when receiving a request I am fine. However I cannot set the strings in the contexts for sending a request or sending a response as those are of type AddressEndpointContext. In such case I would have to re-create them as MapBasedEndpointContext.

Another option is to not set the strings for outgoing messages at all. But in such case an application would not be able to check what OSCORE parameters an outgoing request or response used after it was sent.

**Comment by boaks** [comment]
The idea was to match base on the returns provided by "any" `EndpointContext` implementation. The sub-classes are "comfort" methods to create such `EndpointContext` in various use-cases.

For sending:
If you want to inform the sender about something, which was "added" to the destination context, we used the callback's `Message.onContextEstablished(EndpointContext endpointContext)`. With that, we don't alter the original context. That is implemented for Requests. To add the oscore stuff, we can add a additional callback to the Exchange, which is called before the endpoint context is set and forwarded to the request. I will prepare a PR for this in the afternoon (hopefully :-), so you should be able to check the idea.

**Comment by boaks** [comment]
Please try, if the Exchange EndpointContextOperator will do the job when sending a request.

**Comment by rikard-sics** [comment]
> Please try, if the Exchange EndpointContextOperator will do the job when sending a request.

Thanks! I will have a look at it.

So the idea would be that for receiving a request or response I can modify the existing UdpEndpointContext to add strings to the map?

And in the case of sending a request I can use this EndpointContextOperator? Should the EndpointContextOperator be set already in the application code that is sending the request? Or can I set it from somewhere in the OSCORE code, or is that too late since the endpoint context has already been created at that point?

As for the existing PR https://github.com/eclipse/californium/pull/1002 is it better if I close that one and create a brand new one?

**Comment by boaks** [comment]
> So the idea would be that for receiving a request or response I can modify the existing UdpEndpointContext to add strings to the map?

Yes, as long as you add the strings using
`public static MapBasedEndpointContext addEntries(EndpointContext context, String... attributes)` and keys with prefix `KEY_PREFIX_NONE_CRITICAL`. Please add your the strings with on call (k1, v1, k2, v2). Multiple calls may be somehow inefficient (k1,v1) (k2,v2).

> And in the case of sending a request I can use this EndpointContextOperator? 

Yes, if you want to report the `EndpointContext` with the added strings back to your application layer in `MessageObserver.onContextEstablished(EndpointContext)`.

> Should the EndpointContextOperator be set already in the application code that is sending the request? Or can I set it from somewhere in the OSCORE code, or is that too late since the endpoint context has already been created at that point?

My intention was, that the ObjectSecurityLayer set the operator, which adds the oscore information, in the Exchange when sending request. I don't see, how this could be done in the application code.
The `EndpointContext` provided by the `Request` is left unchanged, the resulting `EndpointContext` is reported in `MessageObserver.onContextEstablished(EndpointContext)`.

> As for the existing PR #1002 is it better if I close that one and create a brand new one?   

Close, yes, because the PR should be based now on "master".  
"brand new on"? I would go for 

1. "create" a new branch from current master.
1. "cherrypick' to old commit to the new branch.
1. fix the conflicts :-). 
1. make the unit test running

**Comment by rikard-sics** [comment]
> Yes, as long as you add the strings using
> `public static MapBasedEndpointContext addEntries(EndpointContext context, String... attributes)` and keys with prefix `KEY_PREFIX_NONE_CRITICAL`. Please add your the strings with on call (k1, v1, k2, v2). Multiple calls may be somehow inefficient (k1,v1) (k2,v2).

Okay, I will proceed like that for incoming messages.

> My intention was, that the ObjectSecurityLayer set the operator, which adds the oscore information, in the Exchange when sending request. I don't see, how this could be done in the application code.
> The `EndpointContext` provided by the `Request` is left unchanged, the resulting `EndpointContext` is reported in `MessageObserver.onContextEstablished(EndpointContext)`.

When it comes to outgoing requests, should I make a new class implementing the EndpointContextOperator interface and in the apply method there add the strings? Then for the outgoing requests I use setEndpointContextPreOperator on the exchange to set the operator?

> Close, yes, because the PR should be based now on "master".
> "brand new on"? I would go for
> 
> 1. "create" a new branch from current master.
> 2. "cherrypick' to old commit to the new branch.
> 3. fix the conflicts :-).
> 4. make the unit test running

Yes, that makes sense. I have closed the old PR and will make a new one based on code from the old with modifications.

**Comment by boaks** [comment]
> When it comes to outgoing requests, should I make a new class implementing the EndpointContextOperator interface and in the apply method there add the strings? Then for the outgoing requests I use setEndpointContextPreOperator on the exchange to set the operator?

Yes.

**Comment by rikard-sics** [comment]
I have now made a new PR following the approach of using strings in the endpoint context as we discussed. https://github.com/eclipse/californium/pull/1027

**Comment by rikard-sics** [comment]
I have now re-made the previous PR (https://github.com/eclipse/californium/pull/1027) as discussed here:
https://github.com/eclipse/californium/pull/1033

**Comment by boaks** [comment]
PR #1033 is merged. Please check, if it fixes this issue and close it , if so.

**Comment by LudwigSeitz** [comment]
Not the outcome I would have preferred. I now have to write custom code for DTLS and OSCORE, which I was trying to avoid. I do understand the issues you raised against overloading PeerIdentity with the OSCORE data though, so I'm going to have to live with this.
