### ISSUE TITLE
Support for RFC 7967

### ISSUE THREAD

**Issue by wegelid-wittra** [eclipse/californium#980]
I am currently using Eclipse Californium as a proxy from COAP to HTTP and would like to support [RFC 7967 - No server response](https://tools.ietf.org/html/rfc7967).

I found [this](https://www.eclipse.org/lists/cf-dev/msg01010.html) request for it from 2017 but it seems like nothing happened back then.

Has there been any update on this since then? If not, could someone point me in the right direction to implement this?

**Comment by boaks** [comment]
AFAIK, nothing was implemented.
If you're interested in, you may consider to implement it and contribute that. 
PR's are welcome :-).

**Comment by wegelid-wittra** [comment]
Do you have any pointers for where to start? :)

**Comment by boaks** [comment]
May be you can start to analyse the "multicast" support. 
It handles responses also in a special way.
Search for the references to `Request.isMulticast()`.

**Comment by wegelid-wittra** [comment]
I have started looking into this and have made some progress. I have added the No-Response to the option classes but now wonder how I should implement the actual functionality of not sending a response.

Examining `Request.isMulticast()` led me to the `CoapEndpoint` class.
1. Would the method `sendResponse()` be a good place to check the code of the response versus the No-Response option of the request, according to the [specification](https://tools.ietf.org/html/rfc7967#section-2.1)?
2. How do I properly cancel the response? Is calling `response.cancel()` enough?

Thank you

**Comment by boaks** [comment]
I would test to "stop"/"drop" the response at the `Exchange` and call "executeComplete".
(hope RFC 7967 has no blockwise ...)

**Comment by wegelid-wittra** [comment]
RFC 7967 does not mention blockwise which I would assume means that it should support it. Will this make things more complicated?

**Comment by boaks** [comment]
> RFC 7967 does not mention blockwise which I would assume means that it should support it.

Seems to be optimistic. I would assume, that it's not intended. Personally I would only use block2 for more than less static resources. And block2 doesn't make sense with "no response".  

> Will this make things more complicated?

Sure, the state-machine for blockwise isn't that easy :-).

**Comment by wegelid-wittra** [comment]
As I see it each block in a blockwise transfer is a request with a response and since RFC 7967 states that "the client can explicitly express to the server its disinterest in all responses against the particular request." I think that they should work together.

Why I want to implement this is to reduce the amount of traffic by letting the server omit the 2.31 Continue responses for each block in a blockwise transfer. The client could still send the last block without the No-Response option to get a response on whether the entire block transfer succeeded or not.

**Comment by boaks** [comment]
That would only apply for block1.

If you want to discuss that topic (RFC7967 in combination with RFC7959), 
the ietf core-mailing list is the best place to do so.

**Comment by boaks** [comment]
Thanks for starting to clarify it, I saw your mail on the core-mailing list!
 
About blockwise with option block1:
Your success will depend on a lot of stuff:
As less blocks are used, the more success you will have.

1. IP-address changes may break block1 transfers.
1. UDP packet drops will break the block1 transfers.
1. UDP packet reorder will break the block1 transfers.

The IP-address changes may be mitigated using DTLS1.2 CID. But for now, the CoAP layer doesn't replace the ip-address by the cid, so that may be working in the future, but not with the current version.

The reorder is in the "transparent blockwise" mode of californium also not implemented (it's not required assuming a response). Please disable it with `MAX_RESOURCE_BODY_SIZE=0`so all single request will be forwarded to your `CoapResource` and you may handle it in your code. In my experience reorder is very rare. May be you can just ignore it, but that depends on your communication environment and your own experience. 

For the drops I don't see a obvious solution within RFC7252 or RFC7959.
Assume in your network environment you lose 2% and you need 4 blocks, that would result in 7.8% lose for the complete transfer. With 8 blocks it's about 15%.  So the success will really depend on how many blocks you will transfer.

I would recommend to start with analyze the communication environment to find out, if that approach makes sense.

**Comment by sbernard31** [comment]
I just link the [core discussion](https://mailarchive.ietf.org/arch/msg/core/x7m70O0_bnQifB_4lK9mECQ1Ov8).

**Comment by boaks** [comment]
My feeling is, without the blockwise support, you lost your interest.
If so, please close the issue.

**Comment by wegelid-wittra** [comment]
Yes. For now I will hold off on adding the No-Response option. Thank your for your help.
