### ISSUE TITLE
Response is beign ignored by CoAP client

### ISSUE THREAD

**Issue by logo17** [eclipse/californium#991]
After making a CoAP Observe NON-GET request I'm geeting the following response:

/Matcher: Duplicate response for open exchange: NON-2.05   MID=21707

However I debugging I see that the payload response is different than the first response. How can I accept duplicate response in the client side?

**Comment by boaks** [comment]
> However I debugging I see that the payload response is different than the first response. 

There is only one response defined for CoAP RFC7252. Therefore removing the second is the right way to process such a second response.

You may consider to use the extension Observe/Notify (RFC7641) by using [Request.setObserve()](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/coap/Request.java#L627).

For further questions, please provide the information requested for new issues.

**Comment by logo17** [comment]
Thanks for the quick response. Sure, I'm calling client.observe function:

`val uri = URI(String.format("%s://%s%s", coapScheme, coapHost, path))
            val coapClient = CoapClient(uri)
            coapClient.useNONs()
            coapClient.observe(object : CoapHandler{
                override fun onLoad(response: CoapResponse?) {
                    Timber.d("Message received: %s", response?.responseText)
                }

                override fun onError() {
                    Timber.e("Error")
                }

            })`

And checking the observe function it's calling 'setObserve':

`public CoapObserveRelation observe(CoapHandler handler) {
		Request request = Request.newGet().setURI(uri).setObserve();
		return observe(request, handler);
	}`

**Comment by boaks** [comment]
When a new issue is created, the following text should be displayed:

# Please providing basic issue information

issues may be answered much faster, if you provide more details ahead!

* branch your faced the issue. Currently 
   * 1.0 is the release, 
   * 1.1 is the master, 
   * and 2.0 is the development branch
* If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
  commit your using
* If your issue is related to your own snippet, please provide that
* If you have logs, please provide them
* If you have tcpdump captures (wireshark), please provide them.

**Comment by boaks** [comment]
So, which branch are you using?
Are you using a different implementation on the server side?
Can you provide a wireshark log?

> Duplicate response for open exchange: NON-2.05 MID=21707

Is mostly related to reused MID, which may be an issue of the server. The wireshark log will bring more light.
